// Generated Help Map file.
// Commands (ID_* and IDM_*)
#define HID_REGEXFILTER                         0x101F4
#define HID_INDICATOR_LEFTVIEW                  0x107D0
#define HID_INDICATOR_RIGHTVIEW                 0x107D1
#define HID_INDICATOR_BOTTOMVIEW                0x107D2
#define HID_INDICATOR_LEFTVIEWCOMBOENCODING     0x107DA
#define HID_INDICATOR_RIGHTVIEWCOMBOENCODING    0x107DB
#define HID_INDICATOR_BOTTOMVIEWCOMBOENCODING   0x107DC
#define HID_INDICATOR_LEFTVIEWCOMBOEOL          0x107E4
#define HID_INDICATOR_RIGHTVIEWCOMBOEOL         0x107E5
#define HID_INDICATOR_BOTTOMVIEWCOMBOEOL        0x107E6
#define HID_INDICATOR_LEFTVIEWCOMBOTABMODE      0x107EE
#define HID_INDICATOR_RIGHTVIEWCOMBOTABMODE     0x107EF
#define HID_INDICATOR_BOTTOMVIEWCOMBOTABMODE    0x107F0
#define HID_INDICATOR_LEFTENCODINGSTART         0x10834
#define HID_INDICATOR_RIGHTENCODINGSTART        0x10848
#define HID_INDICATOR_BOTTOMENCODINGSTART       0x1085C
#define HID_INDICATOR_LEFTEOLSTART              0x10898
#define HID_INDICATOR_RIGHTEOLSTART             0x108AC
#define HID_INDICATOR_BOTTOMEOLSTART            0x108C0
#define HID_INDICATOR_LEFTTABMODESTART          0x108FC
#define HID_INDICATOR_RIGHTTABMODESTART         0x10910
#define HID_INDICATOR_BOTTOMTABMODESTART        0x10924
#define HID_INDICATOR_COLUMN                    0x1092E
#define HID_INDICATOR_MARKEDWORDS               0x1092F
#define HID_VIEW_WHITESPACES                    0x18006
#define HID_VIEW_ONEWAYDIFF                     0x18007
#define HID_NAVIGATE_NEXTDIFFERENCE             0x1800B
#define HID_NAVIGATE_PREVIOUSDIFFERENCE         0x1800C
#define HID_VIEW_OPTIONS                        0x1800E
#define HID_EDIT_FINDNEXT                       0x18016
#define HID_FILE_RELOAD                         0x1801A
#define HID_VIEW_LINEDOWN                       0x1801F
#define HID_NAVIGATE_PREVIOUSCONFLICT           0x18022
#define HID_NAVIGATE_NEXTCONFLICT               0x18024
#define HID_EDIT_MARKASRESOLVED                 0x18028
#define HID_VIEW_SWITCHLEFT                     0x1802B
#define HID_VIEW_LINELEFT                       0x1802D
#define HID_VIEW_LINERIGHT                      0x1802E
#define HID_VIEW_SHOWFILELIST                   0x18031
#define HID_EDIT_FINDPREV                       0x18032
#define HID_EDIT_USETHEIRBLOCK                  0x18033
#define HID_EDIT_USEMYBLOCK                     0x18034
#define HID_EDIT_USETHEIRTHENMYBLOCK            0x18035
#define HID_EDIT_USEMINETHENTHEIRBLOCK          0x18036
#define HID_VIEW_INLINEDIFFWORD                 0x18039
#define HID_EDIT_CREATEUNIFIEDDIFFFILE          0x1803C
#define HID_CARET_LEFT                          0x1803D
#define HID_CARET_RIGHT                         0x1803E
#define HID_CARET_DOWN                          0x1803F
#define HID_CARET_UP                            0x18040
#define HID_CARET_WORDLEFT                      0x18041
#define HID_CARET_WORDRIGHT                     0x18042
#define HID_VIEW_LINEDIFFBAR                    0x18055
#define HID_VIEW_LOCATORBAR                     0x18056
#define HID_EDIT_USELEFTBLOCK                   0x18057
#define HID_EDIT_USELEFTFILE                    0x18058
#define HID_EDIT_USEBLOCKFROMLEFTBEFORERIGHT    0x18059
#define HID_EDIT_USEBLOCKFROMRIGHTBEFORELEFT    0x1805B
#define HID_VIEW_COLLAPSED                      0x18066
#define HID_VIEW_COMPAREWHITESPACES             0x18067
#define HID_VIEW_IGNOREWHITESPACECHANGES        0x18068
#define HID_VIEW_IGNOREALLWHITESPACECHANGES     0x18069
#define HID_NAVIGATE_NEXTINLINEDIFF             0x1806B
#define HID_NAVIGATE_PREVINLINEDIFF             0x1806C
#define HID_NAVIGATE_NEXTINLINEDIFFERENCE       0x1806E
#define HID_NAVIGATE_PREVIOUSINLINEDIFFERENCE   0x1806F
#define HID_VIEW_MOVEDBLOCKS                    0x18070
#define HID_VIEW_WRAPLONGLINES                  0x18071
#define HID_EDIT_SELECTALL                      0x18073
#define HID_VIEW_INLINEDIFF                     0x18079
#define HID_EDIT_FINDNEXTSTART                  0x1807B
#define HID_EDIT_FINDPREVSTART                  0x1807C
#define HID_EDIT_GOTOLINE                       0x1807D
#define HID_VIEW_IGNORECOMMENTS                 0x18080
#define HID_LOGOBUTTON                          0x18081
#define HID_VIEW_BARS                           0x18082
#define HID_VIEW_IGNOREEOL                      0x18083
#define HID_USEBLOCKS                           0x18092
#define HID_EDIT_ENABLE                         0x180D0
#define HID_FILE_ENABLEEDIT                     0x180D2
#define HID_EDIT_REGEXFILTER                    0x180E0
#define HID_REGEXFILTER_REGEXFILTER             0x180E1
#define HID_EDIT_THREEWAY_ACTIONS               0x180E9
#define HID_REGEX_NO_FILTER                     0x180EA
// Prompts (IDP_*)
#define HIDP_OLE_INIT_FAILED                    0x30065
// Resources (IDR_*)
#define HIDR_MAINFRAME                          0x20001
#define HIDR_REGEXFILTERINI                     0x200A6
#define HIDR_IGNORECOMMENTSTXT                  0x200A9
#define HIDR_TGITMERGELOGO                      0x200AC
#define HIDR_HELPALIAS                          0x200AD
#define HIDR_HELPCONTEXT                        0x200AE
// Dialogs (IDD_*)
#define HIDD_SETMAINPAGE                        0x2006B
#define HIDD_OPENDLG                            0x20082
#define HIDD_DIFFLOCATOR                        0x20083
#define HIDD_FILEPATCHES                        0x20087
#define HIDD_ABOUT                              0x20088
#define HIDD_LINEDIFF                           0x20089
#define HIDD_SETCOLORPAGE                       0x2008A
#define HIDD_FIND                               0x2008B
#define HIDD_GOTO                               0x2009B
#define HIDD_REGEXFILTERS                       0x200A4
#define HIDD_REGEXFILTER                        0x200A5
#define HIDD_ENCODING                           0x2012C
