// Generated Help Map file.
// Commands (ID_* and IDM_*)
#define HID_REVGRAPH_ZOOMCOMBO                  0x111E7
#define HID_FIND                                0x111EA
#define HID_VIEW_ZOOMIN                         0x18004
#define HID_VIEW_ZOOMOUT                        0x18005
#define HIDM_SHOWFINDBAR                        0x18013
#define HIDM_FINDNEXT                           0x18015
#define HIDM_FINDPREV                           0x18016
#define HIDM_FINDEXIT                           0x18017
#define HID_VIEW_ZOOM100                        0x18023
#define HID_VIEW_ZOOMALL                        0x18024
#define HID_FILE_SAVEGRAPHAS                    0x18025
#define HID_FILE_SAVESTATGRAPHAS                0x18026
#define HID_FILTER_EXCLUDEPATHS                 0x18027
#define HID_FILTER_EXCLUDEREVISIONS             0x18028
#define HID_VIEW_ZOOMHEIGHT                     0x18029
#define HID_VIEW_ZOOMWIDTH                      0x1802A
#define HID_VIEW_GROUPBRANCHES                  0x1802B
#define HID_VIEW_TOPALIGNTREES                  0x1802C
#define HID_VIEW_SHOWOVERVIEW                   0x1802D
#define HID_VIEW_TOPDOWN                        0x1802E
#define HID_URL_FOCUS                           0x1802E
#define HID_VIEW_SHOWHEAD                       0x1802F
#define HID_VIEW_SHOWDIFFPATHS                  0x18030
#define HID_VIEW_SHOWALLREVISIONS               0x18031
#define HID_VIEW_EXACTCOPYSOURCE                0x18032
#define HID_VIEW_FOLDTAGS                       0x18033
#define HID_VIEW_REMOVEDELETEDONES              0x18034
#define HID_LOGDLG_REFRESH                      0x18035
#define HID_LOGDLG_FIND                         0x18036
#define HID_VIEW_REMOVEUNCHANGEDBRANCHES        0x18037
#define HID_VIEW_REMOVETAGS                     0x18038
#define HID_LOGDLG_FOCUSFILTER                  0x18039
#define HID_VIEW_SHOWWCREV                      0x1803A
#define HID_FOCUS_MESSAGE                       0x18045
#define HID_VIEW_SHOWWCMODIFICATION             0x18046
#define HID_VIEW_FILTER                         0x18047
#define HID_VIEW_SHOWTREESTRIPES                0x18048
#define HID_MENUEXIT                            0x1804A
#define HID_MENUHELP                            0x1804B
#define HID_VIEW_COMPAREREVISIONS               0x1804C
#define HID_VIEW_COMPAREHEADREVISIONS           0x1804D
#define HID_VIEW_UNIFIEDDIFF                    0x1804E
#define HID_VIEW_UNIFIEDDIFFOFHEADREVISIONS     0x1804F
#define HID_FOCUS_FILELIST                      0x18059
#define HID_GO_FORWARD                          0x18063
#define HID_GO_BACKWARD                         0x18064
#define HID_GO_UP                               0x18065
#define HID_GO_DOWN                             0x18066
#define HID_GO_BACKWARD_SELECT                  0x18067
#define HID_GO_FORWARD_SELECT                   0x18068
#define HID_SELECT_SEARCHFIELD                  0x18069
#define HID_EXITCLEARFILTER                     0x1806A
#define HID_VIEW_SHOWBRANCHINGSANDMERGES        0x1806A
#define HID_VIEW_SHOWALLTAGS                    0x1806B
#define HID_VIEW_ARROW_POINT_TO_MERGES          0x1806C
#define HID_STAGING_STAGESELECTEDLINES          0x1806D
#define HID_STAGING_STAGESELECTEDHUNKS          0x1806E
#define HID_UNSTAGING_UNSTAGESELECTEDLINES      0x1806F
#define HID_UNSTAGING_UNSTAGESELECTEDHUNKS      0x18070
// Prompts (IDP_*)
// Resources (IDR_*)
#define HIDR_MAINFRAME                          0x20001
#define HIDR_ACC_PATCHVIEW                      0x2006D
#define HIDR_STATGRAPH                          0x200EB
#define HIDR_ACC_LOGDLG                         0x200FE
#define HIDR_DOWNLOAD                           0x20107
#define HIDR_ACC_COMMITDLG                      0x20145
#define HIDR_REVISIONGRAPH                      0x20167
#define HIDR_STAGING                            0x2016C
#define HIDR_TGITLOGO                           0x20172
#define HIDR_HELPALIAS                          0x20174
#define HIDR_HELPCONTEXT                        0x20175
#define HIDR_REVGRAPHBAR                        0x211E5
#define HIDR_REVGRAPHGLYPHS                     0x211E6
// Dialogs (IDD_*)
#define HIDD_SETTINGSPROXY                      0x20066
#define HIDD_SETTINGSHOOKS                      0x20067
#define HIDD_SETTINGSOVERLAY                    0x2006A
#define HIDD_SETTINGSSAVEDDATA                  0x2006C
#define HIDD_ABOUT                              0x20081
#define HIDD_LOGMESSAGE                         0x20082
#define HIDD_PROMPT                             0x20083
#define HIDD_SVNPROGRESS                        0x20086
#define HIDD_COMMITDLG                          0x20087
#define HIDD_SETTINGSMAIN                       0x2008F
#define HIDD_FINDBAR                            0x20090
#define HIDD_RENAME                             0x20097
#define HIDD_REPOSITORY_BROWSER                 0x20099
#define HIDD_ADD                                0x2009B
#define HIDD_CHANGEDFILES                       0x2009E
#define HIDD_SIMPLEPROMPT                       0x200A0
#define HIDD_INPUTDLG                           0x200A1
#define HIDD_URL                                0x200A4
#define HIDD_SETTINGSPROGSADV                   0x200AA
#define HIDD_TOOLASSOC                          0x200AB
#define HIDD_CHECKFORUPDATES                    0x200AE
#define HIDD_REVERT                             0x200AF
#define HIDD_LFS_LOCKS                          0x200B0
#define HIDD_STATGRAPH                          0x200B3
#define HIDD_SETOVERLAYICONS                    0x200B8
#define HIDD_SETTINGSPROGSDIFF                  0x200C0
#define HIDD_SETTINGSPROGSMERGE                 0x200C1
#define HIDD_SETTINGSLOOKANDFEEL                0x200C3
#define HIDD_SETTINGSDIALOGS                    0x200C4
#define HIDD_SETTINGSDIALOGS2                   0x200C5
#define HIDD_DIFFFILES                          0x200C7
#define HIDD_RESOLVE                            0x200CF
#define HIDD_HISTORYDLG                         0x200D3
#define HIDD_SETTINGSCOLORS_2                   0x200D4
#define HIDD_SETTINGSHOOKCONFIG                 0x200EC
#define HIDD_EXPORT                             0x200EE
#define HIDD_CREATECHANGELIST                   0x200F3
#define HIDD_SETTINGSTBLAME                     0x200F4
#define HIDD_FIRSTSTARTWIZARD_START             0x20114
#define HIDD_SETTINGSBUGTRAQ                    0x2011B
#define HIDD_SETTINGSBUGTRAQADV                 0x2011C
#define HIDD_CLONE                              0x20129
#define HIDD_GITPROGRESS                        0x2012C
#define HIDD_PULLFETCH                          0x2012E
#define HIDD_PUSH                               0x2012F
#define HIDD_GITSWITCH                          0x20130
#define HIDD_AUTOTEXTTESTDLG                    0x20132
#define HIDD_NEW_BRANCH_TAG                     0x20135
#define HIDD_APPLY_PATCH_LIST                   0x20137
#define HIDD_FORMAT_PATCH                       0x20138
#define HIDD_MERGE                              0x20139
#define HIDD_SETTINGSCOLORS_1                   0x2013B
#define HIDD_SETTINGSCOLORS_3                   0x2013C
#define HIDD_RESET                              0x2013D
#define HIDD_REBASE                             0x2013E
#define HIDD_REBASECHERRYPICK                   0x2013F
#define HIDD_SENDMAIL                           0x20140
#define HIDD_SETTINGSMTP                        0x20141
#define HIDD_BROWSE_REFS                        0x20142
#define HIDD_ADD_REMOTE                         0x20143
#define HIDD_SYNC                               0x20146
#define HIDD_BUGTRAQREGEXTESTER                 0x20147
#define HIDD_PATCH_VIEW                         0x20148
#define HIDD_SVNIGNORE                          0x20149
#define HIDD_CREATEREPO                         0x2014A
#define HIDD_SVNDCOMMITTYPE                     0x2014B
#define HIDD_SETTINGSPROGSALTERNATIVEEDITOR     0x2014D
#define HIDD_REQUESTPULL                        0x2014E
#define HIDD_SETTINGSOVERLAYHANDLERS            0x20152
#define HIDD_SETTINGS_CONFIG                    0x20154
#define HIDD_LOGORDERING                        0x20159
#define HIDD_SETTINGSUDIFF                      0x20165
#define HIDD_REFLOG                             0x20634
#define HIDD_SUBMODULE_ADD                      0x20635
#define HIDD_RESOLVE_CONFLICT                   0x211D8
#define HIDD_SETTINGIT_CONFIG                   0x211D9
#define HIDD_SETTINREMOTE                       0x211DA
#define HIDD_SETTINGSBUGTRAQ_CONFIG             0x211DB
#define HIDD_CLEAN                              0x211DC
#define HIDD_SETTINGSEXTMENU                    0x211DD
#define HIDD_BISECTSTART                        0x211DE
#define HIDD_STASH                              0x211DF
#define HIDD_DIFFSUBMODULE                      0x211E0
#define HIDD_IGNORE                             0x211E1
#define HIDD_SUBMODULE_UPDATE                   0x211E2
#define HIDD_DELETEREMOTETAG                    0x211E3
#define HIDD_REVISIONGRAPH                      0x211E4
#define HIDD_REVGRAPHFILTER                     0x211E8
#define HIDD_USER_PASSWD                        0x211E9
#define HIDD_SETTINGSCREDENTIAL                 0x211EF
#define HIDD_MERGEABORT                         0x211F0
#define HIDD_SETTINGSDIALOGS3                   0x211F1
#define HIDD_CERTCHECK                          0x211F2
#define HIDD_RESOLVESUBMODULECONFLICT           0x211F3
#define HIDD_COMMITISONREFS                     0x211F4
#define HIDD_FIRSTSTARTWIZARD_USER              0x211F5
#define HIDD_FIRSTSTARTWIZARD_GIT               0x211F6
#define HIDD_FIRSTSTARTWIZARD_AUTHENTICATION    0x211F7
#define HIDD_FIRSTSTARTWIZARD_LANGUAGE          0x211F8
#define HIDD_SELECTREMOTEREF                    0x211F9
#define HIDD_SETTINGSWIN11CONTEXTMENU           0x211FA
#define HIDD_WORKTREE_CREATE                    0x211FB
#define HIDD_WORKTREE_LIST                      0x211FC
