//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resourceshell.rc
//
#define IDI_PULL                        5
#define IDD_PROPPAGE                    107
#define IDI_APP                         108
#define IDS_MENUUPDATE                  121
#define IDS_MENUCOMMIT                  122
#define IDI_UPDATE                      122
#define IDS_MENUCREATEREPOS             123
#define IDI_COMMIT                      123
#define IDS_MENUADD                     124
#define IDI_ADD                         124
#define IDS_MENUREVERT                  125
#define IDI_REVERT                      125
#define IDS_MENUCLEANUP                 126
#define IDI_CLEANUP                     126
#define IDS_MENURESOLVE                 127
#define IDI_RESOLVE                     127
#define IDS_MENUSWITCH                  128
#define IDI_SWITCH                      128
#define IDS_MENUMERGE                   129
#define IDI_MERGE                       129
#define IDS_MENUBRANCH                  130
#define IDS_MENUIMPORT                  131
#define IDI_EXPORT                      131
#define IDS_MENUEXPORT                  132
#define IDI_COPY                        132
#define IDS_MENUSETTINGS                133
#define IDI_DELETE                      133
#define IDS_MENUABOUT                   134
#define IDI_RENAME                      134
#define IDS_MENUSUBMENU                 135
#define IDI_DIFF                        135
#define IDI_LOG                         136
#define IDS_MENUBISECTSTART             136
#define IDS_MENUDESCUPDATE              137
#define IDI_ABOUT                       137
#define IDS_MENUBISECTGOOD              137
#define IDS_MENUDESCCOMMIT              138
#define IDI_SETTINGS                    138
#define IDS_MENUDESCADD                 139
#define IDI_CREATEREPOS                 139
#define IDS_MENUDESCREVERT              140
#define IDI_CONFLICT                    140
#define IDS_MENUDESCCLEANUP             141
#define IDI_RELOCATE                    141
#define IDS_MENUDESCRESOLVE             142
#define IDI_HELP                        142
#define IDS_MENUDESCSWITCH              143
#define IDI_SHOWCHANGED                 143
#define IDI_IGNORE                      144
#define IDS_MENUASSUMEVALID             144
#define IDS_MENUDESCEXPORT              145
#define IDS_MENUDESCABOUT               146
#define IDS_MENUDESCCREATEREPOS         147
#define IDS_MENUDESCCOPY                148
#define IDS_MENUDESCMERGE               149
#define IDS_MENUDESCSETTINGS            150
#define IDS_MENUDESCDEFAULT             151
#define IDS_STATUSNONE                  152
#define IDS_STATUSUNVERSIONED           153
#define IDS_STATUSNORMAL                154
#define IDS_STATUSADDED                 155
#define IDS_STATUSABSENT                156
#define IDS_STATUSDELETED               157
#define IDS_STATUSREPLACED              158
#define IDS_STATUSMODIFIED              159
#define IDS_STATUSMERGED                160
#define IDS_STATUSCONFLICTED            161
#define IDS_STATUSOBSTRUCTED            162
#define IDS_MENUBISECTBAD               163
#define IDS_PROPPROPERTY                164
#define IDS_PROPVALUE                   165
#define IDS_MENURENAME                  166
#define IDS_MENUDESCRENAME              167
#define IDS_MENUREMOVE                  168
#define IDS_MENUDESCREMOVE              169
#define IDS_MENUUPDATEEXT               170
#define IDS_MENUDESCUPDATEEXT           171
#define IDS_MENUBISECTRESET             171
#define IDS_MENUBISECTSKIP              172
#define IDS_MENUDESCBISECTSKIP          173
#define IDS_MENUDIFF                    176
#define IDS_MENUDESCDIFF                177
#define IDS_DROPCOPYADDMENU             178
#define IDS_DROPMOVEMENU                179
#define IDS_MENULOG                     180
#define IDS_MENUDESCLOG                 181
#define IDS_MENUCONFLICT                186
#define IDS_MENUDESCCONFLICT            187
#define IDS_MENUDESCBISECTSTART         188
#define IDS_MENUDESCBISECTGOOD          189
#define IDS_MENUHELP                    190
#define IDS_MENUDESCHELP                191
#define IDS_MENUSHOWCHANGED             192
#define IDS_MENUDESCSHOWCHANGED         193
#define IDS_MENUIGNORE                  194
#define IDS_MENUDESCIGNORE              195
#define IDS_STATUSINCOMPLETE            196
#define IDS_STATUSIGNORED               197
#define IDS_DROPCOPYMENU                198
#define IDS_PROPWAITCANCEL              199
#define IDS_SETPROPTITLE                200
#define IDS_MENUDESCBISECTBAD           201
#define IDS_MENUDESCBISECTRESET         202
#define IDS_MENUBLAME                   203
#define IDS_STATUSEXTERNAL              204
#define IDS_MENUDESCBLAME               205
#define IDS_MENUSVNFETCH                206
#define IDS_MENUAPPLYPATCH              207
#define IDS_MENUDESCCREATEPATCH         208
#define IDS_MENUDESCAPPLYPATCH          209
#define IDS_MENUDESCSVNFETCH            210
#define IDS_MENULOGSUBMODULE            211
#define IDS_MENUUNDOADD                 212
#define IDS_MENUDESCUNDOADD             213
#define IDS_MENUPREVDIFF                214
#define IDS_MENUDESCPREVDIFF            215
#define IDS_MENUDAEMON                  216
#define IDS_MENUDESCDAEMON              217
#define IDS_DROPEXPORTMENU              218
#define IDS_DROPEXPORTEXTENDEDMENU      219
#define IDS_MENUIGNOREMULTIPLEMASK      220
#define IDS_MENUPULL                    221
#define IDS_MENUPUSH                    222
#define IDS_MENUCLONE                   223
#define IDS_MENUMERGEABORT              224
#define IDS_MENUCLIPPASTE               225
#define IDS_MENUDESCCLIPPASTE           226
#define IDS_MENUREPOBROWSE              227
#define IDS_MENUDESCREPOBROWSE          228
#define IDS_MENUDESCMERGEABORT          229
#define IDS_MENUIGNOREMULTIPLE          231
#define IDS_MENUDIFFLATER               232
#define IDS_MENUDESCDIFFLATER           233
#define IDS_MENUDIFFNOW                 234
#define IDS_MENUUNIGNORE                237
#define IDS_MENUDESCUNIGNORE            238
#define IDS_DROPCOPYRENAMEMENU          250
#define IDS_FILEPROPONFOLDER            253
#define IDS_PROPSNOTSAVED               254
#define IDS_DROPMOVERENAMEMENU          256
#define IDS_MENUREMOVEKEEP              271
#define IDS_MENUDESCREMOVEKEEP          272
#define IDS_YES                         273
#define IDS_NO                          274
#define IDS_MENUIGNOREMULTIPLEMASK2     282
#define IDS_MENUIGNOREMULTIPLE2         283
#define IDS_MENUDELETEIGNOREMULTIPLE2   284
#define IDS_MENUDELETEIGNOREMULTIPLEMASK2 285
#define IDS_MENUTAG                     307
#define IDS_MENUFORMATPATCH             308
#define IDS_MENUIMPORTPATCH             309
#define IDS_MENUFETCH                   311
#define IDS_MENUREBASE                  312
#define IDS_MENUSTASHSAVE               313
#define IDS_MENUSTASHAPPLY              314
#define IDS_MENUSUBADD                  315
#define IDS_MENUSUBSYNC                 316
#define IDS_MENUREFLOG                  317
#define IDS_MENUDESCREFLOG              318
#define IDS_MENUSTASHLIST               319
#define IDS_REFLOG_DEL                  320
#define IDI_MENUSYNC                    321
#define IDS_MENUSENDMAIL                321
#define IDS_MENUDESSENDMAIL             322
#define IDS_MENUREFBROWSE               333
#define IDS_MENUDESCREFBROWSE           334
#define IDS_MENUSVNREBASE               335
#define IDS_MENUSVNREBASE_DESC          336
#define IDS_MENUSVNDCOMMIT              337
#define IDS_MENUSVNDCOMMIT_DESC         338
#define IDS_MENUSYNC                    339
#define IDS_MENUDESCSYNC                340
#define IDS_MENUSTASHPOP                341
#define IDS_MENUSVNIGNORE               342
#define IDS_MENUSVNIGNORE_DESC          343
#define IDS_MENUDIFFTWO                 344
#define IDS_MENUDESCDIFFTWO             345
#define IDS_MENUDESCIMPORTPATCH         346
#define IDS_MENUDESCPULL                347
#define IDS_MENUDESCPUSH                348
#define IDS_MENUDESCCLONE               349
#define IDS_MENUDESCFETCH               350
#define IDS_MENUDELETEIGNOREMULTIPLE    351
#define IDS_MENUDELETEIGNOREMULTIPLEMASK 352
#define IDS_MENUDELETEIGNORE            353
#define IDS_MENUDESCDELETEIGNORE        354
#define IDS_MENUCOMMITSUBMODULE         355
#define IDI_REVISIONGRAPH               366
#define IDS_MENUREVISIONGRAPH           367
#define IDS_MENUDESCREVISIONGRAPH       368
#define IDS_LOADING                     369
#define IDC_HEAD_HASH                   1001
#define IDC_LAST_HASH                   1002
#define IDC_SHELL_CURRENT_BRANCH        1003
#define IDC_HEAD_SUBJECT                1004
#define IDC_LAST_SUBJECT                1005
#define IDC_HEAD_AUTHOR                 1007
#define IDC_LAST_AUTHOR                 1008
#define IDC_HEAD_DATE                   1009
#define IDC_LAST_DATE                   1010
#define IDC_SHELL_REMOTE_URL            1011
#define IDC_SHOWLOG                     1016
#define IDC_SHOWSETTINGS                1017
#define IDI_REPOBROWSE                  5145
#define IDI_BLAME                       5146
#define IDI_PATCH                       5147
#define IDI_CREATEPATCH                 5150
#define IDI_MENUFILE                    5154
#define IDI_MENUFOLDER                  5155
#define IDI_MENULINK                    5156
#define IDI_MENUMULTIPLE                5157
#define IDI_APPSMALL                    5160
#define IDI_SHELVE                      5161
#define IDI_UNSHELVE                    5162
#define IDI_CLIPPASTE                   5164
#define IDI_PUSH                        5166
#define IDI_CLONE                       5167
#define IDI_TAG                         5168
#define IDI_REBASE                      5169
#define IDI_COMBINE                     5170
#define IDI_SKIP                        5171
#define IDI_EDIT                        5172
#define IDI_SQUASH                      5173
#define IDI_PICK                        5174
#define IDI_MENUSENDMAIL                5175
#define IDI_COPYCLIP                    5176
#define IDI_THUMB_DOWN                  5178
#define IDI_THUMB_UP                    5179
#define IDI_DAEMON                      5180
#define IDI_MERGEABORT                  5181
#define IDI_BISECT                      5182
#define IDI_BISECT_RESET                5183
#define IDI_SHOWBRANCHES                5184
#define IDC_CONFIG_AUTOCRLF             11020
#define IDC_EDITPROPERTIES              11021
#define IDC_REPOURLUNESCAPED            11022
#define IDC_SHELL_REMOTE_BRANCH         11022
#define IDC_ESCAPEDURLLABEL             11023
#define IDC_REPOUUID                    11024
#define IDC_CONFIG_SAFECRLF             11024
#define IDC_CHANGELIST                  11025
#define IDC_CONFIG_USERNAME             11025
#define IDC_DEPTHEDIT                   11026
#define IDC_CONFIG_USEREMAIL            11026
#define IDC_CHECKSUM                    11027
#define IDC_ASSUMEVALID                 11027
#define IDC_EXECUTABLE                  11028
#define IDC_SKIPWORKTREE                11029
#define IDC_STATIC_LASTMODIFIED         11030
#define IDC_SYMLINK                     11031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5185
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         11032
#define _APS_NEXT_SYMED_VALUE           5101
#endif
#endif
