//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\TortoiseGit\src\Resources\TortoiseProcENG.rc
//
#define IDR_MAINFRAME                   1
#define IDC_USELOCAL                    3
#define IDC_USEREPO                     4
#define IDD_SETTINGSPROXY               102
#define IDD_SETTINGSHOOKS               103
#define IDD_SETTINGSOVERLAY             106
#define IDD_SETTINGSSAVEDDATA           108
#define IDI_COMMIT                      123
#define IDI_REVERT                      125
#define IDD_ABOUT                       129
#define IDD_LOGMESSAGE                  130
#define IDD_PROMPT                      131
#define IDD_CHECKOUT                    133
#define IDD_SVNPROGRESS                 134
#define IDD_COMMITDLG                   135
#define IDI_DIFF                        135
#define IDD_COPY                        142
#define IDD_SETTINGSMAIN                143
#define IDR_ANIMATION                   148
#define IDR_MOVEANI                     149
#define IDD_RENAME                      151
#define IDD_ADD                         155
#define IDD_CHANGEDFILES                158
#define IDD_SIMPLEPROMPT                160
#define IDD_INPUTDLG                    161
#define IDR_SEARCH                      163
#define IDI_DRIVES                      164
#define IDD_URL                         164
#define IDI_SSH                         165
#define IDI_PROXY                       166
#define IDI_MISC                        167
#define IDB_LOGOFLIPPED                 168
#define IDB_TTF_BMP                     169
#define IDD_SETTINGSPROGSADV            170
#define IDD_TOOLASSOC                   171
#define IDD_CHECKFORUPDATES             174
#define IDD_REVERT                      175
#define IDD_STATGRAPH                   179
#define IDD_PATCH_FILE_OPEN_CUSTOM      180
#define IDD_OVERLAYICONS                184
#define IDD_SETOVERLAYICONS             184
#define IDI_SET_OVERLAYS                190
#define IDD_SETTINGSPROGSDIFF           192
#define IDD_SETTINGSPROGSMERGE          193
#define IDD_SETTINGSPROGSUNIDIFF        194
#define IDD_SETTINGSLOOKANDFEEL         195
#define IDI_GENERAL                     195
#define IDD_SETTINGSDIALOGS             196
#define IDI_LOOKANDFEEL                 196
#define IDI_ICONSET                     197
#define IDI_DIALOGS                     198
#define IDD_DIFFFILES                   199
#define IDR_HTML_CLONEDLG               200
#define IDB_CANCELHIGHLIGHT             201
#define IDB_BITMAP1                     203
#define IDD_RESOLVE                     207
#define IDI_WARNING_GENERAL             210
#define IDD_HISTORYDLG                  211
#define IDR_CLEANUPANI                  212
#define IDD_SETTINGSCOLORS              212
#define IDD_SETTINGSCOLORS_2            212
#define IDI_ACTIONADDED                 213
#define IDD_SETTINGSMISC                213
#define IDI_ACTIONDELETED               214
#define IDI_ACTIONMODIFIED              215
#define IDI_ACTIONREPLACED              216
#define IDI_SAVEDDATA                   225
#define IDI_GRAPHBAR                    229
#define IDI_GRAPHBARSTACKED             230
#define IDI_GRAPHLINE                   231
#define IDI_GRAPHLINESTACKED            232
#define IDI_GRAPHPIE                    233
#define IDI_SWITCHLEFTRIGHT             234
#define IDR_STATGRAPH                   235
#define IDD_SETTINGSHOOKCONFIG          236
#define IDI_HOOK                        237
#define IDD_EXPORT                      238
#define IDD_INPUTLOGDLG                 241
#define IDD_CREATECHANGELIST            243
#define IDI_REPO_FILE                   244
#define IDD_SETTINGSTBLAME              244
#define IDI_REPO_HTTP                   245
#define IDI_REPO_HTTPS                  246
#define IDI_REPO_SVN                    247
#define IDI_REPO_SVNSSH                 248
#define IDI_REPO_UNKNOWN                249
#define IDC_PANCUR                      250
#define IDC_PANCURDOWN                  251
#define IDI_TORTOISEBLAME               252
#define IDR_ACC_LOGDLG                  254
#define IDI_ADD_BKG                     255
#define IDI_RESOLVE_BKG                 256
#define IDI_REVERT_BKG                  257
#define IDI_COMMIT_BKG                  258
#define IDI_CFM_BKG                     260
#define IDR_DOWNLOAD                    263
#define IDI_CANCELNORMAL                264
#define IDI_CANCELPRESSED               265
#define IDI_LOGFILTER                   266
#define IDI_FILTEREDIT                  267
#define IDD_CONFLICTRESOLVE             268
#define IDI_COPY_BKG                    270
#define IDI_EXPORT_BKG                  271
#define IDI_IMPORT_BKG                  272
#define IDI_MERGE_BKG                   273
#define IDI_RENAME_BKG                  274
#define IDI_SWITCH_BKG                  275
#define IDD_PROPPAGE_LARGE              278
#define IDD_DIALOG1                     279
#define IDD_SETTINGSBUGTRAQ             283
#define IDD_SETTINGSBUGTRAQ_            283
#define IDD_SETTINGSBUGTRAQ_A           283
#define IDI_BUGTRAQ                     284
#define IDD_SETTINGSBUGTRAQADV          284
#define IDI_UP                          286
#define IDI_MKDIR                       289
#define IDI_REFRESH                     290
#define IDI_SAVE                        291
#define IDI_SAVEAS                      292
#define IDI_EXPLORER                    293
#define IDI_OPEN                        294
#define IDD_CLONE                       297
#define IDB_GIT                         299
#define IDD_GITPROGRESS                 300
#define IDD_PULLFETCH                   302
#define IDD_PUSH                        303
#define IDD_GITSWITCH                   304
#define IDD_NEW_BRANCH_TAG              309
#define IDD_APPLY_PATCH_LIST            311
#define IDD_FORMAT_PATCH                312
#define IDD_MERGE                       313
#define IDD_GIT_HISTORY                 314
#define IDD_SETTINGSCOLORS_1            315
#define IDD_SETTINGSCOLORS_3            316
#define IDD_RESET                       317
#define IDD_REBASE                      318
#define IDI_GITCONFIG                   319
#define IDI_GITREMOTE                   320
#define IDD_SENDMAIL                    320
#define IDD_SETTINGSMTP                 321
#define IDD_DIALOG_BROWSE_REFS          322
#define IDD_ADD_REMOTE                  323
#define IDD_DIALOG2                     324
#define IDR_ACC_COMMITDLG               325
#define IDD_SYNC                        326
#define IDD_PATCH_VIEW                  328
#define IDD_SVNIGNORE                   329
#define IDD_CREATEREPO                  330
#define IDD_SVNDCOMMITTYPE              331
#define IDI_ACTIONFETCHING              332
#define IDD_SETTINGSPROGSALTERNATIVEEDITOR 333
#define IDD_REQUESTPULL                 334
#define IDB_BITMAP2                     336
#define IDB_BITMAP_REFTYPE              336
#define IDI_IMPORTPATHCES_BKG           337
#define IDD_SETTINGSOVERLAYHANDLERS     338
#define IDS_CHSTAT_FILECOL              1000
#define IDS_CHSTAT_WCCOL                1001
#define IDS_CHSTAT_REPOCOL              1002
#define IDC_LOGLIST                     1003
#define IDS_WARN_CONFIRM_MOVE_SPECIAL_DIRECTORY 1003
#define IDC_PASSEDIT                    1004
#define IDS_SETTINGS_BUGTRAQ_PATHCOL    1004
#define IDC_INFOTEXT                    1005
#define IDS_SETTINGS_BUGTRAQ_PROVIDERCOL 1005
#define IDS_SETTINGS_BUGTRAQ_PARAMETERSCOL 1006
#define IDS_ERR_MISSING_PROVIDER        1007
#define IDS_ERR_PROVIDER_VALIDATE_FAILED 1008
#define IDS_ERR_NO_AVAILABLE_BUGTRAQ_PROVIDERS 1009
#define IDC_CHECKOUTDIRECTORY           1010
#define IDS_SETTINGS_BUGTRAQ_SELECTFOLDERPATH 1010
#define IDS_FILEDIFF_STATADD            1011
#define IDS_FILEDIFF_STATDEL            1012
#define IDC_SVNPROGRESS                 1013
#define IDS_LOG_FILE_LINE_ADD           1013
#define IDC_LOGMESSAGE                  1014
#define IDS_LOG_FILE_LINE_Del           1014
#define IDS_LOG_FILE_LINE_DEL           1014
#define IDC_LOGMSG                      1015
#define IDC_EXTDIFF                     1015
#define IDS_ERR_TGITBLAME               1015
#define IDC_EXTMERGE                    1016
#define IDC_EXTDIFFPROPS                1016
#define IDS_PROC_RESETBRANCH            1016
#define IDC_DIFFVIEWER                  1017
#define IDS_LOG_PUSH                    1017
#define IDS_FILEDIFF_LOG                1018
#define IDS_PROC_TASKS                  1019
#define IDS_STATUSLIST_CONTEXT_COMPARETWOFILES 1020
#define IDC_EXTDIFFBROWSE               1021
#define IDS_B_T_INVALID                 1021
#define IDC_EXTMERGEBROWSE              1022
#define IDC_EXTDIFFPROPSBROWSE          1022
#define IDS_B_T_LOCALEMPTY              1022
#define IDC_CHANGEDDIRS                 1023
#define IDC_ENABLE                      1023
#define IDC_SAVECHECK                   1023
#define IDS_B_T_BOTHEMPTY               1023
#define IDC_NAME                        1027
#define IDC_SERVERADDRESS               1027
#define IDC_USEREDIT                    1027
#define IDC_URLCOMBO                    1029
#define IDC_FONTNAMES                   1030
#define IDC_LOGBUTTON                   1031
#define IDC_GETALL                      1031
#define IDC_EDITCONFIG                  1031
#define IDC_UPDATE                      1031
#define IDC_BROWSE                      1035
#define IDC_CHECKOUTDIRECTORY_BROWSE    1036
#define IDC_INCLUDEPATHS                1036
#define IDC_REPOS_TREE                  1037
#define IDC_SERVERPORT                  1038
#define IDC_USERNAME                    1039
#define IDC_PASSWORD                    1040
#define IDC_TIMEOUT                     1041
#define IDC_FILELIST                    1043
#define IDC_ADDLIST                     1043
#define IDC_CHANGEDLIST                 1043
#define IDC_MENULIST                    1043
#define IDC_REVERTLIST                  1043
#define IDC_LANGUAGECOMBO               1044
#define IDC_FROMURL                     1045
#define IDC_COMMIT_TO                   1046
#define IDC_REMOVABLE                   1048
#define IDC_NETWORK                     1049
#define IDC_FIXED                       1050
#define IDC_CDROM                       1051
#define IDC_HINTLABEL                   1052
#define IDC_VERSIONABOUT                1054
#define IDC_CLEARAUTH                   1059
#define IDC_UNKNOWN                     1061
#define IDC_INPUTTEXT                   1064
#define IDC_HINTTEXT                    1065
#define IDC_SELECTALL                   1067
#define IDC_SSHCLIENT                   1068
#define IDC_INCLUDE_IGNORED             1068
#define IDC_SSHBROWSE                   1069
#define IDC_DEFAULTLOG                  1071
#define IDC_RELATIVETIMES               1072
#define IDC_DONTCONVERT                 1073
#define IDC_RAM                         1073
#define IDC_CHECKNEWERVERSION           1073
#define IDC_SHOWUNVERSIONED             1073
#define IDC_EXPORT_CHECKOUTDIR          1074
#define IDC_VERSIONBOX                  1075
#define IDC_LABEL                       1076
#define IDC_MSGVIEW                     1077
#define IDC_EXCEPTIONS                  1077
#define IDC_BUGID                       1077
#define IDC_EXCLUDEPATHS                1077
#define IDC_DRIVEGROUP                  1079
#define IDC_PROXYGROUP                  1080
#define IDC_SSHGROUP                    1081
#define IDC_MISCGROUP                   1082
#define IDC_COMMITGROUP                 1083
#define IDC_WEBLINK                     1084
#define IDC_SUPPORTLINK                 1085
#define IDC_FONTSIZES                   1086
#define IDC_COMMITFILETIMES             1088
#define IDC_ONLYEXPLORER                1088
#define IDC_DIFFVIEWERBROWSE            1089
#define IDC_EXTDIFFADVANCED             1090
#define IDC_EXTDIFF_OFF                 1091
#define IDC_EXTDIFF_ON                  1092
#define IDC_EXTMERGEADVANCED            1093
#define IDC_EXTDIFFPROPS_OFF            1093
#define IDC_EXTMERGE_OFF                1094
#define IDC_EXTDIFFPROPS_ON             1094
#define IDC_EXTMERGE_ON                 1095
#define IDC_DIFFVIEWER_OFF              1096
#define IDC_DIFFVIEWER_ON               1097
#define IDC_ADDTOOL                     1098
#define IDC_EDITTOOL                    1099
#define IDC_REMOVETOOL                  1100
#define IDS_AUTH_USERNAME               1100
#define IDS_AUTH_PASSWORD               1101
#define IDC_TOOLLISTCTRL                1101
#define IDC_EXTEDIT                     1102
#define IDC_TOOLEDIT                    1103
#define IDC_TOOLBROWSE                  1104
#define IDC_SHORTDATEFORMAT             1105
#define IDC_SUMMARYTEXT                 1106
#define IDC_STATISTICS                  1108
#define IDC_TEXT_INFO                   1109
#define IDC_COMMITLABEL                 1110
#define IDS_REG_ERROR                   1110
#define IDC_PROGRESS                    1111
#define IDC_YOURVERSION                 1112
#define IDC_CURRENTVERSION              1113
#define IDC_CHECKRESULT                 1114
#define IDC_BUGIDLABEL                  1119
#define IDC_OLDLOGS                     1124
#define IDC_ICONSETCOMBO                1124
#define IDC_CHIST                       1125
#define IDC_KEEPLISTS                   1126
#define IDC_SHOWEXCLUDEDASNORMAL        1126
#define IDC_LOG_FIRSTPARENT             1126
#define IDC_IGNOREEOL                   1126
#define IDC_SORTBYCOMMITCOUNT           1126
#define IDC_DIFFBYDOUBLECLICK           1127
#define IDC_CHECK_STOPONCOPY            1130
#define IDC_CHECK_UNTRACKED             1130
#define IDC_GRAPH                       1131
#define IDC_STATBUTTON                  1132
#define IDC_PATCH_TO_CLIPBOARD          1132
#define IDC_SELECTOVERLAYSET            1132
#define IDC_LOG                         1132
#define IDC_GRAPHCOMBO                  1133
#define IDC_GRAPHTYPELABEL              1134
#define IDC_COMMITSEACHWEEK             1135
#define IDC_MOSTACTIVEAUTHOR            1136
#define IDC_LEASTACTIVEAUTHOR           1137
#define IDC_FILECHANGESEACHWEEK         1138
#define IDC_COMMITSEACHWEEKAVG          1140
#define IDC_COMMITSEACHWEEKMIN          1141
#define IDC_COMMITSEACHWEEKMAX          1142
#define IDC_MOSTACTIVEAUTHORAVG         1143
#define IDC_MOSTACTIVEAUTHORMIN         1144
#define IDC_MOSTACTIVEAUTHORMAX         1145
#define IDC_LEASTACTIVEAUTHORAVG        1146
#define IDC_LEASTACTIVEAUTHORMIN        1147
#define IDC_LEASTACTIVEAUTHORMAX        1148
#define IDC_FILECHANGESEACHWEEKAVG      1149
#define IDC_FILECHANGESEACHWEEKMIN      1150
#define IDC_FILECHANGESEACHWEEKMAX      1151
#define IDS_MSGBOX_HELP                 1152
#define IDS_MSGBOX_DONOTSHOWAGAIN       1153
#define IDS_MSGBOX_ABORT                1154
#define IDS_MSGBOX_RETRY                1155
#define IDC_MOSTACTIVEAUTHORNAME        1155
#define IDS_MSGBOX_IGNORE               1156
#define IDC_LEASTACTIVEAUTHORNAME       1156
#define IDS_MSGBOX_CANCEL               1157
#define IDC_AVG                         1157
#define IDS_MSGBOX_TRYAGAIN             1158
#define IDC_MIN                         1158
#define IDS_MSGBOX_CONTINUE             1159
#define IDC_MAX                         1159
#define IDS_MSGBOX_OK                   1160
#define IDC_NUMWEEK                     1160
#define IDS_MSGBOX_YES                  1161
#define IDC_NUMAUTHOR                   1161
#define IDS_MSGBOX_NO                   1162
#define IDC_NUMCOMMITS                  1162
#define IDS_SVNACTION_ADD               1163
#define IDC_NUMFILECHANGES              1163
#define IDS_SVNACTION_COPY              1164
#define IDC_NUMWEEKVALUE                1164
#define IDS_SVNACTION_DELETE            1165
#define IDC_NUMAUTHORVALUE              1165
#define IDS_SVNACTION_RESTORE           1166
#define IDC_NUMCOMMITSVALUE             1166
#define IDS_SVNACTION_REVERT            1167
#define IDC_NUMFILECHANGESVALUE         1167
#define IDS_SVNACTION_RESOLVE           1168
#define IDS_SVNACTION_UPDATE            1169
#define IDC_SHOWFOLDERSTATUS            1169
#define IDS_SVNACTION_COMPLETED         1170
#define IDC_ICONSETLABEL                1170
#define IDS_SVNACTION_EXTERNAL          1171
#define IDC_ICONLIST                    1171
#define IDS_SVNACTION_MODIFIED          1172
#define IDC_LISTRADIO                   1172
#define IDS_SVNACTION_REPLACED          1173
#define IDC_SYMBOLRADIO                 1173
#define IDS_SVNACTION_POSTFIX           1174
#define IDS_SVNACTION_FAILEDREVERT      1175
#define IDS_SVNACTION_STATUS            1176
#define IDS_SVNACTION_SKIP              1177
#define IDS_PROGS_EXTCOL                1178
#define IDS_PROGS_TOOLCOL               1179
#define IDS_LOG_FILE                    1180
#define IDS_SVN_USERCANCELLED           1181
#define IDC_AUTOCLOSECOMBO              1181
#define IDS_LOG_SIZE                    1182
#define IDC_COPYHEAD                    1182
#define IDC_COPYWC                      1183
#define IDS_ERR_INVALIDPATH             1183
#define IDC_AUTOCOMPLETION              1184
#define IDC_COPYREV                     1185
#define IDC_COPYREVTEXT                 1186
#define IDC_BROWSEFROM                  1187
#define IDC_SPLITTERTOP                 1191
#define IDC_SPLITTERBOTTOM              1192
#define IDC_SEARCHEDIT                  1194
#define IDC_FILTERICON                  1196
#define IDC_DATETO                      1198
#define IDC_DATEFROM                    1199
#define IDS_SSL_CERTIFICATETYPE         1200
#define IDC_FROMLABEL                   1200
#define IDS_SSL_ACCEPTQUESTION          1201
#define IDC_TOLABEL                     1201
#define IDS_SSL_CLIENTCERTIFICATEFILENAME 1202
#define IDS_SSL_PEM                     1203
#define IDC_WHOLE_PROJECT               1203
#define IDS_SSL_PKCS12                  1204
#define IDS_IMPORT_DEFAULTMSG           1205
#define IDS_LOG_COPYFROM                1206
#define IDC_CHECKBOX                    1207
#define IDC_SHOWWHOLEPROJECT            1208
#define IDC_SHOWUNMODIFIED              1209
#define IDS_LOG_REVERT_CONFIRM          1211
#define IDC_OLDAPILOGS                  1214
#define IDC_CHECKNEWERBUTTON            1215
#define IDS_LOG_POPUP_COPY              1216
#define IDC_CHECKNEWERBUTTON2           1216
#define IDC_MSYSGIT_CHECK               1216
#define IDS_COMMITDLG_FILE              1217
#define IDS_COMMITDLG_STATUS            1218
#define IDC_FILTERCANCEL                1218
#define IDS_COMMITDLG_ASKADD            1219
#define IDS_COMMITDLG_NOTHINGTOCOMMIT   1220
#define IDC_REALM                       1220
#define IDS_PROGRS_ATREV                1221
#define IDC_AUTOCOMPLETIONTIMEOUT       1221
#define IDS_PROGRS_ACTION               1222
#define IDC_AUTOCOMPLETIONTIMEOUTLABEL  1222
#define IDS_PROGRS_PATH                 1223
#define IDC_RECURSIVECHECK              1223
#define IDS_PROGRS_TITLEFIN             1224
#define IDC_SPELL                       1224
#define IDS_PROGRS_TITLE_CHECKOUT       1225
#define IDS_PROGRS_TITLE_IMPORT         1226
#define IDC_WCPATHLABEL                 1226
#define IDS_PROGRS_TITLE_UPDATE         1227
#define IDC_REPOCHECK                   1227
#define IDS_PROGRS_TITLE_COMMIT         1228
#define IDS_PROGRS_TITLE_ADD            1229
#define IDC_HIDEPATHS                   1229
#define IDS_PROGRS_TITLE_REVERT         1230
#define IDC_WCURLFROM                   1230
#define IDS_PROGRS_TITLE_RESOLVE        1231
#define IDC_RESOLVELIST                 1231
#define IDS_PROGRS_TITLE_SWITCH         1232
#define IDC_DOSWITCH                    1232
#define IDS_PROGRS_TITLE_EXPORT         1233
#define IDS_PROGRS_TITLE_MERGE          1234
#define IDS_PROGRS_TITLE_COPY           1235
#define IDS_PROGRS_MIMETYPE             1236
#define IDS_PROGRS_COPY_WARNING         1238
#define IDC_EXTERNALWARNING             1238
#define IDS_PROGRS_COMMITT_TRUNK        1239
#define IDC_SOUNDS                      1239
#define IDS_PROGRS_REVERTMARKERS        1240
#define IDC_ENABLEACCELERATORS          1240
#define IDS_SETTINGS_SELECTDIFF         1241
#define IDC_MESSAGEGROUP                1241
#define IDS_SETTINGS_SELECTDIFFVIEWER   1242
#define IDC_LISTGROUP                   1242
#define IDS_SETTINGS_SELECTMERGE        1243
#define IDC_PROGRESSBAR                 1243
#define IDS_SETTINGS_SELECTSSH          1244
#define IDC_PROGRESSLABEL               1244
#define IDS_SETTINGS_EXTDIFF_TT         1245
#define IDC_HISTORYLIST                 1245
#define IDS_SETTINGS_EXTDIFFBROWSE_TT   1246
#define IDC_HISTORY                     1246
#define IDS_SETTINGS_CHANGEDDIRS_TT     1247
#define IDS_MSYSGIT_PATH_TT             1248
#define IDS_SETTINGS_FOLDERSTATUS_TT    1249
#define IDC_CONFLICTCOLOR               1249
#define IDS_SETTINGS_EXTMERGE_TT        1250
#define IDC_ADDEDCOLOR                  1250
#define IDS_SETTINGS_PROXYSERVER_TT     1251
#define IDC_DELETEDCOLOR                1251
#define IDS_SETTINGS_DIFFVIEWER_TT      1252
#define IDC_MERGEDCOLOR                 1252
#define IDS_SETTINGS_AUTOCLOSE_TT       1253
#define IDC_MODIFIEDCOLOR               1253
#define IDS_UTILS_SELECTTEXTVIEWER      1254
#define IDC_RESTORE                     1254
#define IDS_SETTINGS_CONVERTBASE_TT     1255
#define IDC_DELETEDNODECOLOR            1255
#define IDS_PROC_WARNREVERT             1256
#define IDC_ADDEDNODECOLOR              1256
#define IDS_PROC_CLEANUPFINISHED        1257
#define IDC_RENAMEDNODECOLOR            1257
#define IDS_PROC_REPOCREATEERR          1258
#define IDC_REPLACEDNODECOLOR           1258
#define IDS_PROC_EXPORT_1               1259
#define IDC_COPYSTARTLABEL              1259
#define IDS_PROC_EXPORT_2               1260
#define IDC_UNVERSIONEDRECURSE          1260
#define IDS_PROC_EXPORT_3               1261
#define IDC_SKIPPER                     1261
#define IDS_PROC_EXPORT_4               1262
#define IDC_SKIPPERLABEL                1262
#define IDS_PROC_COPY_SUCCESS           1263
#define IDC_STACKED                     1263
#define IDS_PROC_SETTINGS_TITLE         1264
#define IDC_SHOWIGNORED                 1264
#define IDC_SHOWUSERPROPS               1265
#define IDC_AUTHORSCASESENSITIVE        1265
#define IDS_SETTINGS_ALTERNATIVEEDITOR_TT 1265
#define IDS_PROC_OVERWRITE_CONFIRM      1266
#define IDS_PROC_REPOCREATEFINISHED     1267
#define IDC_MAXHISTORY                  1268
#define IDS_PROC_MOVING                 1269
#define IDC_CACHEDEFAULT                1269
#define IDS_PROC_RELOCATING             1270
#define IDC_CACHESHELL                  1270
#define IDC_CACHESHELL2                 1271
#define IDC_CACHENONE                   1272
#define IDS_MSGBOX_DONOTSHOW            1272
#define IDC_URLHISTORY                  1272
#define IDS_PROC_COPYING                1273
#define IDC_URLHISTCLEAR                1273
#define IDS_PROC_COPYINGPROG            1274
#define IDC_LOGHISTORY                  1274
#define IDS_PROC_MOVINGPROG             1275
#define IDC_LOGHISTCLEAR                1275
#define IDS_PROC_CPYMVPROG2             1276
#define IDC_RESIZABLEHISTCLEAR          1276
#define IDS_PROC_ENTERURL               1277
#define IDC_RESIZABLEHISTORY            1277
#define IDC_AUTHHISTORY                 1278
#define IDS_SETTINGS_SHORTDATEFORMAT_TT 1279
#define IDC_BUTTON4                     1279
#define IDC_AUTHHISTCLEAR               1279
#define IDC_HOOKADDBUTTON               1279
#define IDC_BUGTRAQADDBUTTON            1279
#define IDC_BUTTON_TABCTRL              1279
#define IDS_SETTINGS_RELATIVETIMES_TT   1280
#define IDC_REPOLOG                     1280
#define IDC_REPOLOGCLEAR                1281
#define IDS_ERR_EXTDIFFSTART            1282
#define IDS_ERR_NOCOMMAND               1283
#define IDS_ERR_NOCOMMANDVALUE          1284
#define IDS_ERR_NOSTATUS                1285
#define IDS_ERR_CLEANUP                 1286
#define IDS_ERR_NOURLOFFILE             1287
#define IDC_GROUP                       1287
#define IDS_ERR_WCCHANGED               1288
#define IDS_ERR_COPYFILES               1289
#define IDS_ERR_EXTMERGESTART           1290
#define IDS_ERR_NOTUPTODATE             1291
#define IDS_ERR_FAILEDIGNOREPROPERTY    1292
#define IDS_ERR_DIFFVIEWSTART           1293
#define IDS_ERR_SSL_VALIDATE            1294
#define IDS_ERR_SSL_UNKNOWNCA           1295
#define IDS_ERR_SSL_CNMISMATCH          1296
#define IDC_ASPDOTNETHACK               1296
#define IDS_ERR_SSL_EXPIREDORNOTYETVALID 1297
#define IDC_GRAPHBARBUTTON              1297
#define IDS_SSL_ACCEPTALWAYS            1298
#define IDC_GRAPHBARSTACKEDBUTTON       1298
#define IDS_SSL_ACCEPTTEMP              1299
#define IDC_GRAPHLINEBUTTON             1299
#define IDS_SSL_REJECT                  1300
#define IDC_GRAPHLINESTACKEDBUTTON      1300
#define IDS_ERR_SSL_NOTYETVALID         1301
#define IDC_GRAPHPIEBUTTON              1301
#define IDC_FIRSTURL                    1301
#define IDS_ERR_SSL_EXPIRED             1302
#define IDC_DIFFSTATIC1                 1302
#define IDS_ERR_COPYITSELF              1303
#define IDC_SECONDURL                   1303
#define IDS_ERR_INVALIDREV              1304
#define IDC_DIFFSTATIC2                 1304
#define IDS_ERR_EMPTYDIFF               1305
#define IDS_ERR_NOTHINGTOADD            1306
#define IDS_ERR_ERROR                   1307
#define IDC_SWITCHLEFTRIGHT             1307
#define IDS_ERR_NOVALIDPATH             1308
#define IDS_ERR_FAILEDUNIGNOREPROPERTY  1309
#define IDS_ERR_NOTHINGTOREVERT         1310
#define IDS_ERR_NOCOMMONCOPYFROM        1311
#define IDS_ERR_GDIPLUS_MISSING         1312
#define IDC_SPLITTER                    1312
#define IDS_ERR_NOTENOUGHMEMORY         1313
#define IDC_UNVERSIONEDASMODIFIED       1313
#define IDS_ERR_MUSTBEURL               1314
#define IDS_ERR_INVALIDREVNOWC          1315
#define IDC_FLOPPY                      1315
#define IDS_ERR_MERGEIDENTICALREVISIONS 1316
#define IDC_REOPENCOMMIT                1316
#define IDC_MAXHISTORYLABEL             1317
#define IDS_ERR_NOHOOKTYPESPECIFIED     1317
#define IDS_ERR_NOHOOKPATHSPECIFIED     1318
#define IDS_ERR_NOHOOKCOMMANDPECIFIED   1319
#define IDS_ERR_HOOKFAILED              1320
#define IDS_ERR_INVALIDREVRANGE         1322
#define IDC_HOOKPATH                    1323
#define IDS_ERR_NOPREVREVISION          1323
#define IDC_HOOKBROWSE                  1324
#define IDS_PROC_CLEANUPFINISHED_FAILED 1324
#define IDC_HOOKCOMMANDLINE             1325
#define IDS_ERR_TWOLOGPARAMS            1325
#define IDC_HIDECHECK                   1326
#define IDS_ERR_TEXTVIEWSTART           1326
#define IDC_WAITCHECK                   1327
#define IDS_ERR_FAILEDISSUETRACKERCOM   1327
#define IDC_HOOKTYPECOMBO               1329
#define IDC_HOOKLIST                    1330
#define IDC_HOOKEDITBUTTON              1331
#define IDC_HOOKREMOVEBUTTON            1332
#define IDC_HOOKCOMMANDBROWSE           1333
#define IDC_HOOKTYPELABEL               1334
#define IDC_HOOKWCPATHLABEL             1335
#define IDC_HOOKCMLABEL                 1336
#define IDC_LOGINFO                     1337
#define IDC_EOLCOMBO                    1341
#define IDC_EOLLABEL                    1342
#define IDC_REV1BTN                     1353
#define IDC_REV2BTN                     1354
#define IDC_ACTIONLABEL                 1356
#define IDC_GROUPBOX                    1359
#define IDC_CHECKOUTPATH                1361
#define IDC_BROWSECHECKOUTPATH          1362
#define IDC_CHECKOUTURL                 1363
#define IDC_HOOKCOPYBUTTON              1367
#define IDC_INFOLABEL                   1368
#define IDC_LIST1                       1372
#define IDC_BUGTRAQLIST                 1372
#define IDC_LIST_PATCH                  1372
#define IDC_COMMIT_LIST                 1372
#define IDC_LIST_REMOTE                 1372
#define IDC_LIST_REF_LEAFS              1372
#define IDC_NEWLINESCOLOR               1378
#define IDC_OLDLINESCOLOR               1380
#define IDC_TABSIZE                     1381
#define IDC_BUTTON1                     1382
#define IDC_REFRESH                     1382
#define IDC_RESOLVEALLLATER             1382
#define IDC_ACTIONLOGSHOW               1382
#define IDC_BUGTRAQEDITBUTTON           1382
#define IDC_BUGTRAQBUTTON               1382
#define IDC_RESTOREDEFAULTS             1382
#define IDC_OPTIONS                     1382
#define IDC_CLONE_BROWSE_URL            1382
#define IDC_BUTTON_SHOW                 1382
#define IDC_BUTTON_ADD                  1382
#define IDC_REMOTE_MANAGE               1382
#define IDC_PROGRESS_BUTTON1            1382
#define IDC_BUTTON_LOCAL_BRANCH         1382
#define IDC_EDITGLOBALGITCONFIG         1382
#define IDC_SHOW_MODIFIED_FILES         1382
#define IDC_BUTTON_SHOW_ENV             1382
#define IDC_REPOGROUP                   1383
#define IDC_BUTTON3                     1383
#define IDC_CLONE_DIR_BROWSE            1383
#define IDC_BUTTON_TO                   1383
#define IDC_BUTTON_UP                   1383
#define IDC_REBASE_POST_BUTTON          1383
#define IDC_BUTTON_REMOTE_BRANCH        1383
#define IDC_EDITLOCALGITCONFIG          1383
#define IDC_COMMIT                      1383
#define IDC_BUTTON_BAD                  1383
#define IDC_TOURLLABEL                  1384
#define IDC_BUTTON_DIR                  1384
#define IDC_BUTTON_DOWN                 1384
#define IDC_PUTTYKEYFILE_BROWSE         1384
#define IDC_BUTTON_SHOW2                1384
#define IDC_BUTTON_UP2                  1384
#define IDC_BUTTON_STASH                1384
#define IDC_FROMGROUP                   1385
#define IDC_BUTTON_REMOVE               1385
#define IDC_BUTTON_DOWN2                1385
#define IDC_MSGGROUP                    1386
#define IDC_FILTER                      1387
#define IDC_REVISIONGROUP               1393
#define IDC_REPOLABEL                   1394
#define IDC_EDITCONFLICT                1399
#define IDS_WARN_FOLDERNOTEXIST         1400
#define IDC_RESOLVED                    1400
#define IDS_WARN_SHAREFILEACCESS        1401
#define IDC_CHOOSELABEL                 1402
#define IDC_RESOLVELABEL                1403
#define IDS_WARN_FOLDERNOTEMPTY         1404
#define IDC_LEAVELABEL                  1404
#define IDS_WARN_WARNING                1405
#define IDC_SELECTFILESONCOMMIT         1405
#define IDS_WARN_NOTE                   1406
#define IDC_ORLABEL                     1406
#define IDS_WARN_NOVALIDPATH            1407
#define IDC_ORLABEL2                    1407
#define IDC_PROXYLABEL1                 1409
#define IDC_PROXYLABEL2                 1410
#define IDS_WARN_COPYHEADWITHLOCALMODS  1411
#define IDC_PROXYLABEL3                 1411
#define IDC_PROXYLABEL4                 1412
#define IDC_PROXYLABEL5                 1413
#define IDC_PROXYLABEL6                 1414
#define IDC_SYSTEMLOCALEFORDATES        1426
#define IDC_ACTIONLOGCLEAR              1427
#define IDC_MAXLINES                    1428
#define IDC_DEFAULTOFFLINE              1431
#define IDC_SHOWIGNOREDOVERLAY          1432
#define IDC_NONINTERACTIVE              1432
#define IDC_USERECYCLEBIN               1432
#define IDC_TEXTSIZE2                   1462
#define IDC_SHOWUNVERSIONEDOVERLAY      1462
#define IDC_ABORT                       1465
#define IDC_LINK                        1466
#define IDC_LINK_CHANGE_LOG             1467
#define IDC_EDIT1                       1469
#define IDC_BUGTRAQPARAMETERS           1469
#define IDC_CLONE_DIR                   1469
#define IDC_BUGTRAQREMOVEBUTTON         1470
#define IDC_GIT_USEREMAIL               1470
#define IDC_EDIT_REMOTE                 1470
#define IDC_SMTP_PORT                   1470
#define IDC_EDIT3                       1470
#define IDC_EDIT_SVN_FROM               1470
#define IDC_VER2EDIT                    1470
#define IDC_REV2EDIT                    1470
#define IDC_BUGTRAQCOPYBUTTON           1471
#define IDC_GIT_USERESINGNINGKEY        1471
#define IDC_BUGTRAQWCPATHLABEL          1472
#define IDC_BUGTRAQPATH                 1473
#define IDC_BUGTRAQBROWSE               1474
#define IDC_BUGTRAQPROVIDERLABEL        1475
#define IDC_BUGTRAQPROVIDERCOMBO        1476
#define IDC_BUGTRAQPARAMETERSLABEL      1477
#define IDC_SHOWEXTERNALS               1480
#define IDC_FORCE                       1480
#define IDC_UNVERSIONEDITEMS            1481
#define IDC_CHECK_NOFF                  1481
#define IDC_SENDMAIL_COMBINE            1481
#define IDC_PUSHALL                     1481
#define IDC_SIGN_OFF                    1482
#define IDC_SIGNOFF                     1482
#define IDC_CHECK_NOCOMMIT              1482
#define IDC_SENDMAIL_MAPI               1482
#define IDC_BUTTON2                     1483
#define IDC_BUTTON_BROWSE               1483
#define IDC_BUTTON_BROWSE_SOURCE_BRANCH 1483
#define IDC_BUTTON_BROWSE_REF           1483
#define IDC_BUTTON_MANAGE               1483
#define IDC_KEEP_CR                     1483
#define IDC_CLONE_URL                   1484
#define IDC_BUTTON_BROWSE_SOURCE_BRANCH2 1484
#define IDC_BUTTON_BROWSE_DEST_BRANCH   1484
#define IDC_CHECK_FFONLY                1484
#define IDC_TITLE_ANIMATE               1485
#define IDC_CHECK_FETCHTAGS             1485
#define IDC_RUN_PROGRESS                1486
#define IDC_CURRENT                     1487
#define IDC_COMBOBOXEX1                 1489
#define IDC_REMOTE_COMBO                1489
#define IDC_BRANCH_REMOTE               1489
#define IDC_COMBOBOXEX_BRANCH           1489
#define IDC_COMBOBOXEX_FROM             1489
#define IDC_REMOTE_RD                   1490
#define IDC_URL                         1490
#define IDC_COMBOBOXEX_TAGS             1490
#define IDC_COMBOBOXEX_TO               1490
#define IDC_COMBOBOXEX_VERSION          1491
#define IDC_OTHER_RD                    1492
#define IDC_OTHER                       1493
#define IDC_BRANCH_SOURCE               1493
#define IDC_REMOTE_BRANCH               1494
#define IDC_RD_REMOTE                   1494
#define IDC_RD_URL                      1495
#define IDC_COLOR_LINE7                 1495
#define IDC_REMOTE                      1496
#define IDC_PACK                        1497
#define IDC_TAGS                        1499
#define IDS_CHECKOUT_TT_DIR             1500
#define IDC_BRANCH_GROUP                1500
#define IDC_COLOR_LINE8                 1500
#define IDS_CHECKOUT_EXPORTDIR          1501
#define IDC_URL_GROUP                   1501
#define IDC_OPTION_GROUP                1502
#define IDC_STATIC_REMOTE               1503
#define IDC_STATIC_SOURCE               1504
#define IDS_EXPORT_TT_EOL               1505
#define IDC_PUTTYKEY_AUTOLOAD           1505
#define IDS_IMPORT_TT_MODULENAMECHECK   1510
#define IDC_LIST2                       1510
#define IDC_SENDMAIL_SUBJECT            1510
#define IDC_EDIT4                       1510
#define IDC_SMTP_PASSWORD               1510
#define IDC_BUGTRAQ_LABEL               1510
#define IDC_CHECK_SVN_BRANCH            1510
#define IDS_IMPORT_TT_TEMPFILES         1511
#define IDC_RADIO_HEAD                  1511
#define IDC_BUGTRAQ_LOGREGEX            1511
#define IDC_EDIT_SVN_TAG                1511
#define IDC_RADIO_BRANCH                1512
#define IDC_EDIT_SVN_BRANCH             1512
#define IDC_RADIO_TAGS                  1513
#define IDC_CHECK_SVN_TAG               1513
#define IDC_RADIO_VERSION               1514
#define IDC_GROUP_BRANCH                1515
#define IDC_GROUP_OPTION                1517
#define IDC_LABEL_BRANCH                1518
#define IDC_BRANCH_TAG                  1519
#define IDC_CHECK_TRACK                 1520
#define IDC_CHECK_FORCE                 1521
#define IDC_GROUP_BASEON                1522
#define IDC_CHECK_BRANCHOVERRIDE        1523
#define IDC_CHECK_SIGN                  1523
#define IDC_CHECK_SQUASH                1524
#define IDC_CHECK_SWITCH                1525
#define IDC_CHECK_BRANCH                1527
#define IDC_EDIT_BRANCH                 1528
#define IDC_SHOWLOCKEDOVERLAY           1529
#define IDC_RADIO_SINCE                 1532
#define IDC_COMBOBOXEX_SINCE            1533
#define IDC_RADIO_NUM                   1534
#define IDC_RADIO_RANGE                 1535
#define IDC_SPIN_NUM                    1536
#define IDC_COMBOBOXEX_DIR              1537
#define IDC_GROUP_DIR                   1538
#define IDC_GROUP_VERSION               1539
#define IDC_EDIT_NUM                    1540
#define IDC_BUTTON_FROM                 1541
#define IDC_CURRENT_BRANCH              1542
#define IDC_BUTTON_FROM2                1542
#define IDC_BUTTON_REF                  1542
#define IDC_LOCAL_BRANCH                1543
#define IDC_COLOR_LINE5                 1544
#define IDC_COLOR_LINE6                 1545
#define IDC_COLOR_LINE1                 1546
#define IDC_COLOR_LINE2                 1547
#define IDC_COLOR_LINE3                 1548
#define IDC_COLOR_LINE4                 1549
#define IDC_SHOWADDEDOVERLAY            1549
#define IDC_SHOWREADONLYOVERLAY         1550
#define IDC_MSYSGIT_PATH                1550
#define IDS_PROC_RENAME                 1550
#define IDC_RADIO_RESET_SOFT            1550
#define IDC_SHOWDELETEDOVERLAY          1551
#define IDC_MSYSGIT_BROWSE              1551
#define IDS_PROC_NEWNAME                1551
#define IDC_RADIO_RESET_MIXED           1551
#define IDC_MSYSGIT_VER                 1552
#define IDS_PROC_NEWNAMECOPY            1552
#define IDC_RADIO_RESET_HARD            1552
#define IDS_PROC_NEWNAMEMOVE            1553
#define IDC_RESET_BRANCH_NAME           1553
#define IDS_PROC_NEWNAMELABEL           1554
#define IDC_GROUP_RESET_TYPE            1554
#define IDC_COMMIT_AMEND                1555
#define IDC_SOUNDS_TEXT                 1556
#define IDC_COMMIT_AMENDDIFF            1556
#define IDC_REBASE_PROGRESS             1557
#define IDC_COMMIT_SETDATETIME          1557
#define IDC_REBASE_SHEET                1558
#define IDC_EDIT_ALL                    1559
#define IDS_PROC_MULTIRENAME            1560
#define IDC_PICK_ALL                    1560
#define IDC_SQUASH_ALL                  1561
#define IDC_REBASE_SPLIT                1562
#define IDC_STATUS_STATIC               1563
#define IDC_REBASE_CONTINUE             1564
#define IDC_REBASE_ABORT                1565
#define IDC_REBASE_DUMY_TAB             1566
#define IDC_GIT_USERNAME                1566
#define IDC_CHECK_GLOBAL                1567
#define IDC_EDIT_URL                    1568
#define IDC_CHECK_WARN_NO_SIGNED_OFF_BY 1568
#define IDC_EDIT_PUTTY_KEY              1569
#define IDS_PROC_CHECKOUTTO             1570
#define IDC_CHECK_ISAUTOLOADPUTTYKEY    1570
#define IDS_PROC_CHECKOUTTOPONLY        1571
#define IDC_PUTTYKEYFILE                1571
#define IDS_PROC_CHECKOUTNOEXTERNALS    1572
#define IDC_GROUP_CLONE                 1572
#define IDS_PROC_OVERWRITEEXPORT        1573
#define IDC_GROUPT_REMOTE               1573
#define IDS_PROC_OVERWRITEEXPORT_OVERWRITE 1574
#define IDS_PROC_OVERWRITEEXPORT_RENAME 1575
#define IDC_SENDMAIL_PATCHS             1575
#define IDS_PROC_OVERWRITEEXPORT_CANCEL 1576
#define IDS_PROC_EXPORTUNVERSION        1577
#define IDC_SENDMAIL_TO                 1577
#define IDC_COMBOBOXEX_REF              1578
#define IDC_SENDMAIL_CC                 1578
#define IDC_STATIC_REF                  1579
#define IDC_SENDMAIL_ATTACHMENT         1579
#define IDC_REFLOG_LIST                 1580
#define IDC_SENDMAIL_SETUP              1580
#define IDC_COMBOBOXEX_REPOSITORY       1581
#define IDC_COMBOBOXEX_PATH             1582
#define IDC_SENDMAIL_GROUP              1582
#define IDC_REP_BROWSE                  1583
#define IDC_SEND_ADDRESS                1583
#define IDC_BUTTON_PATH_BROWSE          1584
#define IDC_STMP_SERVER                 1584
#define IDC_GROUP_SUBMODULE             1585
#define IDC_SMTP_AUTH                   1585
#define IDC_BRANCH_CHECK                1586
#define IDC_SMTP_USER                   1586
#define IDC_SUBMODULE_BRANCH            1587
#define IDC_CHECK_SENDMAIL              1587
#define IDD_REFLOG                      1588
#define IDC_TREE_REF                    1588
#define IDD_SUBMODULE_ADD               1589
#define IDC_EDIT_NAME                   1589
#define IDC_CHECK_FORSE                 1590
#define IDC_STATIC_BRANCH               1592
#define IDC_BUGTRAQ_WARNINGIFNOISSUE_TRUE 1593
#define IDC_BUGTRAQ_WARNINGIFNOISSUE_FALSE 1594
#define IDC_BUGTRAQ_APPEND_FALSE        1596
#define IDC_BUGTRAQ_NUMBER_TRUE         1597
#define IDC_BUGTRAQ_NUMBER_FALSE        1598
#define IDC_BUGTRAQ_URL                 1599
#define IDS_REPOBROWSE_SAVEAS           1600
#define IDC_BUGTRAQ_MESSAGE             1600
#define IDS_REPOBROWSE_SHOWLOG          1601
#define IDC_BUGTRAQ_APPEND_TRUE         1601
#define IDS_REPOBROWSE_OPEN             1602
#define IDC_CHECK_REBASE                1602
#define IDC_CLONE_GROUP_SVN             1603
#define IDC_CHECK_PRUNE                 1603
#define IDC_CHECK_SVN                   1604
#define IDC_CHECK_SVN_TRUNK             1605
#define IDC_EDIT_SVN_TRUNK              1606
#define IDC_REBASE_CHECK_FORCE          1607
#define IDC_EDIT_DEPTH                  1607
#define IDC_CHECK_SVN_FROM              1608
#define IDC_COMBOBOXEX_URL              1610
#define IDC_BUTTON_PULL                 1611
#define IDC_BUTTON_PUSH                 1612
#define IDC_BUTTON_APPLY                1613
#define IDC_BUTTON_EMAIL                1614
#define IDC_STATIC_LOCAL_BRANCH         1616
#define IDC_STATIC_REMOTE_BRANCH        1617
#define IDC_STATIC_REMOTE_URL           1618
#define IDC_CHECK_PUTTY_KEY             1619
#define IDC_STATIC_STATUS               1621
#define IDC_PROGRESS_SYNC               1622
#define IDC_ANIMATE_SYNC                1623
#define IDC_GROUP_INFO                  1624
#define IDC_BUTTON_COMMIT               1625
#define IDC_CHECK_DIR                   1626
#define IDC_RADIO_CLEAN_ALL             1627
#define IDC_RADIO_CLEAN_NO              1628
#define IDC_RADIO_CLEAN_IGNORE          1629
#define IDC_GROUP_CLEAN_TYPE            1630
#define IDC_CHECK_AUTOCRLF              1631
#define IDC_CHECK_SAFECRLF              1632
#define IDC_CHECK4                      1634
#define IDC_CHECK_AUTORETRY             1634
#define IDC_STATIC_MERGE_MESSAGE        1635
#define IDC_PATCH                       1636
#define IDC_VIEW_PATCH                  1637
#define IDC_BUTTON_SUBMODULE            1639
#define IDC_RADIO_EXCLUDE               1640
#define IDC_RADIO_GITIGNORE             1641
#define IDC_GROUP_TYPE                  1642
#define IDC_REV1EDIT                    1643
#define IDC_REV1GROUP                   1644
#define IDC_REV2GROUP                   1645
#define IDC_CHECK_DEPTH                 1646
#define IDC_EDIT_MESSAGE                1647
#define IDC_GROUP_MESSAGE               1648
#define IDC_STATIC_REMINDER             1649
#define IDC_CHECK_USERNAME              1650
#define IDC_EDIT_USERNAME               1651
#define IDC_MSYSGIT_EXTERN_PATH         1652
#define IDC_CHECK_BARE                  1653
#define IDC_INIT_REPO_DESC              1654
#define IDC_CHECK_RECURSIVE             1654
#define IDC_CHECK_IGNORE_WHITE_SPACE    1655
#define IDC_CHECK_3WAY                  1656
#define IDC_CHECK_IGNORE_SPACE          1657
#define IDC_AM_SPLIT                    1658
#define IDC_AM_DUMY_TAB                 1659
#define IDC_REMEMBER                    1660
#define IDC_HIDEMENUS                   1660
#define IDC_ALTERNATIVEEDITOR_OFF       1661
#define IDC_ALTERNATIVEEDITOR_ON        1662
#define IDC_ALTERNATIVEEDITOR           1663
#define IDC_ALTERNATIVEEDITORBROWSE     1664
#define IDC_NOAUTOSELECTSUBMODULES      1669
#define IDC_COMMIT_DATEPICKER           1670
#define IDC_COMMIT_TIMEPICKER           1671
#define IDC_COMBOBOXEX_GOOD             1671
#define IDC_BUTTON_GOOD                 1672
#define IDC_GROUP_STASHMESSAGE          1673
#define IDC_STASHMESSAGE                1674
#define IDC_FOLLOWRENAMES               1675
#define IDS_ABOUTVERSION                1700
#define IDS_ABOUTVERSIONBOX             1701
#define IDS_DLGTITLE_ADD_DIFF_TOOL      1750
#define IDS_DLGTITLE_ADD_MERGE_TOOL     1751
#define IDS_DLGTITLE_EDIT_DIFF_TOOL     1752
#define IDS_DLGTITLE_EDIT_MERGE_TOOL    1753
#define IDS_DLGTITLE_ADV_DIFF           1754
#define IDS_DLGTITLE_ADV_MERGE          1755
#define IDS_LOG_COPY_SUCCESS            1830
#define IDS_LOG_MESSAGEEDITTITLE        1831
#define IDS_LOG_AUTHOREDITTITLE         1832
#define IDS_LOG_SHOWALL                 1833
#define IDS_LOG_SHOWRANGE               1834
#define IDS_LOG_LOGINFOSTRING           1835
#define IDS_LOG_SHOWNEXT                1836
#define IDS_LOG_SHOW_WHOLE              1838
#define IDS_LOG_FILTER_ALL              1850
#define IDS_LOG_FILTER_PATHS            1851
#define IDS_LOG_FILTER_AUTHORS          1852
#define IDS_LOG_FILTER_MESSAGES         1853
#define IDS_LOG_FILTER_REVS             1854
#define IDS_LOG_FILTER_REGEX            1855
#define IDS_LOG_FILTER_BUGIDS           1856
#define IDS_LOG_FILTER_REGEX_TT         1860
#define IDS_LOG_REVERTTOREV_CONFIRM     1890
#define IDS_LOG_REVERTREV_ERROR         1891
#define IDS_LOG_STOPONCOPY_HINT         1892
#define IDS_LOG_SAVEFOLDERTOHINT        1893
#define IDS_LOG_MERGETO                 1894
#define IDS_LOG_SHOW_CURRENT_BRANCH     1895
#define IDS_LOG_SHOW_CURRENT_PATH       1896
#define IDS_LOG_SHOW_FIRST_PARENT       1897
#define IDS_LOG_SHOW_NO_MERGE           1898
#define IDS_COMMIT_AMEND_TT             1899
#define IDS_PROGRESSGETFILE             1900
#define IDS_PROGRESSREVISION            1901
#define IDS_PROGRESSWAIT                1902
#define IDS_PROGRESS_UNIFIEDDIFF        1903
#define IDS_PROGRESS_COMPARE            1904
#define IDS_PROGRESS_INFO               1905
#define IDS_PROGRESSGETFILEREVISION     1906
#define IDS_PROGRESSIMPORT              1907
#define IDS_PROGRESSREVISIONTEXT        1908
#define IDS_INPUT_ENTERLOG              2000
#define IDS_INPUT_LOGTITLE              2001
#define IDS_INPUT_REMOVELOGMSG          2002
#define IDS_INPUT_ADDLOGMSG             2003
#define IDS_INPUT_COPYLOGMSG            2004
#define IDS_INPUT_MKDIRLOGMSG           2005
#define IDS_INPUT_MOVELOGMSG            2006
#define IDS_INPUT_ADDFOLDERLOGMSG       2007
#define IDS_INPUT_ADDFILEFOLDERMSG      2008
#define IDS_INPUT_RENAMELOGMSG          2009
#define IDS_INPUT_IMPORTFOLDER          2010
#define IDS_INPUT_IMPORTFILE            2011
#define IDS_INPUT_COPY                  2012
#define IDS_INPUT_MKDIR                 2013
#define IDS_INPUT_REMOVEONE             2014
#define IDS_INPUT_REMOVEMORE            2015
#define IDS_INPUT_IMPORTFILEFULL        2016
#define IDS_INPUT_IMPORTFILES           2017
#define IDS_INPUT_RENAME                2018
#define IDS_INPUT_MOVE                  2019
#define IDS_INPUT_COPYMORE              2020
#define IDS_INPUT_MOVEMORE              2021
#define IDS_INPUT_EDITPROP              2022
#define IDS_INPUT_REMOVEPROP            2023
#define IDS_INPUT_SETPROP               2024
#define IDS_BLAME_PROGRESSTITLE         2100
#define IDS_BLAME_PROGRESSINFO          2101
#define IDS_BLAME_PROGRESSCANCEL        2102
#define IDS_BLAME_PROGRESSINFO2         2103
#define IDS_BLAME_PROGRESSINFOSTART     2104
#define IDS_BLAME_PROGRESSLOGSTART      2105
#define IDS_MENUREFRESH                 2150
#define IDC_GROUP_DCOMMIT_TYPE          2151
#define IDC_RADIO_SVN_COMMIT            2152
#define IDC_RADIO_GIT_COMMIT            2153
#define IDS_LOG_COMPAREWITHBASE         2200
#define IDS_PROC_ENTERURLLABEL          2300
#define IDS_PROC_PATCHTITLE             2301
#define IDS_PROC_SAVEPATCHTO            2302
#define IDS_PROC_REPOCREATESHAREWARN    2303
#define IDS_PROC_CLEANUP                2304
#define IDS_PROC_REMOVEFORCE            2305
#define IDS_PROC_YESTOALL               2306
#define IDS_PROC_IGNORESUCCESS          2307
#define IDS_PROC_RESOLVE                2308
#define IDS_PROC_RTFM                   2309
#define IDS_PROC_CASERENAME             2310
#define IDS_PROC_UnIGNORESUCCESS        2311
#define IDS_PROC_UNIGNORESUCCESS        2311
#define IDS_PROC_FORCEMOVE              2312
#define IDS_PROC_OMMITEXTERNALS         2313
#define IDS_PROC_ICONCACHEREBUILT       2314
#define IDS_PROC_ICONCACHENOTREBUILT    2315
#define IDS_PROC_EXPORTFOLDERNAME       2316
#define IDS_PROC_EXPORTFOLDERNAME2      2317
#define IDS_PROC_REMOVEFORCEFOLDER      2318
#define IDS_PROC_DIFFTITLE              2330
#define IDS_PROC_DIFFLABEL              2331
#define IDS_PROC_CLEANUP_INFO1          2332
#define IDS_PROC_CLEANUP_INFO2          2333
#define IDS_PROC_UNVERSION              2334
#define IDS_PROC_COPYRENAME             2335
#define IDS_PROC_MOVERENAME             2336
#define IDS_DIFF_WCNAME                 2400
#define IDS_DIFF_BASENAME               2401
#define IDS_DIFF_WORKINGCOPY            2402
#define IDS_DIFF_REVISIONPATCHED        2403
#define IDS_DIFF_REMOTENAME             2404
#define IDS_DIFF_WORKINGBASE            2405
#define IDS_DIFF_PROP_WCNAME            2406
#define IDS_DIFF_PROP_BASENAME          2407
#define IDS_DIFF_PROP_REMOTENAME        2408
#define IDS_DIFF_PROP_REVISIONNAME      2409
#define IDS_DIFF_BASENAMEREV            2410
#define IDS_DIFF_PROP_BASENAMEREV       2411
#define IDS_COMMONFILEFILTER            2500
#define IDS_PROGRAMSFILEFILTER          2501
#define IDS_CERTIFICATESFILEFILTER      2502
#define IDS_PATCHFILEFILTER             2503
#define IDS_PICTUREFILEFILTER           2504
#define IDS_PROPSFILEFILTER             2505
#define IDS_CHECKUPDATE_SUMMARY         2600
#define IDS_COMMITDLG_EXTERNALS         2700
#define IDS_COMMITDLG_STATISTICSFORMAT  2701
#define IDS_COMMITDLG_ONLYNUMBERS       2702
#define IDS_COMMITDLG_NOISSUEWARNING    2703
#define IDS_COMMITDLG_NOTHINGTOCOMMITUNVERSIONED 2704
#define IDS_COMMITDLG_HISTORY_TT        2705
#define IDS_COMMITDLG_HISTORYHINT_TT    2706
#define IDS_COMMITDLG_UNVERSIONEDFOLDERWARNING 2707
#define IDS_COMMITDLG_NOMESSAGE         2708
#define IDS_COMMITDLG_POPUP_PASTEFILELIST 2750
#define IDS_COMMITDLG_POPUP_PASTELASTMESSAGE 2751
#define IDC_NOCONTEXTPATHS              2752
#define IDS_SETTINGS_EXTMENULAYOUT_TT   2753
#define IDS_SETTINGS_CHECKNEWER_TT      3100
#define IDS_SETTINGS_ONLYEXPLORER_TT    3101
#define IDS_SETTINGS_MENULAYOUT_TT      3102
#define IDS_SETTINGS_EXCLUDELIST_TT     3103
#define IDS_SETTINGS_INCLUDELIST_TT     3104
#define IDS_SETTINGS_CLEARAUTH_TT       3105
#define IDS_SETTINGS_COMMITFILETIMES_TT 3106
#define IDS_SETTINGS_ICONSETCHANGED     3108
#define IDS_SETTINGS_PROXYEXCEPTIONS_TT 3109
#define IDS_SETTINGS_READONLYNAME       3110
#define IDS_SETTINGS_LOCKEDNAME         3111
#define IDS_SETTINGS_OLDLOGAPIS_TT      3112
#define IDS_SETTINGS_AUTOCOMPLETION_TT  3114
#define IDS_SETTINGS_AUTOCOMPLETIONTIMEOUT_TT 3115
#define IDS_SETTINGS_RECURSIVE_TT       3116
#define IDS_SETTINGS_USEWCURL_TT        3117
#define IDS_SETTINGS_SPELLCHECKER_TT    3118
#define IDS_SETTINGS_REPOCHECK_TT       3119
#define IDS_SETTINGS_UNVERSIONEDRECURSE_TT 3121
#define IDS_SETTINGS_MAXHISTORY_TT      3122
#define IDS_SETTINGS_CACHEDEFAULT_TT    3123
#define IDS_SETTINGS_CACHESHELL_TT      3124
#define IDS_SETTINGS_CACHENONE_TT       3125
#define IDS_SETTINGS_SAVEDDATA_LOGHIST_TT 3126
#define IDS_SETTINGS_SAVEDDATA_URLHIST_TT 3127
#define IDS_SETTINGS_SAVEDDATA_RESIZABLE_TT 3128
#define IDS_SETTINGS_SAVEDDATA_AUTH_TT  3129
#define IDS_SETTINGS_DOTNETHACK_TT      3130
#define IDS_SETTINGS_RESTARTSYSTEM      3131
#define IDS_SETTINGS_ASPHACKWARNING     3132
#define IDS_SETTINGS_UNVERSIONEDASMODIFIED_TT 3133
#define IDS_SETTINGS_COMMITREOPEN_TT    3134
#define IDS_SETTINGS_CHECKOUTPATH_TT    3135
#define IDS_SETTINGS_CHECKOUTURL_TT     3136
#define IDS_SETTINGS_SORTNUMERICAL_TT   3137
#define IDS_SETTINGS_SHOWEXCLUDEDASNORMAL_TT 3138
#define IDS_SETTINGS_SAVEDDATA_REPOLOGHIST_TT 3139
#define IDS_SETTINGS_SELECTFILESONCOMMIT_TT 3141
#define IDS_SETTINGS_DIFFBYDOUBLECLICK_TT 3142
#define IDS_SETTINGS_USESYSTEMLOCALEFORDATES_TT 3143
#define IDS_SETTINGS_USERECYCLEBIN_TT   3144
#define IDS_SETTINGS_EXCLUDECONTEXTLIST_TT 3145
#define IDS_SETTINGS_CACHESHELLEXT_TT   3146
#define IDS_SETTINGS_HOOKS_SELECTFOLDERPATH 3150
#define IDS_SETTINGS_HOOKS_SELECTSCRIPTFILE 3151
#define IDS_SETTINGS_HOOKS_TYPECOL      3152
#define IDS_SETTINGS_HOOKS_PATHCOL      3153
#define IDS_SETTINGS_HOOKS_COMMANDLINECOL 3154
#define IDS_SETTINGS_HOOKS_WAITCOL      3155
#define IDS_SETTINGS_HOOKS_SHOWCOL      3156
#define IDS_SETTINGS_SHOWACTIONLOG_TT   3158
#define IDS_SETTINGS_CLEARACTIONLOG_TT  3159
#define IDS_SETTINGS_MAXACTIONLOGLINES_TT 3160
#define IDS_SETTINGS_HIDEMENUS_TT       3161
#define IDS_SETTINGS_REPOSITORY_URL     3170
#define IDS_SETTINGS_REPOSITORY_SIZE    3171
#define IDS_SETTINGS_CONNECTIVITY_ASKUSER 3172
#define IDS_SETTINGS_CONNECTIVITY_OFFLINENOW 3173
#define IDS_SETTINGS_CONNECTIVITY_OFFLINEFOREVER 3174
#define IDS_SETTINGS_MULTIPLEURLSFORUUID 3178
#define IDS_CHECKNEWER_YOURVERSION      3200
#define IDS_CHECKNEWER_CURRENTVERSION   3201
#define IDS_CHECKNEWER_YOURUPTODATE     3202
#define IDS_CHECKNEWER_NEWERVERSIONAVAILABLE 3203
#define IDS_CHECKNEWER_NETERROR         3204
#define IDS_STATUSLIST_COLFILE          3300
#define IDS_STATUSLIST_COLSTATUS        3301
#define IDS_STATUSLIST_COLREMOTESTATUS  3302
#define IDS_STATUSLIST_COLTEXTSTATUS    3303
#define IDS_STATUSLIST_COLPROPSTATUS    3304
#define IDS_STATUSLIST_COLREMOTETEXTSTATUS 3305
#define IDS_STATUSLIST_COLREMOTEPROPSTATUS 3306
#define IDS_STATUSLIST_COLURL           3307
#define IDS_STATUSLIST_COLEXT           3308
#define IDS_STATUSLIST_COLAUTHOR        3311
#define IDS_STATUSLIST_COLDATE          3312
#define IDS_STATUSLIST_COLREVISION      3313
#define IDS_STATUSLIST_COLCOPYFROM      3315
#define IDS_STATUSLIST_COLMODIFICATIONDATE 3316
#define IDS_STATUSLIST_COLFILENAME      3317
#define IDS_STATUSLIST_COLREMOTEREVISION 3318
#define IDS_STATUSLIST_MULTIPLETARGETS  3320
#define IDS_STATUSLIST_PROPONLY         3321
#define IDS_STATUSLIST_COPYFROM         3322
#define IDS_STATUSLIST_SWITCHEDTO       3323
#define IDS_STATUSLIST_CONTEXT_ADD      3330
#define IDS_STATUSLIST_CONTEXT_EXPLORE  3331
#define IDS_STATUSLIST_CONTEXT_RESOLVED 3332
#define IDS_STATUSLIST_CONTEXT_COMMIT   3333
#define IDS_STATUSLIST_CONTEXT_PROPERTIES 3334
#define IDS_STATUSLIST_CONTEXT_COPY     3335
#define IDS_STATUSLIST_CONTEXT_COPYEXT  3336
#define IDS_STATUSLIST_CONTEXT_REPAIRMOVE 3337
#define IDS_STATUSLIST_CONTEXT_REMOVEFROMCS 3338
#define IDS_STATUSLIST_CONTEXT_CREATECS 3339
#define IDS_STATUSLIST_CONTEXT_ADDTOCS  3340
#define IDS_STATUSLIST_CONTEXT_MOVETOCS 3340
#define IDS_STATUSLIST_CONTEXT_ADD_RECURSIVE 3341
#define IDS_STATUSLIST_NESTED           3402
#define IDS_STATUSLIST_BUSYMSG          3403
#define IDS_STATUSLIST_EMPTYMSG         3404
#define IDS_STATUSLIST_UNASSIGNED_CHANGESET 3405
#define IDS_STATUSLIST_CHECKGROUP       3406
#define IDS_STATUSLIST_UNCHECKGROUP     3407
#define IDS_STATUSLIST_KEEPLOCAL        3409
#define IDS_STATUSLIST_NOPROPVALUE      3412
#define IDS_PROGRS_CONFLICTSOCCURED_WARNING 3500
#define IDS_PROGRS_CONFLICTSOCCURED     3501
#define IDS_PROGRS_DRYRUN               3502
#define IDS_PROGRS_FINISHED             3503
#define IDS_PROGRS_TITLEFAILED          3504
#define IDS_PROGRS_INFOFAILED           3505
#define IDS_PROGRS_CMDINFO              3506
#define IDS_PROGRS_IGNOREANCESTRY       3507
#define IDS_PROGRS_RESPECTANCESTRY      3508
#define IDS_PROGRS_INFOGETTINGINFO      3511
#define IDS_PROGRS_TITLE_RENAME         3530
#define IDS_PROGRS_TITLE_MERGEREINTEGRATE 3533
#define IDS_PROGRS_CLOSE_MANUAL         3540
#define IDS_PROGRS_CLOSE_NOERROR        3541
#define IDS_PROGRS_CLOSE_NOCONFLICTS    3542
#define IDS_PROGRS_CLOSE_NOMERGES       3543
#define IDS_PROGRS_CLOSE_LOCAL          3544
#define IDS_PROGRS_NONRECURSIVEHINT     3580
#define IDS_PROGRS_PATHATREV            3600
#define IDS_PROGRS_TIME                 3602
#define IDS_PROGRS_FINALINFO            3603
#define IDS_PROGRS_EXTERNALSEXCLUDED    3604
#define IDS_PROGRS_EXTERNALSINCLUDED    3605
#define IDS_PROGRS_IGNOREDINCLUDED      3606
#define IDS_PROGRS_CMD_CHECKOUT         3650
#define IDS_PROGRS_CMD_IMPORT           3651
#define IDS_PROGRS_CMD_SWITCH           3652
#define IDS_PROGRS_CMD_MERGEPEG         3653
#define IDS_PROGRS_CMD_MERGEURL         3654
#define IDS_PROGRS_CMD_COPY             3655
#define IDS_PROGRS_CMD_ADD              3657
#define IDS_PROGRS_CMD_COMMIT           3658
#define IDS_PROGRS_CMD_EXPORT           3659
#define IDS_PROGRS_CMD_RENAME           3661
#define IDS_PROGRS_CMD_RESOLVE          3662
#define IDS_PROGRS_CMD_REVERT           3663
#define IDS_PROGRS_CMD_MERGEREINTEGRATE 3666
#define IDS_SSL_SAVE_CERTPATH           3700
#define IDS_REPOSTATUS_HEADREV          3800
#define IDS_REPOSTATUS_WCINFO           3801
#define IDS_REPOSTATUS_EMPTYFILELIST    3810
#define IDS_STATGRAPH_COMMITSBYAUTHOR   3900
#define IDS_STATGRAPH_COMMITSBYDATE     3901
#define IDS_STATGRAPH_COMMITSBYDATEY    3903
#define IDS_STATGRAPH_COMMITSBYAUTHORX  3904
#define IDS_STATGRAPH_COMMITSBYAUTHORY  3905
#define IDS_STATGRAPH_STATS             3906
#define IDS_STATGRAPH_OTHERGROUP        3907
#define IDS_STATGRAPH_EMPTYAUTHOR       3908
#define IDS_STATGRAPH_COMMITSBYDATEXWEEK 3909
#define IDS_STATGRAPH_COMMITSBYDATEXMONTH 3910
#define IDS_STATGRAPH_COMMITSBYDATEXQUARTER 3911
#define IDS_STATGRAPH_COMMITSBYDATEXYEAR 3912
#define IDS_STATGRAPH_QUARTERLABEL      3920
#define IDS_STATGRAPH_PIEBUTTON_TT      3930
#define IDS_STATGRAPH_LINESTACKEDBUTTON_TT 3931
#define IDS_STATGRAPH_LINEBUTTON_TT     3932
#define IDS_STATGRAPH_BARSTACKEDBUTTON_TT 3933
#define IDS_STATGRAPH_BARBUTTON_TT      3934
#define IDS_STATGRAPH_AUTHORSLIDER_TT   3935
#define IDC_LOG_ALLBRANCH               3936
#define IDS_LOG_ALLBRANCH_TT            3937
#define IDS_SVNERR_CHECKPATHORURL       4000
#define IDS_SVNERR_RUNCLEANUP           4001
#define IDS_SVNERR_CLEANUPORFRESHCHECKOUT 4003
#define IDS_CLIPBOARD_PROGRESS_DEST     4100
#define IDS_SVNACTION_SKIPMISSING       4200
#define IDS_SVNACTION_ADDING            4201
#define IDS_SVNACTION_DELETING          4202
#define IDS_SVNACTION_MERGED            4203
#define IDS_SVNACTION_CONFLICTED        4204
#define IDS_SVNACTION_EXISTS            4209
#define IDS_SVNACTION_CHANGELISTSET     4210
#define IDS_SVNACTION_CHANGELISTCLEAR   4211
#define IDS_SVNACTION_CHANGELISTFAILED  4212
#define IDS_SVNACTION_MERGEBEGINMULTIPLE 4213
#define IDS_SVNACTION_MERGEBEGINSINGLE  4214
#define IDS_SVNACTION_CHANGELISTMOVED   4215
#define IDS_SVNACTION_MERGEBEGINNONE    4216
#define IDS_SVNACTION_MERGEBEGINSINGLEREVERSE 4217
#define IDS_SVNACTION_MERGEBEGINMULTIPLEREVERSE 4218
#define IDS_SVN_SUMMARIZENORMAL         4220
#define IDS_SVN_SUMMARIZEADDED          4221
#define IDS_SVN_SUMMARIZEMODIFIED       4222
#define IDS_SVN_SUMMARIZEDELETED        4223
#define IDS_REVGRAPH_SAVEPIC            4351
#define IDS_REVGRAPH_ERR_GDIINIT        4360
#define IDS_REVGRAPH_ERR_NOBITMAP       4361
#define IDS_REVGRAPH_ERR_NOENCODER      4362
#define IDS_MERGE_SELECTRANGE           4400
#define IDS_MERGE_SELECTENDREVISION     4401
#define IDS_MERGE_SELECTSTARTREVISION   4402
#define IDS_MERGE_RECORDONLY            4403
#define IDS_MERGE_MERGE                 4404
#define IDS_SVNPROGRESS_MENUUSETHEIRS   4500
#define IDS_SVNPROGRESS_MENUUSEMINE     4501
#define IDS_SVNPROGRESS_MENUOPENPARENT  4502
#define IDS_SVNPROGRESS_MENUMARKASRESOLVED 4503
#define IDS_SVNPROGRESS_RESOLVED        4510
#define IDS_SVNPROGRESS_EXPORTING       4530
#define IDS_SVNPROGRESS_EXPORTINGTO     4531
#define IDS_SVNPROGRESS_EXPORTINGWAIT   4532
#define IDS_SVNPROGRESS_MERGELOGMSGONE  4560
#define IDS_SVNPROGRESS_MERGELOGRANGE   4560
#define IDS_SVNPROGRESS_MERGELOGMSGMULTIPLE 4561
#define IDS_SVNPROGRESS_MERGELOGMSG     4562
#define IDS_SVNPROGRESS_UNVERSION       4563
#define IDC_REBASE_COMBOXEX_UPSTREAM    4564
#define IDC_REBASE_COMBOXEX_BRANCH      4565
#define IDC_REBASE_STATIC_BRANCH        4566
#define IDC_REBASE_STATIC_UPSTREAM      4567
#define IDD_RESOLVE_CONFLICT            4568
#define IDC_MODIFY                      4569
#define IDD_SETTINGIT_CONFIG            4569
#define IDC_DEL_GROUP                   4570
#define IDD_SETTINREMOTE                4570
#define IDC_DELETE                      4571
#define IDD_SETTINGEMAIL                4571
#define IDD_SETTIN                      4571
#define IDD_SETTINGSBUGTRAQ_CONFIG      4571
#define IDC_LOCAL_STATUS                4572
#define IDD_CLEAN                       4572
#define IDC_REMOTE_STATUS               4573
#define IDD_SETTINGSEXTMENU             4573
#define IDD_BISECTSTART                 4574
#define IDD_STASH                       4575
#define IDC_COMBOBOXEX_LOCAL_BRANCH     5000
#define IDC_COMBOBOXEX_REMOTE_BRANCH    5001
#define IDC_COMBOBOXEX_BAD              5001
#define IDS_FILEDIFF_FILE               5100
#define IDS_FILEDIFF_COMMENT            5101
#define IDS_FILEDIFF_ACTION             5101
#define IDS_FILEDIFF_COMMENTCOPY        5102
#define IDS_FILEDIFF_WAIT               5102
#define IDS_FILEDIFF_COMMENTRENAMED     5103
#define IDS_FILEDIFF_FILTERCUE          5120
#define IDS_FILEDIFF_POPBLAME           5150
#define IDS_FILEDIFF_POPSAVELIST        5151
#define IDS_FILEDIFF_POPEXPORT          5152
#define IDS_FILEDIFF_POPCLIPBOARD       5153
#define IDS_FILEDIFF_CHANGEDLISTINTRO   5170
#define IDS_FILEDIFF_SWITCHLEFTRIGHT_TT 5190
#define IDS_SVNDIFF_ONEURL              5200
#define IDS_SVNDIFF_TWOURLS             5201
#define IDS_PROPPAGE_BACK               5300
#define IDS_PROPPAGE_NEXT               5301
#define IDS_PROPPAGE_CANCEL             5302
#define IDS_PROPPAGE_HELP               5303
#define IDS_SETTINGS_TRUNKPATTERN       5520
#define IDS_SETTINGS_BRANCHESPATTERN    5521
#define IDS_SETTINGS_TAGSPATTERN        5522
#define IDS_SETTINGS_TWEAKTRUNKCOLORS   5523
#define IDS_SETTINGS_TWEAKTAGSCOLORS    5524
#define IDS_SVN_PROGRESS_SPEED          5700
#define IDS_SVN_PROGRESS_TOTALTRANSFERRED 5701
#define IDS_SVN_PROGRESS_TOTALMBTRANSFERRED 5702
#define IDS_SVN_PROGRESS_TOTALANDSPEED  5703
#define IDS_SVN_PROGRESS_TOTALBYTESTRANSFERRED 5704
#define IDS_SVN_PROGRESS_BYTES_SEC      5705
#define IDS_SVN_PROGRESS_KBYTES_SEC     5706
#define IDS_COLOURPICKER_CUSTOMTEXT     7000
#define IDS_COLOURPICKER_DEFAULTTEXT    7001
#define IDS_COPYDLG_FROMURL             8000
#define IDS_EDITPROPS_NUMPATHS          9000
#define IDS_EDITPROPS_DIFFERENTPROPVALUES 9001
#define IDS_EDITPROPS_RECURSIVEREMOVEQUESTION 9002
#define IDS_EDITPROPS_RECURSIVE         9003
#define IDS_EDITPROPS_NOTRECURSIVE      9004
#define IDS_EDITPROPS_CANCEL            9005
#define IDS_EDITPROPS_ADDBUTTON         9006
#define IDS_EDITPROPS_EDITBUTTON        9007
#define IDS_EDITPROPS_ADDTITLE          9007
#define IDS_EDITPROPS_EDITTITLE         9008
#define IDS_EDITPROPS_BINVALUE          9020
#define IDS_EDITPROPS_ERRIMPORTFORMAT   9030
#define IDS_ERR_NOTFOUND_SUPER_PRJECT   9031
#define IDS_HOOKTYPE_STARTCOMMIT        9100
#define IDS_HOOKTYPE_PRECOMMIT          9101
#define IDS_HOOKTYPE_POSTCOMMIT         9102
#define IDS_HOOKTYPE_STARTUPDATE        9103
#define IDS_HOOKTYPE_PREUPDATE          9104
#define IDS_HOOKTYPE_POSTUPDATE         9105
#define IDS_PROP_TT_IGNORE              9200
#define IDS_PROP_TT_KEYWORDS            9201
#define IDS_PROP_TT_EXECUTABLE          9202
#define IDS_PROP_TT_EOLSTYLE            9203
#define IDS_PROP_TT_MIMETYPE            9204
#define IDS_PROP_TT_EXTERNALS           9205
#define IDS_PROP_TT_MERGEINFO           9207
#define IDS_PROP_TT_BQLABEL             9220
#define IDS_PROP_TT_BQMESSAGE           9221
#define IDS_PROP_TT_BQNUMBER            9222
#define IDS_PROP_TT_BQURL               9223
#define IDS_PROP_TT_BQWARNNOISSUE       9224
#define IDS_PROP_TT_BQAPPEND            9225
#define IDS_PROP_TT_BQLOGREGEX          9226
#define IDS_PROP_TT_TSVNLOGTEMPLATE     9240
#define IDS_PROP_TT_TSVNLOGWIDTHMARKER  9241
#define IDS_PROP_TT_TSVNLOGMINSIZE      9242
#define IDS_PROP_TT_TSVNLOGFILELISTENGLISH 9243
#define IDS_PROP_TT_TSVNAUTOPROPS       9245
#define IDS_PROP_TT_TSVNPROJECTLANGUAGE 9246
#define IDS_PROP_TT_TSVNLOGSUMMARY      9247
#define IDS_PROP_TT_TSVNUSERFILEPROPERTIES 9248
#define IDS_PROP_TT_TSVNUSERFOLDERPROPERTIES 9249
#define IDS_PROP_TT_WEBVIEWERREVISION   9260
#define IDS_PROP_TT_WEBVIEWERPATHREVISION 9261
#define IDS_PROP_TT_USERFILEPROPERTIES  9280
#define IDS_PROP_TT_USERFOLDERPROPERTIES 9281
#define IDS_TT_RECURSIVE                9290
#define IDS_PROP_TT_RECURSIVE           9290
#define IDS_PROP_TT_IMPORT              9291
#define IDS_PROP_TT_EXPORT              9292
#define IDS_PROP_TT_SAVE                9293
#define IDS_PROP_TT_REMOVE              9294
#define IDS_PROP_TT_EDIT                9295
#define IDS_PROP_TT_ADD                 9296
#define IDS_EDITCONFLICT_ACTIONINFO_ADD 9300
#define IDS_EDITCONFLICT_ACTIONINFO_MODIFY 9301
#define IDS_EDITCONFLICT_ACTIONINFO_DELETE 9302
#define IDS_EDITCONFLICT_PROP_ACTIONINFO_ADD 9303
#define IDS_EDITCONFLICT_PROP_ACTIONINFO_MODIFY 9304
#define IDS_EDITCONFLICT_ACTIONINFO_DELETE2 9305
#define IDS_EDITCONFLICT_PROP_ACTIONINFO_DELETE 9305
#define IDS_EDITCONFLICT_REASONINFO_EDITED 9320
#define IDS_EDITCONFLICT_REASONINFO_OBSTRUCTED 9321
#define IDS_EDITCONFLICT_REASONINFO_DELETED 9322
#define IDS_EDITCONFLICT_REASONINFO_MISSING 9323
#define IDS_EDITCONFLICT_REASONINFO_UNVERSIONED 9324
#define IDS_CONNECTIONSTATE_ONLINE      9600
#define IDS_CONNECTIONSTATE_TEMPOFFLINE 9601
#define IDS_CONNECTIONSTATE_OFFLINE     9602
#define IDS_STATUSLIST_COLADD           9603
#define IDS_STATUSLIST_COLDEL           9604
#define IDS_YEAR_AGO                    9605
#define IDS_YEARS_AGO                   9606
#define IDS_MONTH_AGO                   9607
#define IDS_MONTHS_AGO                  9608
#define IDS_WEEK_AGO                    9609
#define IDS_WEEKS_AGO                   9610
#define IDS_DAY_AGO                     9611
#define IDS_DAYS_AGO                    9612
#define IDS_HOUR_AGO                    9613
#define IDS_HOURS_AGO                   9614
#define IDS_MINUTE_AGO                  9615
#define IDS_MINUTES_AGO                 9616
#define IDS_SECOND_AGO                  9617
#define IDS_SECONDS_AGO                 9618
#define IDS_B_T_NOTEMPTY                9619
#define IDS_TORTOISEGIT                 9620
#define IDS_CHOOSE_REPOSITORY           9621
#define IDS_ERR_NOT_REPOSITORY          9622
#define IDS_ERR_ADDRESS_NO_EMPTY        9623
#define IDS_SVNACTION_SENDMAIL_START    9624
#define IDS_PROGRS_TITLE_SENDMAIL       9625
#define IDS_PROGRS_CMD_SENDMAIL         9626
#define IDS_SVNACTION_SENDMAIL_ERROR    9627
#define IDS_SVNACTION_SENDMAIL_DONE     9628
#define IDS_SVNACTION_SENDMAIL_RETRY    9629
#define IDS_ERR_PAGEANT                 9632
#define IDS_MENU_VIEWPATCH              9633
#define IDS_MENU_VIEWWITHMERGE          9634
#define IDS_MENU_APPLY                  9635
#define IDS_MENU_SENDMAIL               9636
#define IDS_ERR_PROC                    9637
#define IDS_ERROR_NOREF                 9638
#define IDS_ERROR_INDEX                 9639
#define IDS_ERROR_HEAD                  9640
#define IDS_ERROR_NOCLEAN_STASH         9641
#define IDS_ERROR_NOTHING_COMMIT        9642
#define IDS_COMMIT_FINISH               9643
#define IDS_COMMITDLG_POPUP_LOGHISTORY  9644
#define IDS_REBASE_UPTODATE_FMT         9645
#define IDS_REBASE_FORCE_TT             9646
#define IDS_REBASE_ABORT_TT             9647
#define IDS_ERROR_CANNON_FIND_TORTOISEPROC 9648
#define IDS_REBASE_FASTFORWARD_FMT      9649
#define IDS_REBASE_EQUAL_FMT            9650
#define IDS_CLONE_DEPTH_TT              9651
#define IDS_HOOKTYPE_PREPUSH            9652
#define IDS_HOOKTYPE_POSTPUSH           9653
#define IDS_STASH_POP                   9654
#define IDS_DCOMMIT_STASH_POP           9654
#define IDS_HASH                        9655
#define IDS_REF                         9656
#define IDS_ACTION                      9657
#define IDS_MESSAGE                     9658
#define IDS_TREE_DIFF                   9659
#define IDS_AM_3WAY_TT                  9660
#define IDS_AM_IGNORE_SPACE             9661
#define IDS_AM_IGNORE_SPACE_TT          9661
#define IDS_STATGRAPH_NUMBEROFUNIT      9662
#define IDS_STATGRAPH_COMMITSBYUNIT     9663
#define IDS_STATGRAPH_FILECHANGESBYUNIT 9664
#define IDS_STATGRAPH_PERCENTAGE_OF_AUTHORSHIP 9665
#define IDS_STATGRAPH_PERCENTAGE_OF_AUTHORSHIPY 9666
#define IDS_STATGRAPH_COMMITSBYDATEXDAY 9667
#define ID_VIEW_ZOOMIN                  32772
#define ID_VIEW_ZOOMOUT                 32773
#define ID_VIEW_SHOWALLREVISIONS        32796
#define ID_VIEW_GROUPBRANCHES           32799
#define ID_VIEW_ZOOM100                 32803
#define ID_VIEW_ZOOMALL                 32804
#define ID_FILE_SAVEGRAPHAS32805        32805
#define ID_FILE_SAVESTATGRAPHAS         32806
#define ID_FILTER_EXCLUDEPATHS          32807
#define ID_FILTER_EXCLUDEREVISIONS      32808
#define ID_VIEW_SHOWOVERVIEW            32813
#define ID_VIEW_TOPDOWN                 32814
#define ID_URL_FOCUS                    32814
#define ID_VIEW_SHOWHEAD                32815
#define ID_VIEW_EXACTCOPYSOURCE         32816
#define ID_VIEW_FOLDTAGS                32818
#define ID_VIEW_REDUCECROSSLINES        32819
#define ID_VIEW_REMOVEDELETEDONES       32820
#define ID_LOGDLG_REFRESH               32821
#define ID_LOGDLG_FIND                  32822
#define ID_LOGDLG_FOCUSFILTER           32825
#define ID_VIEW_SHOWWCREV               32826
#define ID_FOCUS_MESSAGE                32837

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        339
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1676
#define _APS_NEXT_SYMED_VALUE           201
#endif
#endif
