//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\TortoiseGit\src\Resources\TortoiseProcENG.rc
//
#define IDR_MAINFRAME                   1
#define IDD_SETTINGSPROXY               102
#define IDD_SETTINGSHOOKS               103
#define IDD_SETTINGSOVERLAY             106
#define IDD_SETTINGSSAVEDDATA           108
#define IDR_ACC_PATCHVIEW               109
#define IDD_ABOUT                       129
#define IDD_LOGMESSAGE                  130
#define IDD_PROMPT                      131
#define IDD_SVNPROGRESS                 134
#define IDD_COMMITDLG                   135
#define IDD_SETTINGSMAIN                143
#define IDD_FINDBAR                     144
#define IDD_RENAME                      151
#define IDD_REPOSITORY_BROWSER          153
#define IDD_ADD                         155
#define IDD_CHANGEDFILES                158
#define IDD_SIMPLEPROMPT                160
#define IDD_INPUTDLG                    161
#define IDI_DRIVES                      164
#define IDD_URL                         164
#define IDI_PROXY                       166
#define IDI_MISC                        167
#define IDB_LOGOFLIPPED                 168
#define IDD_SETTINGSPROGSADV            170
#define IDD_TOOLASSOC                   171
#define IDD_CHECKFORUPDATES             174
#define IDD_REVERT                      175
#define IDD_STATGRAPH                   179
#define IDD_SETOVERLAYICONS             184
#define IDI_SET_OVERLAYS                190
#define IDD_SETTINGSPROGSDIFF           192
#define IDD_SETTINGSPROGSMERGE          193
#define IDD_SETTINGSLOOKANDFEEL         195
#define IDI_GENERAL                     195
#define IDD_SETTINGSDIALOGS             196
#define IDI_LOOKANDFEEL                 196
#define IDI_ICONSET                     197
#define IDD_SETTINGSDIALOGS2            197
#define IDI_DIALOGS                     198
#define IDD_DIFFFILES                   199
#define IDD_RESOLVE                     207
#define IDD_HISTORYDLG                  211
#define IDD_SETTINGSCOLORS_2            212
#define IDI_ACTIONADDED                 213
#define IDI_ACTIONDELETED               214
#define IDI_ACTIONMODIFIED              215
#define IDI_ACTIONREPLACED              216
#define IDI_ACTIONCONFLICTED            217
#define IDI_SAVEDDATA                   225
#define IDI_GRAPHBAR                    229
#define IDI_GRAPHBARSTACKED             230
#define IDI_GRAPHLINE                   231
#define IDI_GRAPHLINESTACKED            232
#define IDI_GRAPHPIE                    233
#define IDI_SWITCHLEFTRIGHT             234
#define IDR_STATGRAPH                   235
#define IDD_SETTINGSHOOKCONFIG          236
#define IDI_HOOK                        237
#define IDD_EXPORT                      238
#define IDD_CREATECHANGELIST            243
#define IDI_REPOBROWSER_BKG             244
#define IDD_SETTINGSTBLAME              244
#define IDC_PANCUR                      250
#define IDC_PANCURDOWN                  251
#define IDC_RENINFOLABEL                252
#define IDI_TORTOISEBLAME               252
#define IDR_ACC_LOGDLG                  254
#define IDI_ADD_BKG                     255
#define IDI_RESOLVE_BKG                 256
#define IDI_REVERT_BKG                  257
#define IDI_COMMIT_BKG                  258
#define IDI_CFM_BKG                     260
#define IDR_DOWNLOAD                    263
#define IDI_CANCELNORMAL                264
#define IDI_CANCELPRESSED               265
#define IDI_LOGFILTER                   266
#define IDI_FILTEREDIT                  267
#define IDI_SWITCH_BKG                  275
#define IDD_FIRSTSTARTWIZARD_START      276
#define IDD_SETTINGSBUGTRAQ             283
#define IDI_BUGTRAQ                     284
#define IDD_SETTINGSBUGTRAQADV          284
#define IDI_REFRESH                     290
#define IDI_SAVE                        291
#define IDI_SAVEAS                      292
#define IDI_EXPLORER                    293
#define IDI_OPEN                        294
#define IDI_UPDATE_BKG                  295
#define IDD_CLONE                       297
#define IDD_GITPROGRESS                 300
#define IDD_PULLFETCH                   302
#define IDD_PUSH                        303
#define IDD_GITSWITCH                   304
#define IDD_AUTOTEXTTESTDLG             306
#define IDD_NEW_BRANCH_TAG              309
#define IDD_APPLY_PATCH_LIST            311
#define IDD_FORMAT_PATCH                312
#define IDD_MERGE                       313
#define IDD_SETTINGSCOLORS_1            315
#define IDD_SETTINGSCOLORS_3            316
#define IDD_RESET                       317
#define IDD_REBASE                      318
#define IDI_GITCONFIG                   319
#define IDD_REBASECHERRYPICK            319
#define IDI_GITREMOTE                   320
#define IDD_SENDMAIL                    320
#define IDD_SETTINGSMTP                 321
#define IDD_BROWSE_REFS                 322
#define IDD_ADD_REMOTE                  323
#define IDR_ACC_COMMITDLG               325
#define IDD_SYNC                        326
#define IDD_BUGTRAQREGEXTESTER          327
#define IDD_PATCH_VIEW                  328
#define IDD_SVNIGNORE                   329
#define IDD_CREATEREPO                  330
#define IDD_SVNDCOMMITTYPE              331
#define IDI_ACTIONFETCHING              332
#define IDD_SETTINGSPROGSALTERNATIVEEDITOR 333
#define IDD_REQUESTPULL                 334
#define IDI_GITFOLDER                   335
#define IDB_BITMAP_REFTYPE              336
#define IDI_IMPORTPATHCES_BKG           337
#define IDD_SETTINGSOVERLAYHANDLERS     338
#define IDI_LIBRARY                     339
#define IDD_SETTINGS_CONFIG             340
#define IDI_RESTORE                     341
#define IDI_RESTOREOVL                  342
#define IDI_JUMPUP                      343
#define IDI_JUMPDOWN                    344
#define IDD_LOGORDERING                 345
#define IDI_GITCREDENTIAL               346
#define IDI_EXTERNALOVL                 347
#define IDI_MERGEACTIVE                 348
#define IDI_EXECUTABLEOVL               349
#define IDI_SYMLINKOVL                  350
#define IDI_SPELL                       351
#define IDI_FILE                        352
#define IDI_CODE                        353
#define IDI_SNIPPET                     354
#define IDI_CERTCHECK                   355
#define IDI_TORTOISEUDIFF               356
#define IDD_SETTINGSUDIFF               357
#define IDI_LIBRARY_WIN10               358
#define IDR_REVISIONGRAPH               359
#define IDI_RESET                       361
#define IDI_NOTEPAD                     362
#define IDS_CHSTAT_FILECOL              1000
#define IDS_CHSTAT_WCCOL                1001
#define IDS_CHSTAT_REPOCOL              1002
#define IDC_LOGLIST                     1003
#define IDS_STATUSLIST_SKIPWORKTREE     1003
#define IDC_PASSEDIT                    1004
#define IDS_SETTINGS_BUGTRAQ_PATHCOL    1004
#define IDC_INFOTEXT                    1005
#define IDS_SETTINGS_BUGTRAQ_PROVIDERCOL 1005
#define IDS_SETTINGS_BUGTRAQ_PARAMETERSCOL 1006
#define IDS_ERR_MISSING_PROVIDER        1007
#define IDS_ERR_PROVIDER_VALIDATE_FAILED 1008
#define IDS_ERR_NO_AVAILABLE_BUGTRAQ_PROVIDERS 1009
#define IDC_EXPORTFILE                  1010
#define IDS_SETTINGS_BUGTRAQ_SELECTFOLDERPATH 1010
#define IDS_FILEDIFF_STATADD            1011
#define IDS_FILEDIFF_STATDEL            1012
#define IDC_SVNPROGRESS                 1013
#define IDS_PROC_DIFFERROR_FILENOTINWORKINGTREE 1013
#define IDC_LOGMESSAGE                  1014
#define IDS_MENURESTORE                 1014
#define IDC_FINDNEXT                    1014
#define IDC_LOGMSG                      1015
#define IDC_EXTDIFF                     1015
#define IDS_ERR_TGITBLAME               1015
#define IDC_EXTMERGE                    1016
#define IDS_PROC_RESETBRANCH            1016
#define IDC_DIFFVIEWER                  1017
#define IDS_STATUSLIST_CONTEXT_COPYFULLPATHS 1017
#define IDS_FILEDIFF_LOG                1018
#define IDS_PROC_TASKS                  1019
#define IDC_FINDTEXT                    1019
#define IDS_STATUSLIST_CONTEXT_COMPARETWOFILES 1020
#define IDC_FINDPREV                    1020
#define IDC_EXTDIFFBROWSE               1021
#define IDS_B_T_INVALID                 1021
#define IDC_MATCHCASECHECK              1021
#define IDC_EXTMERGEBROWSE              1022
#define IDS_B_T_LOCALEMPTY              1022
#define IDC_FINDEXIT                    1022
#define IDC_ENABLE                      1023
#define IDC_SAVECHECK                   1023
#define IDS_B_T_BOTHEMPTY               1023
#define IDS_LOG_FILTER_SUBJECT          1024
#define IDS_STATUSLIST_SHOWLOGOLDNAME   1025
#define IDS_APPNAME                     1026
#define IDC_NAME                        1027
#define IDC_SERVERADDRESS               1027
#define IDC_USEREDIT                    1027
#define IDS_MENUCREATERESTORE           1027
#define IDS_PROC_SUBMODULESUPDATE       1028
#define IDC_URLCOMBO                    1029
#define IDS_NOWORKINGCOPY               1029
#define IDC_FONTNAMES                   1030
#define IDS_PROCEXPORTERRFOLDER         1030
#define IDC_LOGBUTTON                   1031
#define IDC_UPDATE                      1031
#define IDS_PROC_NOZIPFILE              1031
#define IDC_DONOTASKAGAIN               1032
#define IDS_PROC_KEEPFILELOCAL          1032
#define IDS_PROC_FILESREMOVED           1033
#define IDS_PROC_AUTOGENERATEDBYGIT     1034
#define IDS_PATCH                       1035
#define IDC_EXPORTFILE_BROWSE           1036
#define IDC_INCLUDEPATHS                1036
#define IDS_LOG                         1036
#define IDS_PROC_APPLYPATCH_GITAMACTIVE 1037
#define IDC_SERVERPORT                  1038
#define IDS_SUCCESS                     1038
#define IDC_USERNAME                    1039
#define IDS_FAIL                        1039
#define IDC_PASSWORD                    1040
#define IDS_DONE                        1040
#define IDS_PROC_SKIPPATCH              1041
#define IDS_ABORTBUTTON                 1042
#define IDC_FILELIST                    1043
#define IDC_ADDLIST                     1043
#define IDC_CHANGEDLIST                 1043
#define IDC_MENULIST                    1043
#define IDC_REVERTLIST                  1043
#define IDS_OKBUTTON                    1043
#define IDC_LANGUAGECOMBO               1044
#define IDS_SKIPBUTTON                  1044
#define IDS_RESOLVEDBUTTON              1045
#define IDC_COMMIT_TO                   1046
#define IDS_PROC_APPLYPATCH_REBASEDIRFOUND 1046
#define IDS_PROC_PROGRESS_GITUNCLEANEXIT 1047
#define IDC_REMOVABLE                   1048
#define IDS_UPTODATE                    1048
#define IDC_COMMIT_AUTHORDATA           1048
#define IDC_NETWORK                     1049
#define IDS_SEECHANGES                  1049
#define IDC_FIXED                       1050
#define IDS_PROC_PULL_DIFFS             1050
#define IDC_CDROM                       1051
#define IDS_PROC_PULL_LOG               1051
#define IDS_PROGRS_TITLE_PULL           1052
#define IDS_PROGRS_TITLE_FETCH          1053
#define IDC_VERSIONABOUT                1054
#define IDS_PROC_RESTARTREBASE          1054
#define IDS_PROC_COMMITMESSAGE          1055
#define IDS_PROGS_TITLE_CHERRYPICK      1056
#define IDS_PROC_REVISIONFILES          1057
#define IDS_PROC_NOTHINGTOREBASE        1058
#define IDS_PROC_NOCLEAN                1059
#define IDS_PROC_NOHEAD                 1060
#define IDC_UNKNOWN                     1061
#define IDS_PROC_REBASE_STARTCHERRYPICK 1061
#define IDS_PROC_REBASE_STARTREBASE     1062
#define IDS_PROC_REBASEFINISHED         1063
#define IDC_INPUTTEXT                   1064
#define IDS_PROC_COMMITMESSAGE_EMPTY    1064
#define IDC_HINTTEXT                    1065
#define IDS_PROC_REBASING_PROGRESS      1065
#define IDS_PROC_REBASE_FFTO            1066
#define IDC_SELECTALL                   1067
#define IDS_PROC_CONFLICTFILES          1067
#define IDC_SSHCLIENT                   1068
#define IDC_INCLUDE_IGNORED             1068
#define IDS_AMENDBUTTON                 1068
#define IDC_SSHBROWSE                   1069
#define IDS_CONTINUEBUTTON              1069
#define IDS_COMMITBUTTON                1070
#define IDS_FINISHBUTTON                1071
#define IDC_RELATIVETIMES               1072
#define IDS_PROC_STARTREBASEBUTTON      1072
#define IDC_RAM                         1073
#define IDC_CHECKNEWERVERSION           1073
#define IDC_SHOWUNVERSIONED             1073
#define IDS_PROC_STARTREBASEFFBUTTON    1073
#define IDC_RIGHTSIDEBRANCHESTAGS       1073
#define IDC_EXPORTFILE_LABEL            1074
#define IDS_PROC_REBASE_EMPTYCOMMITMSG  1074
#define IDC_ASTERISKLOGPREFIX           1074
#define IDC_VERSIONBOX                  1075
#define IDS_PROC_REBASE_ABORT           1075
#define IDC_FULLCOMMITMESSAGEONLOGLINE  1075
#define IDC_LABEL                       1076
#define IDS_LASTCOMMIT                  1076
#define IDC_MSGVIEW                     1077
#define IDC_BUGID                       1077
#define IDC_EXCLUDEPATHS                1077
#define IDS_BRANCHNAME                  1077
#define IDS_DATELASTCOMMIT              1078
#define IDC_DRIVEGROUP                  1079
#define IDS_PROC_COMMIT_ADDSIGNOFFBUTTON 1079
#define IDC_PROXYGROUP                  1080
#define IDS_PROC_COMMIT_NOADDSIGNOFFBUTTON 1080
#define IDC_SSHGROUP                    1081
#define IDS_PROC_COMMIT_NOSIGNOFFLINE   1081
#define IDS_PROC_COMMIT_PREPARECOMMIT   1082
#define IDC_COMMITGROUP                 1083
#define IDS_PROC_COMMIT_UPDATEINDEX     1083
#define IDC_WEBLINK                     1084
#define IDS_PROC_COMMIT_DETACHEDWARNING 1084
#define IDC_SUPPORTLINK                 1085
#define IDS_PROC_COMMIT_RESTOREFILES    1085
#define IDC_FONTSIZES                   1086
#define IDS_PROC_COMMIT_RESTOREFILES_RESTORE 1086
#define IDS_PROC_COMMIT_RESTOREFILES_KEEP 1087
#define IDC_ONLYEXPLORER                1088
#define IDC_MERGEACTIVE_TT              1088
#define IDC_DIFFVIEWERBROWSE            1089
#define IDS_STATUSLIST_RESTOREPATH      1089
#define IDC_EXTDIFFADVANCED             1090
#define IDS_RESTOREBUTTON               1090
#define IDC_EXTDIFF_OFF                 1091
#define IDS_STATUSLIST_STATUSLINE1      1091
#define IDC_EXTDIFF_ON                  1092
#define IDS_STATUSLIST_STATUSLINE2      1092
#define IDC_EXTMERGEADVANCED            1093
#define IDS_STATUSLIST_FAILEDGETMERGEFILE 1093
#define IDC_EXTMERGE_OFF                1094
#define IDS_STATUSLIST_FAILEDGETBASEFILE 1094
#define IDC_EXTMERGE_ON                 1095
#define IDS_STATUSLIST_CHECKOUTFILEFAILED 1095
#define IDC_DIFFVIEWER_OFF              1096
#define IDS_STATUSLIST_FILESREVERTED    1096
#define IDC_DIFFVIEWER_ON               1097
#define IDS_REFBROWSE                   1097
#define IDC_ADDTOOL                     1098
#define IDS_REFLOG                      1098
#define IDC_EDITTOOL                    1099
#define IDS_PROGS_TITLE_REVERTCOMMIT    1099
#define IDC_REMOVETOOL                  1100
#define IDS_AUTH_USERNAME               1100
#define IDS_AUTH_PASSWORD               1101
#define IDC_TOOLLISTCTRL                1101
#define IDC_EXTEDIT                     1102
#define IDS_PROC_REVERTCOMMIT           1102
#define IDC_TOOLEDIT                    1103
#define IDS_PROC_PICK                   1103
#define IDC_TOOLBROWSE                  1104
#define IDS_PROC_CHERRYPICKFAILED       1104
#define IDC_SHORTDATEFORMAT             1105
#define IDS_PROC_NOPARENT               1105
#define IDC_SUMMARYTEXT                 1106
#define IDS_PROC_NOPREVIOUSVERSION      1106
#define IDS_PROC_CANNOTCOMBINE          1107
#define IDC_STATISTICS                  1108
#define IDS_PROC_COMBINE_ERRORSTEP1     1108
#define IDC_TEXT_INFO                   1109
#define IDS_PROC_COMBINE_ERRORSTEP2     1109
#define IDC_COMMITLABEL                 1110
#define IDS_REG_ERROR                   1110
#define IDC_PROGRESS                    1111
#define IDS_PROC_COMBINE_ERRORRESETHEAD 1111
#define IDC_YOURVERSION                 1112
#define IDS_PROC_DELETENREFS            1112
#define IDC_CURRENTVERSION              1113
#define IDS_PROC_DELETEREF              1113
#define IDC_CHECKRESULT                 1114
#define IDS_DELETEBUTTON                1114
#define IDS_PROC_DELETEREMOTEBRANCH     1115
#define IDC_SOURCE                      1115
#define IDS_PROC_DELETEREMOTEBRANCH_LOCALREMOTE 1116
#define IDS_PROC_DELETEREMOTEBRANCH_LOCAL 1117
#define IDS_PROC_DELETEALLSTASH         1118
#define IDC_BUGIDLABEL                  1119
#define IDS_PROC_DELETEBRANCHTAG        1119
#define IDS_PUTTYKEYFILEFILTER          1120
#define IDS_PROC_GITCONFIG_REMOTEEMPTY  1121
#define IDS_PROC_GITCONFIG_URLEMPTY     1122
#define IDS_PROC_GITCONFIG_OVERWRITEREMOTE 1123
#define IDC_ICONSETCOMBO                1124
#define IDS_PROC_GITCONFIG_SAVEREMOTE   1124
#define IDS_SAVEBUTTON                  1125
#define IDC_KEEPLISTS                   1126
#define IDC_SHOWEXCLUDEDASNORMAL        1126
#define IDC_SORTBYCOMMITCOUNT           1126
#define IDS_DISCARDBUTTON               1126
#define IDC_DIFFBYDOUBLECLICK           1127
#define IDS_PROC_SAVECONFIGFAILED       1127
#define IDC_COMMITTERNAMES              1127
#define IDS_WARN_REMOVE                 1128
#define IDC_ABBREVIATERENAMINGS         1128
#define IDC_COMMITDATES                 1128
#define IDS_PROC_GITCONFIG_EDITLOCALGONCFIG 1129
#define IDC_CHECK_UNTRACKED             1130
#define IDS_PROC_GITCONFIG_NOMSYSGIT    1130
#define IDC_GRAPH                       1131
#define IDS_PROC_CLONE_DIR              1131
#define IDC_CHECK_ALL                   1131
#define IDC_STATBUTTON                  1132
#define IDC_LOG                         1132
#define IDS_GITEXEERROR_NOMESSAGE       1132
#define IDC_GRAPHCOMBO                  1133
#define IDS_PROC_CLONE_URLDIREMPTY      1133
#define IDC_SHOWDIFF2                   1133
#define IDC_GRAPHTYPELABEL              1134
#define IDS_PROC_COMMIT_SHOWPATCH       1134
#define IDC_SHOWDIFF                    1134
#define IDC_COMMITSEACHWEEK             1135
#define IDS_PROC_COMMIT_HIDEPATCH       1135
#define IDC_MOSTACTIVEAUTHOR            1136
#define IDS_PROC_COMMIT_RECOMMIT        1136
#define IDC_LEASTACTIVEAUTHOR           1137
#define IDS_PROC_STASHFAILED            1137
#define IDC_FILECHANGESEACHWEEK         1138
#define IDS_PROC_STASHSUCCESS           1138
#define IDS_PROC_NOUSERDATA             1139
#define IDC_COMMITSEACHWEEKAVG          1140
#define IDS_PROC_PREVIOUSVERSION        1140
#define IDC_COMMITSEACHWEEKMIN          1141
#define IDS_PROC_REFINVALID             1141
#define IDC_COMMITSEACHWEEKMAX          1142
#define IDS_IGNOREBUTTON                1142
#define IDC_MOSTACTIVEAUTHORAVG         1143
#define IDS_PROC_STASHAPPLYFAILED       1143
#define IDC_MOSTACTIVEAUTHORMIN         1144
#define IDS_PROC_FILEDIFF_VERSION1BASE  1144
#define IDC_MOSTACTIVEAUTHORMAX         1145
#define IDS_PROC_FILEDIFF_VERSION2      1145
#define IDC_LEASTACTIVEAUTHORAVG        1146
#define IDS_PROC_FILEDIFF_VERSION2NEWER 1146
#define IDC_LEASTACTIVEAUTHORMIN        1147
#define IDS_PROC_FILEDIFF_VERSION1BASENEWER 1147
#define IDC_LEASTACTIVEAUTHORMAX        1148
#define IDS_ERR_PAEGENTTIMEOUT          1148
#define IDC_FILECHANGESEACHWEEKAVG      1149
#define IDS_ERR_NOPATCHES               1149
#define IDC_FILECHANGESEACHWEEKMIN      1150
#define IDS_PROC_REQUESTPULL            1150
#define IDC_FILECHANGESEACHWEEKMAX      1151
#define IDS_ERR_PULLREUQESTFAILED       1151
#define IDS_MSGBOX_HELP                 1152
#define IDS_MSGBOX_DONOTSHOWAGAIN       1153
#define IDS_MSGBOX_ABORT                1154
#define IDS_MSGBOX_RETRY                1155
#define IDC_MOSTACTIVEAUTHORNAME        1155
#define IDS_MSGBOX_IGNORE               1156
#define IDC_LEASTACTIVEAUTHORNAME       1156
#define IDS_MSGBOX_CANCEL               1157
#define IDC_AVG                         1157
#define IDS_MSGBOX_TRYAGAIN             1158
#define IDC_MIN                         1158
#define IDS_MSGBOX_CONTINUE             1159
#define IDC_MAX                         1159
#define IDS_MSGBOX_OK                   1160
#define IDC_NUMWEEK                     1160
#define IDS_MSGBOX_YES                  1161
#define IDC_NUMAUTHOR                   1161
#define IDS_MSGBOX_NO                   1162
#define IDC_NUMCOMMITS                  1162
#define IDS_SVNACTION_ADD               1163
#define IDC_NUMFILECHANGES              1163
#define IDS_SVNACTION_COPY              1164
#define IDC_NUMWEEKVALUE                1164
#define IDS_SVNACTION_DELETE            1165
#define IDC_NUMAUTHORVALUE              1165
#define IDS_SVNACTION_RESTORE           1166
#define IDC_NUMCOMMITSVALUE             1166
#define IDS_SVNACTION_REVERT            1167
#define IDC_NUMFILECHANGESVALUE         1167
#define IDS_SVNACTION_RESOLVE           1168
#define IDS_SVNACTION_UPDATE            1169
#define IDS_SVNACTION_COMPLETED         1170
#define IDC_ICONSETLABEL                1170
#define IDS_SVNACTION_EXTERNAL          1171
#define IDC_ICONLIST                    1171
#define IDS_SVNACTION_MODIFIED          1172
#define IDC_LISTRADIO                   1172
#define IDS_SVNACTION_REPLACED          1173
#define IDC_SYMBOLRADIO                 1173
#define IDS_SVNACTION_POSTFIX           1174
#define IDS_SVNACTION_FAILEDREVERT      1175
#define IDS_SVNACTION_STATUS            1176
#define IDS_SVNACTION_SKIP              1177
#define IDS_PROGS_EXTCOL                1178
#define IDS_PROGS_TOOLCOL               1179
#define IDS_LOG_FILE                    1180
#define IDS_USERCANCELLED               1181
#define IDC_AUTOCLOSECOMBO              1181
#define IDS_LOG_SIZE                    1182
#define IDS_ERR_INVALIDPATH             1183
#define IDC_AUTOCOMPLETION              1184
#define IDS_PROC_REMOVEBRANCH           1184
#define IDS_PROGS_TITLE_EDITNOTES       1185
#define IDS_PROC_FAILEDSAVINGNOTES      1186
#define IDS_PROC_FASTFORWARD            1187
#define IDS_PROC_EVERYTHINGUPDATED      1188
#define IDS_PROC_SYNC_PULLWRONGBRANCH   1189
#define IDS_PROC_SYNC_REFRESHING        1190
#define IDC_SPLITTERTOP                 1191
#define IDS_PROC_SYNC_COMMITSAHEAD      1191
#define IDC_SPLITTERBOTTOM              1192
#define IDS_PROC_SYNC_WAINTINPUT        1192
#define IDS_PROC_SYNC_PUSH_UNKNOWN      1193
#define IDC_SEARCHEDIT                  1194
#define IDS_PROC_SYNC_PUSH_UNKNOWNBRANCH 1194
#define IDS_PROC_SYNC_INCOMMITS         1195
#define IDS_PROC_SYNC_INCHANGELIST      1196
#define IDS_PROC_SYNC_OUTCOMMITS        1197
#define IDC_DATETO                      1198
#define IDS_PROC_SYNC_OUTCHANGELIST     1198
#define IDC_DATEFROM                    1199
#define IDS_PROC_SYNC_PUSH              1199
#define IDC_FROMLABEL                   1200
#define IDS_PROC_LOG_STATS              1200
#define IDC_TOLABEL                     1201
#define IDS_PROC_LOG_ALLBRANCHES        1201
#define IDS_PROC_LOG_NOBRANCH           1202
#define IDC_WHOLE_PROJECT               1203
#define IDS_SETTINGS_CREATELIB_TT       1203
#define IDS_STATUSLIST_GROUP_MERGEDFILES 1204
#define IDS_IMPORT_DEFAULTMSG           1205
#define IDS_STATUSLIST_GROUP_MODIFIEDFILES 1206
#define IDC_CHECKBOX                    1207
#define IDS_PROC_SYNC_PUSHTAGS          1207
#define IDS_PROC_SYNC_PULL              1208
#define IDC_SHOWUNMODIFIED              1209
#define IDS_PROC_SYNC_FETCH             1209
#define IDS_PROC_SYNC_FETCHREBASE       1210
#define IDC_SHOWSTAGED                  1210
#define IDS_LOG_REVERT_CONFIRM          1211
#define IDS_PROC_SYNC_REMOTEUPDATE      1212
#define IDS_PROC_SYNC_CLEANUPSTALEBRANCHES 1213
#define IDS_PROC_SYNC_SUBKODULEUPDATE   1214
#define IDC_CHECKNEWERBUTTON            1215
#define IDS_PROC_SYNC_SUBKODULEINIT     1215
#define IDS_LOG_POPUP_COPY              1216
#define IDC_MSYSGIT_CHECK               1216
#define IDS_COMMITDLG_FILE              1217
#define IDS_COMMITDLG_STATUS            1218
#define IDS_COMMITDLG_ASKADD            1219
#define IDS_COMMITDLG_NOTHINGTOCOMMIT   1220
#define IDC_REALM                       1220
#define IDS_PROGRS_ATREV                1221
#define IDC_AUTOCOMPLETIONTIMEOUT       1221
#define IDS_PROGRS_ACTION               1222
#define IDC_AUTOCOMPLETIONTIMEOUTLABEL  1222
#define IDS_PROGRS_PATH                 1223
#define IDS_PROGRS_TITLEFIN             1224
#define IDS_PROGRS_TITLE_CHECKOUT       1225
#define IDS_PROGRS_TITLE_IMPORT         1226
#define IDS_PROGRS_TITLE_UPDATE         1227
#define IDS_PROC_SYNC_SUBKODULESYNC     1227
#define IDS_PROGRS_TITLE_COMMIT         1228
#define IDS_PROGRS_TITLE_ADD            1229
#define IDS_PROGRS_TITLE_REVERT         1230
#define IDS_PROGRS_TITLE_RESOLVE        1231
#define IDC_RESOLVELIST                 1231
#define IDS_PROGRS_TITLE_SWITCH         1232
#define IDS_PROGRS_TITLE_EXPORT         1233
#define IDS_PROGRS_TITLE_MERGE          1234
#define IDS_PROGRS_TITLE_COPY           1235
#define IDS_PROC_DOWNLOAD               1236
#define IDS_ERR_MISSINGVALUE            1237
#define IDS_STATUSLIST_GROUP_NOTVERSIONEDFILES 1238
#define IDS_STATUSLIST_GROUP_IGNOREDFILES 1239
#define IDC_MERGEACTIVE                 1239
#define IDS_PROGRS_REVERTMARKERS        1240
#define IDS_SETTINGS_SELECTDIFF         1241
#define IDC_MESSAGEGROUP                1241
#define IDS_SETTINGS_SELECTDIFFVIEWER   1242
#define IDC_LISTGROUP                   1242
#define IDS_SETTINGS_SELECTMERGE        1243
#define IDC_PROGRESSBAR                 1243
#define IDS_SETTINGS_SELECTSSH          1244
#define IDC_PROGRESSLABEL               1244
#define IDS_SETTINGS_EXTDIFF_TT         1245
#define IDC_HISTORYLIST                 1245
#define IDS_SETTINGS_EXTDIFFBROWSE_TT   1246
#define IDS_SETTINGS_CHANGEDDIRS_TT     1247
#define IDS_PROC_BROWSEREFS_FETCHFROM   1247
#define IDS_MSYSGIT_PATH_TT             1248
#define IDC_CONFLICTCOLOR               1249
#define IDS_PROC_BROWSEREFS_COMPAREREFS 1249
#define IDS_SETTINGS_EXTMERGE_TT        1250
#define IDC_ADDEDCOLOR                  1250
#define IDS_SETTINGS_PROXYSERVER_TT     1251
#define IDC_DELETEDCOLOR                1251
#define IDS_SETTINGS_DIFFVIEWER_TT      1252
#define IDC_MERGEDCOLOR                 1252
#define IDS_SETTINGS_AUTOCLOSE_TT       1253
#define IDC_MODIFIEDCOLOR               1253
#define IDC_RESTORE                     1254
#define IDS_PROC_BROWSEREFS_RENAME      1254
#define IDS_PROC_BROWSEREFS_MANAGEREMOTES 1255
#define IDS_PROC_WARNREVERT             1256
#define IDC_NOTENODECOLOR               1256
#define IDS_PROC_CLEANUPFINISHED        1257
#define IDC_RENAMEDCOLOR                1257
#define IDS_PROC_REPOCREATEERR          1258
#define IDC_OTHERREFSCOLOR              1258
#define IDS_PROC_EXPORT_1               1259
#define IDS_PROC_EXPORT_2               1260
#define IDS_PROC_EXPORT_3               1261
#define IDC_SKIPPER                     1261
#define IDC_SKIPPERLABEL                1262
#define IDS_SELECT                      1262
#define IDS_HOOKS_APPROVE_SECURITYHINT  1263
#define IDS_PROC_SETTINGS_TITLE         1264
#define IDC_SHOWIGNORED                 1264
#define IDC_AUTHORSCASESENSITIVE        1265
#define IDS_SETTINGS_ALTERNATIVEEDITOR_TT 1265
#define IDC_SHOWLOCALCHANGESIGNORED     1265
#define IDS_PROC_OVERWRITE_CONFIRM      1266
#define IDS_PROC_REPOCREATEFINISHED     1267
#define IDC_MAXHISTORY                  1268
#define IDS_PROC_BROWSEREFS_DELETEREMOTEBRANCH 1268
#define IDS_PROC_MOVING                 1269
#define IDC_CACHEDEFAULT                1269
#define IDC_CACHESHELL                  1270
#define IDS_PROC_STASHRUNNING           1270
#define IDC_CACHESHELL2                 1271
#define IDS_PROC_BROWSEREFS_DELETEREMOTEBRANCHES 1271
#define IDC_CACHENONE                   1272
#define IDS_MSGBOX_DONOTSHOW            1272
#define IDC_URLHISTORY                  1272
#define IDS_PROC_COPYING                1273
#define IDC_URLHISTCLEAR                1273
#define IDS_PROC_COPYINGPROG            1274
#define IDC_LOGHISTORY                  1274
#define IDS_PROC_MOVINGPROG             1275
#define IDC_LOGHISTCLEAR                1275
#define IDS_PROC_CPYMVPROG2             1276
#define IDC_RESIZABLEHISTCLEAR          1276
#define IDS_PROC_ENTERURL               1277
#define IDC_RESIZABLEHISTORY            1277
#define IDC_AUTHHISTORY                 1278
#define IDS_PROC_BROWSEREFS_DELETEBRANCH 1278
#define IDS_SETTINGS_SHORTDATEFORMAT_TT 1279
#define IDC_AUTHHISTCLEAR               1279
#define IDC_HOOKADDBUTTON               1279
#define IDC_BUGTRAQADDBUTTON            1279
#define IDC_BUTTON_TABCTRL              1279
#define IDS_SETTINGS_RELATIVETIMES_TT   1280
#define IDC_REPOLOG                     1280
#define IDC_REPOLOGCLEAR                1281
#define IDS_PROC_BROWSEREFS_DELETEBRANCHES 1281
#define IDS_ERR_EXTDIFFSTART            1282
#define IDS_ERR_NOCOMMAND               1283
#define IDS_ERR_NOCOMMANDVALUE          1284
#define IDS_ERR_NOSTATUS                1285
#define IDS_LOG_SUBMODULE               1286
#define IDS_ERR_NOURLOFFILE             1287
#define IDS_PROC_INSTALL                1288
#define IDS_ERR_COPYFILES               1289
#define IDS_ERR_EXTMERGESTART           1290
#define IDS_STATUSLIST_GROUP_DIFFWITHPARENT 1291
#define IDS_ERR_FAILEDIGNOREPROPERTY    1292
#define IDS_ERR_DIFFVIEWSTART           1293
#define IDS_PROGS_TITLE_CREATETAG       1294
#define IDS_PROC_LOG_FETCHINGFILES      1295
#define IDS_NOTES                       1296
#define IDC_GRAPHBARBUTTON              1297
#define IDS_PROC_LOG_TAGINFO            1297
#define IDC_GRAPHBARSTACKEDBUTTON       1298
#define IDS_PROGS_TITLE_CREATEBRANCH    1298
#define IDC_GRAPHLINEBUTTON             1299
#define IDS_PROC_TAG                    1299
#define IDC_GRAPHLINESTACKEDBUTTON      1300
#define IDS_PROC_BRANCH                 1300
#define IDC_GRAPHPIEBUTTON              1301
#define IDC_FIRSTURL                    1301
#define IDS_PROC_NEWBRANCHTAG_FORCE_TT  1301
#define IDC_DIFFSTATIC1                 1302
#define IDC_SUBMODULEDIFFTITLE          1302
#define IDS_PROC_NEWBRANCHTAG_SIGN_TT   1302
#define IDS_ERR_COPYITSELF              1303
#define IDC_SECONDURL                   1303
#define IDS_ERR_INVALIDREV              1304
#define IDS_SUBMODULE_EMPTYDIFF         1305
#define IDS_ERR_NOTHINGTOADD            1306
#define IDS_ERR_ERROR                   1307
#define IDC_SWITCHLEFTRIGHT             1307
#define IDS_ERR_NOVALIDPATH             1308
#define IDS_ERR_FAILEDUNIGNOREPROPERTY  1309
#define IDS_ERR_NOTHINGTOREVERT         1310
#define IDS_ERR_NOCOMMONCOPYFROM        1311
#define IDC_SPLITTER                    1312
#define IDS_LOG_FILTER_REFNAME          1312
#define IDS_ERR_NOTENOUGHMEMORY         1313
#define IDC_UNVERSIONEDASMODIFIED       1313
#define IDS_ERR_MUSTBEURL               1314
#define IDC_RECURSIVESUBMODULES         1314
#define IDC_FLOPPY                      1315
#define IDS_CHECKUPDATE_DESTFOLDER      1315
#define IDS_ERR_MERGEIDENTICALREVISIONS 1316
#define IDC_MAXHISTORYLABEL             1317
#define IDS_ERR_NOHOOKTYPESPECIFIED     1317
#define IDS_ERR_NOHOOKPATHSPECIFIED     1318
#define IDS_ERR_NOHOOKCOMMANDPECIFIED   1319
#define IDS_ERR_HOOKFAILED              1320
#define IDS_PROC_BROWSEREFS_DELETETAG   1321
#define IDS_ERR_FAILEDUPDATEDOWNLOAD    1322
#define IDC_HOOKPATH                    1323
#define IDS_ERR_NOPREVREVISION          1323
#define IDC_HOOKBROWSE                  1324
#define IDS_PROC_CLEANUPFINISHED_FAILED 1324
#define IDC_HOOKCOMMANDLINE             1325
#define IDS_ERR_TWOLOGPARAMS            1325
#define IDC_HIDECHECK                   1326
#define IDS_ERR_TEXTVIEWSTART           1326
#define IDC_WAITCHECK                   1327
#define IDS_ERR_FAILEDISSUETRACKERCOM   1327
#define IDS_PROC_BROWSEREFS_DELETETAGS  1328
#define IDC_HOOKTYPECOMBO               1329
#define IDS_PROCS_TITLE_GITREMOTESETTINGS 1329
#define IDC_HOOKLIST                    1330
#define IDS_PROC_BROWSEREFS_RENAMEONLYBRANCHES 1330
#define IDC_HOOKEDITBUTTON              1331
#define IDS_PROC_BROWSEREFS_NOCHANGEOFTYPE 1331
#define IDC_HOOKREMOVEBUTTON            1332
#define IDS_PROC_BROWSEREFS_WARNINGUNMERGED 1332
#define IDC_HOOKCOMMANDBROWSE           1333
#define IDS_PROC_BROWSEREFS_WARNINGNOMERGECHECK 1333
#define IDC_HOOKTYPELABEL               1334
#define IDS_PROC_BROWSEREFS_WARNINGDELETEREMOTEBRANCHES 1334
#define IDC_HOOKWCPATHLABEL             1335
#define IDS_PROC_NOMSYSGIT              1335
#define IDC_HOOKCMLABEL                 1336
#define IDS_PROC_SETMSYSGITPATH         1336
#define IDC_LOGINFO                     1337
#define IDS_PROC_GOTOMSYSGITWEBSITE     1337
#define IDS_PROC_OLDMSYSGIT             1338
#define IDS_PROC_NOTSHOWAGAINIGNORE     1339
#define IDS_PROC_EDITLOCALGITCONFIG     1340
#define IDS_PROC_EDITGLOBALGITCONFIG    1341
#define IDS_PROC_STASHPOPSUCCESS        1342
#define IDS_PROC_STASHAPPLYSUCCESS      1343
#define IDS_PROC_STASHPOPFAILED         1344
#define IDS_PROC_STASHPOPFAILEDCONFLICTS 1345
#define IDS_PROC_STASHAPPLYFAILEDCONFLICTS 1346
#define IDS_PROC_CREATED                1347
#define IDS_PROC_NEWBRANCHTAG_TRACK_TT  1348
#define IDS_STATUSLIST_FROM             1349
#define IDS_LASTAUTHOR                  1350
#define IDS_B_T_NOT_UNIQUE              1351
#define IDS_B_EXISTS                    1352
#define IDC_REV1BTN                     1353
#define IDS_T_EXISTS                    1353
#define IDC_REV2BTN                     1354
#define IDS_B_DELETEORDIFFERENTNAME     1354
#define IDC_REV1BTN2                    1354
#define IDS_B_T_DIFFERENTNAMEORFORCE    1355
#define IDC_RESETFILTER                 1355
#define IDS_B_DIFFERENTNAMEOROVERRIDE   1356
#define IDS_T_SAMEBRANCHNAMEEXISTS      1357
#define IDS_B_SAMETAGNAMEEXISTS         1358
#define IDS_SETTINGS_ABBREVIATERENAMINGS_TT 1359
#define IDS_PROC_PUSHFETCH_ALLREMOTES   1360
#define IDS_PROC_SYNC_NOFASTFORWARD     1361
#define IDS_PUSHDLG_PUSHBRANCH_TT       1362
#define IDS_PUSHDLG_PUSHREMOTE_TT       1363
#define IDS_STATUSLIST_COLLASTMODIFIED  1364
#define IDS_STATUSLIST_COLSIZE          1365
#define IDS_DELETEREMOTETAG             1366
#define IDC_HOOKCOPYBUTTON              1367
#define IDS_REVREVERTED                 1367
#define IDC_INFOLABEL                   1368
#define IDS_DESCRIPTION                 1368
#define IDS_PROC_BROWSEREFS_EDITDESCRIPTION 1369
#define IDS_PROC_SYNC_CONFLICTS         1370
#define IDC_REPOTREE                    1371
#define IDS_STASHBUTTON                 1371
#define IDC_REPOLIST                    1372
#define IDC_BUGTRAQLIST                 1372
#define IDC_LIST_PATCH                  1372
#define IDC_COMMIT_LIST                 1372
#define IDC_LIST_REMOTE                 1372
#define IDC_LIST_REF_LEAFS              1372
#define IDS_SETTINGS_FETCH_ADDEDREMOTE  1372
#define IDS_STASHSAVE_INCLUDEUNTRACKED  1373
#define IDS_PROC_NOTSHOWAGAINCONTINUE   1374
#define IDS_PROC_LOG_JUMPNOTFOUND       1375
#define IDS_RECURSE_SUBMODULES_CHECK    1376
#define IDS_RECURSE_SUBMODULES_ONDEMAND 1377
#define IDC_NEWLINESCOLOR               1378
#define IDS_PROC_SHOWDIFF               1378
#define IDS_PROC_LOADING                1379
#define IDS_FILEDIFF_EXT                1380
#define IDC_OLDLINESCOLOR               1380
#define IDS_ERR_EMPTYDIFF               1381
#define IDC_TABSIZE                     1381
#define IDC_REFRESH                     1382
#define IDC_ACTIONLOGSHOW               1382
#define IDC_BUGTRAQEDITBUTTON           1382
#define IDC_BUGTRAQBUTTON               1382
#define IDC_RESTOREDEFAULTS             1382
#define IDC_OPTIONS                     1382
#define IDC_CLONE_BROWSE_URL            1382
#define IDC_BUTTON_SHOW                 1382
#define IDC_BUTTON_ADD                  1382
#define IDC_REMOTE_MANAGE               1382
#define IDC_PROGRESS_BUTTON1            1382
#define IDC_BUTTON_LOCAL_BRANCH         1382
#define IDC_EDITGLOBALGITCONFIG         1382
#define IDC_BUTTON_SHOW_ENV             1382
#define IDS_PROC_TAG_FF                 1382
#define IDC_SHOW_MODIFIED_FILES         1383
#define IDC_REPOGROUP                   1383
#define IDC_CLONE_DIR_BROWSE            1383
#define IDC_BUTTON_TO                   1383
#define IDC_REBASE_POST_BUTTON          1383
#define IDC_BUTTON_REMOTE_BRANCH        1383
#define IDC_EDITLOCALGITCONFIG          1383
#define IDC_COMMIT                      1383
#define IDS_GITVER_REQUIRED             1383
#define IDC_BUTTON_BAD                  1383
#define IDC_BUTTON_DIR                  1384
#define IDC_BUTTON_DOWN                 1384
#define IDC_PUTTYKEYFILE_BROWSE         1384
#define IDC_BUTTON_STASH                1384
#define IDC_EDITSYSTEMGITCONFIG         1384
#define IDS_SETTINGS_SYMBOLIZEREFNAMES_TT 1384
#define IDC_FROMGROUP                   1385
#define IDC_BUTTON_REMOVE               1385
#define IDC_CONFIG                      1385
#define IDC_BUTTON_UNIFIEDDIFF          1385
#define IDS_PROC_SYNC_PUSHNOTES         1385
#define IDC_BUTTON_UP                   1386
#define IDS_PROC_REPOCREATED            1386
#define IDC_FILTER                      1387
#define IDS_PROC_BROWSEREFS_DELETEALLTAGS 1387
#define IDS_SETTINGS_ENABLELOGCACHE_TT  1388
#define IDS_LOG_FILTER_EMAILS           1389
#define IDS_CARE_SUBMODULE_CHANGES      1390
#define IDS_STATUSLIST_WARN_MAXDIFF     1391
#define IDS_PROC_MARK_ASSUMEVALID       1392
#define IDS_PROC_MARK_SKIPWORKTREE      1393
#define IDS_SHOWLOG_OF                  1394
#define IDS_LOG_CHRONOLOGICALREVERSEDORDER 1395
#define IDS_TORTOISEGITDEFAULT          1396
#define IDS_DELETING_REMOTE_REFS        1397
#define IDS_ADVANCED                    1398
#define IDS_LOCAL_WINCRED               1399
#define IDS_WARN_FOLDERNOTEXIST         1400
#define IDS_LOCAL_WINSTORE              1401
#define IDS_GLOBAL_WINCRED              1402
#define IDS_GLOBAL_WINSTORE             1403
#define IDS_WARN_GITINIT_FOLDERNOTEMPTY 1404
#define IDS_WARN_WARNING                1405
#define IDC_SELECTFILESONCOMMIT         1405
#define IDS_WARN_NOTE                   1406
#define IDC_STRIPCOMMENTEDLINES         1406
#define IDS_WARN_NOVALIDPATH            1407
#define IDC_NOAUTOSELECTMISSING         1407
#define IDS_SYSTEM_WINCRED              1408
#define IDC_PROXYLABEL1                 1409
#define IDS_DAEMON_SECURITY_WARN        1409
#define IDC_PROXYLABEL2                 1410
#define IDS_ASK_REMOVE_FROM_INDEX       1410
#define IDC_PROXYLABEL3                 1411
#define IDS_REMOVE_FROM_INDEX           1411
#define IDC_PROXYLABEL4                 1412
#define IDS_DO_SAME_FOR_REST            1412
#define IDC_PROXYLABEL5                 1413
#define IDS_PROGRS_TITLE_RESET          1413
#define IDC_PROXYLABEL6                 1414
#define IDS_RESET_SOFT                  1414
#define IDS_SETTINGS_LOCAL              1415
#define IDS_SETTINGS_GLOBAL             1416
#define IDS_SETTINGS_SYSTEM             1417
#define IDS_GITCREDENTIAL_HELPEREMPTY   1418
#define IDS_GITCREDENTIAL_OVERWRITEHELPER 1419
#define IDS_GITCREDENTIAL_SAVEHELPER    1420
#define IDS_STATGRAPH_COMMITSBYAUTHORMOREX 1421
#define IDS_RESET_MIXED                 1422
#define IDS_RESET_HARD                  1423
#define IDS_CHERRYPICKFAILEDSKIP        1424
#define IDS_COPY_REF_NAMES              1425
#define IDC_SYSTEMLOCALEFORDATES        1426
#define IDS_PROC_GITCONFIG_VIEWTGITCONFIG 1426
#define IDC_ACTIONLOGCLEAR              1427
#define IDS_SMTP_MAPI                   1427
#define IDC_MAXLINES                    1428
#define IDS_SMTP_DIRECTLY               1428
#define IDS_PROC_GITCONFIG_ASKTAGOPT    1429
#define IDS_COMMITDLG_POPUP_PICKCOMMITHASH 1430
#define IDS_COMMITDLG_POPUP_PICKCOMMITMESSAGE 1431
#define IDC_SHOWIGNOREDOVERLAY          1432
#define IDC_USERECYCLEBIN               1432
#define IDS_REPOBROWSE_INFO             1432
#define IDS_REPOBROWSE_INFOEXT          1433
#define IDS_WORKING_TREE                1434
#define IDS_REPOBROWSE_INFOFILE         1435
#define IDS_REPOBROWSE_INFOMULTI        1436
#define IDS_SETTINGS_ENABLEGRAVATAR_TT  1437
#define IDS_SETTINGS_GRAVATARURL_TT     1438
#define IDS_PROC_SWITCH_MERGE_TT        1439
#define IDS_PROC_CONFIRMKILLPROCESS     1440
#define IDS_SETTINGS_CONFIRMKILLPROCESS_TT 1441
#define IDS_SYNCDIALOGRANDOMPOS_TT      1442
#define IDS_CONFIG_LOCAL                1443
#define IDS_CONFIG_PROJECT              1444
#define IDS_CONFIG_GLOBAL               1445
#define IDS_CONFIG_GLOBAL_TT            1446
#define IDS_CONFIG_PROJECT_TT           1447
#define IDS_CONFIG_LOCAL_TT             1448
#define IDS_COMPAREREV_NODIFF           1449
#define IDS_WARNUSERSAFEDIFFERENT       1450
#define IDS_WALKBEHAVIOUR_FIRSTPARENT   1451
#define IDS_WALKBEHAVIOUR_FOLLOWRENAMES 1452
#define IDS_SHOWFILES_HIDEPATHS         1453
#define IDS_SHOWFILES_GRAYPATHS         1454
#define IDS_VIEW_SHOWTAGLABELS          1455
#define IDS_VIEW_SHOWLOCALBRANCHLABELS  1456
#define IDS_VIEW_SHOWREMOTEBRANCHLABELS 1457
#define IDS_VIEW_LABELS                 1458
#define IDS_B_T_PREFILL_ORIGIN          1459
#define IDS_HINT                        1460
#define IDS_VIEW_SHOWGRAVATAR           1461
#define IDC_SHOWUNVERSIONEDOVERLAY      1462
#define IDS_WALKBEHAVIOUR_COMPRESSED    1462
#define IDS_WALKBEHAVIOUR_LABELEDCOMMITS 1463
#define IDS_WALKBEHAVIOUR_NOMERGES      1464
#define IDS_ICONFILEFILTER              1465
#define IDC_LINK                        1466
#define IDS_PROC_OVERWRITEEXPORT_CANCEL 1466
#define IDS_PROC_OVERWRITEEXPORT_OVERWRITE 1467
#define IDS_PROC_OVERWRITEEXPORT_KEEP   1468
#define IDC_BUGTRAQPARAMETERS           1469
#define IDC_CLONE_DIR                   1469
#define IDS_WARN_RENAMEREQUIRED         1469
#define IDC_BUGTRAQREMOVEBUTTON         1470
#define IDC_GIT_USEREMAIL               1470
#define IDC_EDIT_REMOTE                 1470
#define IDC_SMTP_PORT                   1470
#define IDC_EDIT_SVN_FROM               1470
#define IDC_REV2EDIT                    1470
#define IDC_NEWBRANCH                   1470
#define IDS_RENAME_INFO                 1470
#define IDC_BUGTRAQCOPYBUTTON           1471
#define IDC_GIT_USERESINGNINGKEY        1471
#define IDS_PROC_COPY_SUBMODULE         1471
#define IDC_BUGTRAQWCPATHLABEL          1472
#define IDS_PROC_COPY_REPOSITORY        1472
#define IDC_BUGTRAQPATH                 1473
#define IDS_HIERARCHICALCONFIG          1473
#define IDS_OFFLINEMODE                 1474
#define IDC_BUGTRAQBROWSE               1474
#define IDS_CHECKNEWER_NETERROR_FORMAT  1475
#define IDC_BUGTRAQPROVIDERLABEL        1475
#define IDC_BUGTRAQPROVIDERCOMBO        1476
#define IDS_PROC_BRANCH_FF              1476
#define IDC_BUGTRAQPARAMETERSLABEL      1477
#define IDS_PROC_LOG_LOCAL_BRANCHES     1477
#define IDC_BROWSEREFS_EDIT_FILTER      1478
#define IDS_PROC_LOG_SELECT_LOCAL_BRANCHES 1478
#define IDC_BROWSEREFS_STATIC_FILTER    1479
#define IDS_STATUSLIST_GROUP_IGNORELOCALCHANGES 1479
#define IDC_FORCE                       1480
#define IDS_PROC_UNSET_IGNORELOCALCHANGES 1480
#define IDC_UNVERSIONEDITEMS            1481
#define IDC_CHECK_NOFF                  1481
#define IDC_SENDMAIL_COMBINE            1481
#define IDC_PUSHALL                     1481
#define IDS_STATUSLIST_UNSETIGNORELOCALCHANGES 1481
#define IDC_SIGN_OFF                    1482
#define IDC_SIGNOFF                     1482
#define IDC_CHECK_NOCOMMIT              1482
#define IDC_PROC_PUSH_SET_PUSHREMOTE    1482
#define IDS_LOG_FILTER_TOGGLE           1482
#define IDC_BUTTON_BROWSE               1483
#define IDC_BUTTON_BROWSE_SOURCE_BRANCH 1483
#define IDC_BUTTON_BROWSE_REF           1483
#define IDC_BUTTON_MANAGE               1483
#define IDC_KEEP_CR                     1483
#define IDS_WARN_GITINIT_SPECIALFOLDER  1483
#define IDC_BUTTON_BROWSE_DEST_BRANCH   1484
#define IDC_CHECK_FFONLY                1484
#define IDS_SAMPLEBUGTRAQTESTMSG        1484
#define IDC_TITLE_ANIMATE               1485
#define IDC_CHECK_FETCHTAGS             1485
#define IDC_PROC_PUSH_SET_PUSHBRANCH    1485
#define IDS_REFBROWSE_INFO              1485
#define IDC_RUN_PROGRESS                1486
#define IDC_PROC_PUSH_SET_UPSTREAM      1486
#define IDS_SWITCH_WITH_MERGE           1486
#define IDC_CURRENT                     1487
#define IDC_STATIC_RECURSE_SUBMODULES   1487
#define IDS_SELECTFILE                  1487
#define IDC_COMBOBOX_RECURSE_SUBMODULES 1488
#define IDS_SETTINGS_ENABLEDRAGCONTEXTMENU_TT 1488
#define IDC_REMOTE_COMBO                1489
#define IDC_BRANCH_REMOTE               1489
#define IDC_COMBOBOXEX_BRANCH           1489
#define IDC_COMBOBOXEX_FROM             1489
#define IDS_DIFFOPTION_IGNORESPACEATEOL 1489
#define IDC_REMOTE_RD                   1490
#define IDC_URL                         1490
#define IDC_COMBOBOXEX_TAGS             1490
#define IDC_COMBOBOXEX_TO               1490
#define IDS_DIFFOPTION_IGNORESPACECHANGE 1490
#define IDC_COMBOBOXEX_VERSION          1491
#define IDS_DIFFOPTION_IGNOREALLSPACE   1491
#define IDC_OTHER_RD                    1492
#define IDS_DIFFOPTION_IGNORBLANKLINES  1492
#define IDC_OTHER                       1493
#define IDC_BRANCH_SOURCE               1493
#define IDS_SELECTUPSTREAM              1493
#define IDC_REMOTE_BRANCH               1494
#define IDC_RD_REMOTE                   1494
#define IDS_SELECTBRANCH                1494
#define IDC_RD_URL                      1495
#define IDC_COLOR_LINE7                 1495
#define IDS_B_CANNOTFORCECURRENT        1495
#define IDC_REMOTE                      1496
#define IDS_REPOBROWSEASKSUBMODULEUPDATE 1496
#define IDS_TRACKEDBRANCH               1497
#define IDS_REBASE_AUTOSKIPPED          1498
#define IDC_FORCE_WITH_LEASE            1498
#define IDC_TAGS                        1499
#define IDS_PROC_REBASE_SELECTALL_SQUASH 1499
#define IDS_EXPORTFILE_TT               1500
#define IDC_BRANCH_GROUP                1500
#define IDC_COLOR_LINE8                 1500
#define IDC_FILTERMATCHCOLOR            1500
#define IDS_CHECKOUT_EXPORTDIR          1501
#define IDC_URL_GROUP                   1501
#define IDC_OPTION_GROUP                1502
#define IDS_PROC_REBASE_SELECTALL_EDIT  1502
#define IDC_STATIC_REMOTE               1503
#define IDS_PROC_REBASE_SELECTALL_PICK  1503
#define IDC_STATIC_SOURCE               1504
#define IDS_DELETEREMOTETAGON           1504
#define IDC_PUTTYKEY_AUTOLOAD           1505
#define IDS_B_T_REMOTE_NAME_COLLIDE     1505
#define IDS_CHANGETYPE                  1506
#define IDS_OLDHASH                     1507
#define IDS_OLDMESSAGE                  1508
#define IDS_NEWHASH                     1509
#define IDS_NEWMESSAGE                  1510
#define IDC_SENDMAIL_SUBJECT            1510
#define IDC_BUGTRAQ_LABEL               1510
#define IDC_CHECK_SVN_BRANCH            1510
#define IDS_SAME                        1511
#define IDC_RADIO_HEAD                  1511
#define IDC_BUGTRAQ_LOGREGEX            1511
#define IDC_EDIT_SVN_TAG                1511
#define IDS_NEW                         1512
#define IDC_RADIO_BRANCH                1512
#define IDC_EDIT_SVN_BRANCH             1512
#define IDS_DELETED                     1513
#define IDC_RADIO_TAGS                  1513
#define IDC_CHECK_SVN_TAG               1513
#define IDS_FORWARDN                    1514
#define IDC_RADIO_VERSION               1514
#define IDS_REWINDN                     1515
#define IDC_GROUP_BRANCH                1515
#define IDS_REFLIST                     1516
#define IDS_HIDEUNCHANGED               1517
#define IDC_GROUP_OPTION                1517
#define IDS_REFCOMPAREHIDEUNCHANGED_TT  1518
#define IDC_LABEL_BRANCH                1518
#define IDC_BRANCH_TAG                  1519
#define IDS_SORTTAGSREVERSED_TT         1519
#define IDC_AUTOTEXTCONTENT             1520
#define IDC_CHECK_TRACK                 1520
#define IDS_CLEAN_TO_RECYCLEBIN         1520
#define IDC_AUTOTEXTREGEX               1521
#define IDC_CHECK_FORCE                 1521
#define IDS_CLEAN_NO_RECYCLEBIN         1521
#define IDC_AUTOTEXTSCAN                1522
#define IDC_GROUP_BASEON                1522
#define IDS_FORCE_WITH_LEASE_TT         1522
#define IDC_TESTRESULT                  1523
#define IDC_CHECK_BRANCHOVERRIDE        1523
#define IDC_CHECK_SIGN                  1523
#define IDS_FORCE_TT                    1523
#define IDC_TIMINGLABEL                 1524
#define IDC_CHECK_SQUASH                1524
#define IDS_PROC_REBASE_CONTINUE_NOTCLEAN 1524
#define IDC_CHECK_SWITCH                1525
#define IDS_PROC_COMMIT_SUPERPROJECT    1525
#define IDC_CHECK_MERGE                 1526
#define IDS_LOG_NOT_VISIBLE             1526
#define IDC_CHECK_BRANCH                1527
#define IDS_PROC_SELECTION_HISTORY      1527
#define IDC_EDIT_BRANCH                 1528
#define IDS_ERR_SSL_VALIDATE            1528
#define IDC_SHOWLOCKEDOVERLAY           1529
#define IDS_ANNOTATEDTAGS               1529
#define IDC_EDIT_ORIGIN                 1530
#define IDS_ALLTAGS                     1530
#define IDC_CHECK_ORIGIN                1531
#define IDS_ALLREFS                     1531
#define IDC_RADIO_SINCE                 1532
#define IDS_SETTINGS_SHOWDESCRIBE_TT    1532
#define IDC_COMBOBOXEX_SINCE            1533
#define IDS_SETTINGS_DESCRIBESTRATEGY_TT 1533
#define IDC_RADIO_NUM                   1534
#define IDS_SETTINGS_DESCRIBEABBREVIATEDSIZE_TT 1534
#define IDC_RADIO_RANGE                 1535
#define IDS_SETTINGS_DESCRIBEALWAYSLONG_TT 1535
#define IDC_ONLYNONELEVATED             1536
#define IDC_SPIN_NUM                    1536
#define IDS_SETTINGS_ASTERISKLOGPREFIX_TT 1536
#define IDC_COMBOBOXEX_DIR              1537
#define IDS_SUBMODULEDIFF_IDENTICAL     1537
#define IDC_GROUP_DIR                   1538
#define IDS_SMTP_CONFIGURED             1538
#define IDC_GROUP_VERSION               1539
#define IDS_ENCRYPT_NONE                1539
#define IDC_EDIT_NUM                    1540
#define IDS_ENCRYPT_STARTTLS            1540
#define IDC_BUTTON_FROM                 1541
#define IDS_ENCRYPT_SSL                 1541
#define IDC_CURRENT_BRANCH              1542
#define IDC_BUTTON_REF                  1542
#define IDC_REGEDT                      1542
#define IDS_COMMIT_MESSAGEONLY_TT       1542
#define IDC_LOCAL_BRANCH                1543
#define IDS_DISABLEUPDATECHECKSBUTTON   1543
#define IDC_LOCAL_BRANCHES              1543
#define IDC_COLOR_LINE5                 1544
#define IDS_DISABLEUPDATECHECKS         1544
#define IDC_COLOR_LINE6                 1545
#define IDS_SETTINGS_DELFILE            1545
#define IDC_COLOR_LINE1                 1546
#define IDS_REMINDMELATER               1546
#define IDC_COLOR_LINE2                 1547
#define IDS_SETTINGS_DELCACHE           1547
#define IDC_COLOR_LINE3                 1548
#define IDC_LOGMINSIZE                  1548
#define IDS_STATUSLIST_CONTEXT_SHELL    1548
#define IDC_COLOR_LINE4                 1549
#define IDC_SHOWADDEDOVERLAY            1549
#define IDS_PREPAREDIFF                 1549
#define IDC_SHOWREADONLYOVERLAY         1550
#define IDC_MSYSGIT_PATH                1550
#define IDS_PROC_RENAME                 1550
#define IDC_RADIO_RESET_SOFT            1550
#define IDC_RADIO_RESET_MERGE           1550
#define IDC_SHOWDELETEDOVERLAY          1551
#define IDC_MSYSGIT_BROWSE              1551
#define IDS_PROC_NEWNAME                1551
#define IDC_RADIO_RESET_MIXED           1551
#define IDC_BORDER                      1551
#define IDC_KEEPFILELISTSENGLISH        1552
#define IDC_MSYSGIT_VER                 1552
#define IDS_PROC_NEWNAMECOPY            1552
#define IDC_RADIO_RESET_HARD            1552
#define IDS_PROC_NEWNAMEMOVE            1553
#define IDS_PROC_NEWNAMELABEL           1554
#define IDC_GROUP_RESET_TYPE            1554
#define IDC_COMMIT_AMEND                1555
#define IDS_COMMIT_AS_COMMIT_DATE_TT    1555
#define IDC_COMMIT_AMENDDIFF            1556
#define IDS_REBASE_ADDANOTHERCOMMIT     1556
#define IDC_REBASE_PROGRESS             1557
#define IDC_COMMIT_SETDATETIME          1557
#define IDS_PROC_LOG_ONLYONCE           1557
#define IDC_COMMIT_SETAUTHOR            1558
#define IDS_PROC_BROWSEREFS_DROPTRACKEDBRANCH 1558
#define IDC_SPLITALLOPTIONS             1559
#define IDS_PROC_BROWSEREFS_SETTRACKEDBRANCH 1559
#define IDS_PROC_MULTIRENAME            1560
#define IDC_COMMIT_AS_COMMIT_DATE       1561
#define IDS_PROC_REBASE_UNSELECTED_SKIP 1561
#define IDC_REBASE_SPLIT                1562
#define IDS_PROC_REBASE_UNSELECTED_SQUASH 1562
#define IDC_STATUS_STATIC               1563
#define IDS_PROC_REBASE_UNSELECTED_EDIT 1563
#define IDC_REBASE_CONTINUE             1564
#define IDS_DIFFWITHMERGE               1564
#define IDC_REBASE_ABORT                1565
#define IDS_NOCHANGEAFTERMERGE          1565
#define IDC_REBASE_DUMY_TAB             1566
#define IDC_GIT_USERNAME                1566
#define IDS_WARN_DELETE_MANY            1566
#define IDS_WARN_DELETE_MANY_FROM_INDEX 1567
#define IDC_EDIT_URL                    1568
#define IDS_WARN_DELETE_ONE_FROM_INDEX  1568
#define IDC_EDIT_PUTTY_KEY              1569
#define IDC_BUGTRAQLOGREGEX1            1569
#define IDS_REMOVEBUTTON                1569
#define IDC_BUGTRAQLOGREGEX2            1570
#define IDS_LAST_N_WEEKS                1570
#define IDC_PUTTYKEYFILE                1571
#define IDS_LAST_N_MONTHS               1571
#define IDC_GROUP_CLONE                 1572
#define IDS_LAST_N_YEARS                1572
#define IDC_GROUPT_REMOTE               1573
#define IDS_REBASE_BRANCH_UNCHANGED     1573
#define IDS_LAST_N_COMMITS              1574
#define IDC_SENDMAIL_PATCHS             1575
#define IDS_DEFAULT_NUMBER_OF_TT        1575
#define IDS_DEFAULT_SCALE_TT            1576
#define IDC_SENDMAIL_TO                 1577
#define IDS_NO_LIMIT                    1577
#define IDC_COMBOBOXEX_REF              1578
#define IDC_SENDMAIL_CC                 1578
#define IDC_REGEXIDLABEL                1578
#define IDS_LAST_SEL_DATE               1578
#define IDC_STATIC_REF                  1579
#define IDC_SENDMAIL_ATTACHMENT         1579
#define IDC_REGEXMSGLABEL               1579
#define IDS_REBASE_BRANCH_FF            1579
#define IDC_REFLOG_LIST                 1580
#define IDC_SENDMAIL_SETUP              1580
#define IDC_STATIC_REPOURL              1580
#define IDC_IBUGTRAQPROVIDERGROUP       1580
#define IDS_MERGEBUTTON                 1580
#define IDC_COMBOBOXEX_REPOSITORY       1581
#define IDC_UUIDLABEL32                 1581
#define IDS_REBASEBUTTON                1581
#define IDC_COMBOBOXEX_PATH             1582
#define IDC_SENDMAIL_GROUP              1582
#define IDC_UUID32                      1582
#define IDS_RESTORE_FROM_INDEX          1582
#define IDC_REP_BROWSE                  1583
#define IDC_SEND_ADDRESS                1583
#define IDC_UUIDLABEL64                 1583
#define IDS_LOCAL_GCM                   1583
#define IDC_BUTTON_PATH_BROWSE          1584
#define IDC_SMTP_SERVER                 1584
#define IDC_UUID64                      1584
#define IDS_GLOBAL_GCM                  1584
#define IDC_GROUP_SUBMODULE             1585
#define IDC_SMTP_AUTH                   1585
#define IDC_PARAMS                      1585
#define IDS_SYSTEM_GCM                  1585
#define IDC_BRANCH_CHECK                1586
#define IDC_SMTP_USER                   1586
#define IDC_PARAMSLABEL                 1586
#define IDS_COMMIT_MERGE_HINT           1586
#define IDC_SUBMODULE_BRANCH            1587
#define IDC_CHECK_SENDMAIL              1587
#define IDS_REBASE_PRESERVEMERGES_TT    1587
#define IDD_REFLOG                      1588
#define IDC_TREE_REF                    1588
#define IDS_PROC_LOG_BASIC_REFS         1588
#define IDC_CHECK_NOPREFIX              1588
#define IDD_SUBMODULE_ADD               1589
#define IDC_EDIT_NAME                   1589
#define IDS_PROC_LOG_SELECT_BASIC_REFS  1589
#define IDS_CHERRYPICK_MERGECOMMIT      1590
#define IDS_COMMIT_COMMIT               1591
#define IDS_COMMIT_RECOMMIT             1592
#define IDC_BUGTRAQ_WARNINGIFNOISSUE    1593
#define IDS_COMMIT_COMMITPUSH           1593
#define IDC_BUGTRAQ_APPEND              1594
#define IDC_WARN_NO_SIGNED_OFF_BY       1594
#define IDS_DROPONESTASH                1594
#define IDC_BUGTRAQ_NUMBER              1595
#define IDS_PROC_PULL_EMPTYBRANCH       1595
#define IDS_PROC_SYNC_FETCHALL          1596
#define IDS_NOTYET_SETTRACKEDBRANCH     1597
#define IDS_PROC_DIFF_BASE              1598
#define IDC_BUGTRAQ_URL                 1599
#define IDS_REMOVESTALEBUTTON           1599
#define IDS_REPOBROWSE_SAVEAS           1600
#define IDC_BUGTRAQ_MESSAGE             1600
#define IDS_REPOBROWSE_SHOWLOG          1601
#define IDS_REPOBROWSE_OPEN             1602
#define IDC_CHECK_REBASE                1602
#define IDC_LANGCOMBO                   1602
#define IDC_CLONE_GROUP_SVN             1603
#define IDC_CHECK_PRUNE                 1603
#define IDS_REBASELOCKFILEFOUND         1603
#define IDC_CHECK_SVN                   1604
#define IDS_ERR_MUSTBESAMEWT            1604
#define IDC_CHECK_SVN_TRUNK             1605
#define IDS_MERGE_UNRELATED             1605
#define IDC_EDIT_SVN_TRUNK              1606
#define IDS_HOOKTYPE_PREREBASE          1606
#define IDC_REBASE_CHECK_FORCE          1607
#define IDC_EDIT_DEPTH                  1607
#define IDS_BROWSE_REFS_ONLYMERGED      1607
#define IDC_CHECK_SVN_FROM              1608
#define IDC_REBASE_CHECK_PRESERVEMERGES 1608
#define IDS_BROWSE_REFS_ONLYUNMERGED    1608
#define IDC_HANDLERHINT                 1609
#define IDS_ARCHIVEFILEFILTER           1609
#define IDC_COMBOBOXEX_URL              1610
#define IDS_PROC_USELFS_TT              1610
#define IDC_BUTTON_PULL                 1611
#define IDS_EXTRAPATH_TT                1611
#define IDC_BUTTON_PUSH                 1612
#define IDC_SAMPLELABEL                 1612
#define IDS_FIRSTSTART_HINT1            1612
#define IDC_BUTTON_APPLY                1613
#define IDS_FIRSTSTART_HINT2            1613
#define IDC_BUTTON_EMAIL                1614
#define IDS_FIRSTSTART_HINT3            1614
#define IDS_FIRSTSTART_HINT4            1615
#define IDC_STATIC_LOCAL_BRANCH         1616
#define IDS_FIRSTSTART_STARTTITLE       1616
#define IDC_STATIC_REMOTE_BRANCH        1617
#define IDS_FIRSTSTART_GITTITLE         1617
#define IDC_STATIC_REMOTE_URL           1618
#define IDS_FIRSTSTART_USERTITLE        1618
#define IDC_CHECK_PUTTY_KEY             1619
#define IDS_SEEMANUALGITEXEPATH         1619
#define IDS_ERR_GITDLLMISSING           1620
#define IDC_STATIC_STATUS               1621
#define IDS_ERR_GITNOVALIDOUTPUT        1621
#define IDC_PROGRESS_SYNC               1622
#define IDS_ERR_GITNEEDHACKS            1622
#define IDC_ANIMATE_SYNC                1623
#define IDS_ERR_GITUNNEEDEDHACKS        1623
#define IDC_GROUP_INFO                  1624
#define IDS_ERR_GITCALLFAILED           1624
#define IDC_BUTTON_COMMIT               1625
#define IDS_GITEXEFILEFILTER            1625
#define IDC_CHECK_DIR                   1626
#define IDS_REALLYCANCEL                1626
#define IDC_RADIO_CLEAN_ALL             1627
#define IDS_HINTLASTMESSAGES            1627
#define IDC_RADIO_CLEAN_NO              1628
#define IDS_FIRSTSTART_AUTHENTICATIONTITLE 1628
#define IDC_RADIO_CLEAN_IGNORE          1629
#define IDS_FIRSTSTART_SSHHINT          1629
#define IDC_GROUP_CLEAN_TYPE            1630
#define IDS_FIRSTSTART_LANGUAGEHINT1    1630
#define IDC_CHECK_AUTOCRLF              1631
#define IDS_FIRSTSTART_LANGUAGEHINT2    1631
#define IDC_CHECK_DIR_UNMANAGEDREPO     1631
#define IDC_COMBO_SAFECRLF              1632
#define IDS_FIRSTSTART_LANGUAGEHINT3    1632
#define IDC_CHECK_QUOTEPATH             1633
#define IDS_PROC_LOG_SHOWUNVERSIONED    1633
#define IDS_STATUSLIST_CONTEXT_COPYFILENAMES 1634
#define IDC_STATIC_MERGE_MESSAGE        1635
#define IDS_STATUSLIST_CONTEXT_COPYCOL  1635
#define IDC_PATCH                       1636
#define IDS_STATUSLIST_CONTEXT_COPYRELPATHS 1636
#define IDC_VIEW_PATCH                  1637
#define IDS_PROC_PUSH_ALLBRANCHES       1637
#define IDS_CONFLICT_NOSUBMODULE        1638
#define IDC_BUTTON_SUBMODULE            1639
#define IDS_CONFLICT_SUBMODULENOTINITIALIZED 1639
#define IDC_RADIO_EXCLUDE               1640
#define IDS_CONFLICT_REFTOBEMERGED      1640
#define IDC_RADIO_GITIGNORE             1641
#define IDS_CONFLICT_REVERT             1641
#define IDC_GROUP_TYPE                  1642
#define IDS_CONFLICT_INFOTEXT           1642
#define IDC_REV1EDIT                    1643
#define IDS_SVNPROGRESS_MENURESOLVEUSING 1643
#define IDC_REV1GROUP                   1644
#define IDS_PROC_SYNC_COMPARETAGS       1644
#define IDC_REV2GROUP                   1645
#define IDS_TAGCOMPARE_SAME             1645
#define IDC_CHECK_DEPTH                 1646
#define IDS_TAGCOMPARE_ONLYLOCAL        1646
#define IDC_EDIT_MESSAGE                1647
#define IDS_TAGCOMPARE_ONLYREMOTE       1647
#define IDC_GROUP_MESSAGE               1648
#define IDS_TAGCOMPARE_DIFFER           1648
#define IDC_STATIC_REMINDER             1649
#define IDS_TAGCOMPARE_LOCALHASH        1649
#define IDC_CHECK_USERNAME              1650
#define IDS_TAGCOMPARE_LOCALMESSAGE     1650
#define IDC_EDIT_USERNAME               1651
#define IDS_TAGCOMPARE_REMOTEHASH       1651
#define IDC_MSYSGIT_EXTERN_PATH         1652
#define IDS_TAGCOMPARE_REMOTEMESSAGE    1652
#define IDC_CHECK_BARE                  1653
#define IDS_DELETE_REMOTETAG            1653
#define IDC_INIT_REPO_DESC              1654
#define IDC_CHECK_RECURSIVE             1654
#define IDS_DELETE_LOCALTAG             1654
#define IDS_CONFLICT_NOTASUBMODULE      1655
#define IDC_CHECK_3WAY                  1656
#define IDS_REBASE_CURRENTBRANCHUPTODATE 1656
#define IDC_CHECK_IGNORE_SPACE          1657
#define IDS_GITCONFIG_SETTING           1657
#define IDC_AM_SPLIT                    1658
#define IDS_SETTINGS_GITCONFIG_INHERIT_TT 1658
#define IDC_AM_DUMY_TAB                 1659
#define IDS_PROC_REMOTEBRANCH           1659
#define IDC_REMEMBER                    1660
#define IDC_HIDEMENUS                   1660
#define IDS_VIEW_SHOWROTHERLABELS       1660
#define IDC_ALTERNATIVEEDITOR_OFF       1661
#define IDS_CONFLICT_HINT_IN_COMMIT_MESSAGE 1661
#define IDC_ALTERNATIVEEDITOR_ON        1662
#define IDS_NEED_TO_RESOLVE_CONFLICTS_HINT 1662
#define IDC_ALTERNATIVEEDITOR           1663
#define IDS_STATUSLIST_CONTEXT_ADD_EXE  1663
#define IDC_ALTERNATIVEEDITORBROWSE     1664
#define IDS_STATUSLIST_CONTEXT_ADD_LINK 1664
#define IDS_CHERRYPICK_EMPTY            1665
#define IDS_NOGITREPO                   1666
#define IDC_NOAUTOSELECTSUBMODULES      1669
#define IDC_COMMIT_DATEPICKER           1670
#define IDC_COMMIT_TIMEPICKER           1671
#define IDC_COMBOBOXEX_GOOD             1671
#define IDC_BUTTON_GOOD                 1672
#define IDC_GROUP_STASHMESSAGE          1673
#define IDC_STASHMESSAGE                1674
#define IDC_FOLLOWRENAMES               1675
#define IDC_TOGROUP                     1676
#define IDC_IGNORE_WHITESPACE           1676
#define IDC_FROMHASH                    1677
#define IDC_BLAME_ONLYFIRSTPARENT       1677
#define IDC_FROMSUBJECT                 1678
#define IDC_TOHASH                      1679
#define IDC_TOSUBJECT                   1680
#define IDC_CHECK_NEWBRANCH             1681
#define IDC_TOGROUP2                    1681
#define IDC_CHECK_CHERRYPICKED_FROM     1682
#define IDC_THEIRSHASH                  1682
#define IDC_CREATELIB                   1683
#define IDC_THEIRSSUBJECT               1683
#define IDC_BUTTON_REVISION             1684
#define IDC_RUNFIRSTSTARTWIZARD         1684
#define IDC_REPOBROWSER_URL             1685
#define IDC_REFLOG_BUTTONCLEARSTASH     1686
#define IDC_GROUP_IGNORE_TYPE           1686
#define IDC_RADIO_IGNORETYPE_ONLYINFOLDER 1687
#define IDC_SEARCH                      1687
#define IDC_RADIO_IGNORETYPE_RECURSIVELY 1688
#define IDC_RADIO_IGNOREFILE_GLOBALGITIGNORE 1689
#define IDC_RADIO_IGNOREFILE_LOCALGITIGNORES 1690
#define IDC_RADIO_IGNOREFILE_GITINFOEXCLUDE 1691
#define IDC_GROUP_IGNORE_FILE           1692
#define IDC_CHECK_SUBMODULE_INIT        1693
#define IDC_CHECK_SUBMODULE_RECURSIVE   1694
#define IDC_LOG2                        1695
#define IDC_LIST_TAGS                   1696
#define IDC_SHOW_DIFF                   1696
#define IDC_GROUP_CHANGELOG             1697
#define IDC_GROUP_DOWNLOADS             1698
#define IDC_LOG3                        1698
#define IDC_SELECTLABEL                 1700
#define IDS_ABOUTVERSION                1700
#define IDC_CHECKALL                    1701
#define IDS_ABOUTVERSIONBOX             1701
#define IDC_CHECKNONE                   1702
#define IDC_CHECKUNVERSIONED            1703
#define IDC_CHECKVERSIONED              1704
#define IDC_CHECKADDED                  1705
#define IDC_CHECKMODIFIED               1706
#define IDC_CHECKFILES                  1707
#define IDC_CHECKSUBMODULES             1708
#define IDC_CHECKDELETED                1709
#define IDC_BUTTON_UPDATE               1710
#define IDC_LIST_DOWNLOADS              1711
#define IDC_STATIC_REVISION             1712
#define IDC_STATIC_REVISION2            1713
#define IDC_STATIC_SUBJECT              1714
#define IDC_STATIC_SUBJECT2             1715
#define IDC_CHECK_NOCHECKOUT            1716
#define IDC_STATIC_REVISION3            1716
#define IDC_VIEWSYSTEMGITCONFIG         1717
#define IDC_STATIC_SUBJECT3             1717
#define IDC_EDITGLOBALXDGGITCONFIG      1718
#define IDC_COMMIT_MESSAGEONLY          1719
#define IDC_STATIC_CHANGETYPE           1720
#define IDC_CHANGETYPE                  1721
#define IDC_GROUP                       1722
#define IDC_STATIC_CHANGETYPE2          1722
#define IDC_LOG_JUMPTYPE                1723
#define IDC_THEIRSCHANGETYPE            1723
#define IDC_LOG_JUMPUP                  1724
#define IDC_LOG_JUMPDOWN                1725
#define IDC_TEMPFILESCLEAR              1726
#define IDC_STATIC_TAGOPT               1727
#define IDC_STOREDDECISIONSCLEAR        1727
#define IDC_COMBO_TAGOPT                1728
#define IDC_REV1BTN1                    1729
#define IDC_CHECK_NORECYCLEBIN          1730
#define IDC_CHECK_DRYRUN                1731
#define IDC_SYMBOLIZEREFNAMES           1733
#define IDC_CHECK_SUBMODULE_NOFETCH     1734
#define IDC_CHECK_SUBMODULE_MERGE       1735
#define IDC_CHECK_SUBMODULE_REBASE      1736
#define IDC_TOTAL_LINE_WITHOUT_NEW_DEL  1737
#define IDC_TOTAL_LINE_WITHOUT_NEW_DEL_VALUE 1738
#define IDC_TOTAL_LINE_WITH_NEW_DEL     1739
#define IDC_TOTAL_LINE_WITH_NEW_DEL_VALUE 1740
#define IDC_CALC_DIFF                   1741
#define IDC_CHECK_MERGE_LOG             1742
#define IDC_EDIT_MERGE_LOGNUM           1743
#define IDC_ENABLELOGCACHE              1744
#define IDC_COMBO_MERGESTRATEGY         1745
#define IDC_COMBO_STRATEGYOPTION        1746
#define IDC_EDIT_STRATEGYPARAM          1747
#define IDC_LIST_PATH                   1748
#define IDC_PROG_LABEL                  1749
#define IDS_DLGTITLE_ADD_DIFF_TOOL      1750
#define IDC_STATIC_ORDER                1750
#define IDS_DLGTITLE_ADD_MERGE_TOOL     1751
#define IDC_COMBOBOXEX_ORDERING         1751
#define IDC_COMBO_SIMPLECREDENTIAL      1752
#define IDS_DLGTITLE_EDIT_DIFF_TOOL     1752
#define IDS_DLGTITLE_EDIT_MERGE_TOOL    1753
#define IDC_BUTTON_RENAME_REMOTE        1753
#define IDC_COMBO_SSHCLIENT             1753
#define IDS_DLGTITLE_ADV_DIFF           1754
#define IDC_CHECK_SUBMODULE_REMOTE      1754
#define IDC_SMTPDELIVERYCOMBO           1754
#define IDS_DLGTITLE_ADV_MERGE          1755
#define IDC_EDITTGITCONFIG              1755
#define IDC_SMTPENCRYPTIONCOMBO         1756
#define IDS_REVGRAPH_POPUP_COMPAREREVS  1757
#define IDC_STATIC_SMTPSERVER           1757
#define IDS_REVGRAPH_POPUP_UNIDIFFREVS  1758
#define IDC_STATIC_SMTPPORT             1758
#define IDC_COMBO_CONFIGTYPE            1759
#define IDC_STATIC_SMTPENCRYPTION       1759
#define IDC_COMBO_HELPER                1760
#define IDC_STATIC_SMTPLOGIN            1760
#define IDC_CHECK_USEHTTPPATH           1761
#define IDC_STATIC_SMTPPASSWORD         1761
#define IDC_REVGRAPHUSELOCALFORCUR      1762
#define IDC_LOGGRAPHLINEWIDTH           1763
#define IDC_LOGGRAPHNODESIZE            1764
#define IDC_PIC_AUTHOR                  1765
#define IDC_ENABLEGRAVATAR              1766
#define IDC_GRAVATARURL                 1767
#define IDC_CONFIRMKILLPROCESS          1768
#define IDC_SYNCDIALOGRANDOMPOS         1769
#define IDC_RADIO_SETTINGS_EFFECTIVE    1770
#define IDC_RADIO_SETTINGS_LOCAL        1771
#define IDC_RADIO_SETTINGS_PROJECT      1772
#define IDC_RADIO_SETTINGS_GLOBAL       1773
#define IDC_RADIO_SETTINGS_SYSTEM       1774
#define IDC_COMBO_SETTINGS_SAFETO       1775
#define IDC_WALKBEHAVIOUR               1776
#define IDC_VIEW                        1777
#define IDC_ICONFILE_BROWSE             1778
#define IDC_ICONFILE                    1779
#define IDC_CHECK_INHERIT_NAME          1780
#define IDC_CHECK_INHERIT_LIMIT         1780
#define IDC_CHECK_INHERIT_BTREGEXP      1780
#define IDC_CHECK_INHERIT_EMAIL         1781
#define IDC_CHECK_INHERIT_BORDER        1781
#define IDC_CHECK_INHERIT_BTURL         1781
#define IDC_REFCOMPAREHIDEUNCHANGED     1781
#define IDC_CHECK_INHERIT_KEYID         1782
#define IDC_CHECK_INHERIT_ICONPATH      1782
#define IDC_CHECK_INHERIT_BTMSG         1782
#define IDC_PROGRESSDLG_SHOW_TIMES      1782
#define IDC_CHECK_INHERIT_BTLABEL       1783
#define IDC_CURRENTBRANCH               1784
#define IDC_CHECK_PRUNEALL              1785
#define IDC_CHECK_PUSHDEFAULT           1786
#define IDC_TESTBUGTRAQREGEXBUTTON      1787
#define IDC_ENABLEDRAGCONTEXTMENU       1788
#define IDC_DIFFOPTION                  1789
#define IDC_BUTTON_REVERSE              1790
#define IDC_CHECK_INHERIT_BTUUID32      1791
#define IDC_CHECK_INHERIT_BTUUID64      1792
#define IDC_CHECK_INHERIT_BTPARAMS      1793
#define IDC_EDIT_PUSHURL                1794
#define IDC_SORTTAGSREVERSED            1795
#define IDC_STATIC_FORCE                1796
#define IDC_NOSOUNDS                    1796
#define IDC_OPENCERT                    1797
#define IDC_BRANCHESINCLUDEFETCHHEAD    1797
#define IDC_ERRORDESC                   1798
#define IDC_ERROR                       1799
#define IDC_SHA1                        1800
#define IDC_SHA256                      1801
#define IDC_ISSUER                      1802
#define IDC_COMMONNAME                  1803
#define IDC_SHOWDESCRIBE                1804
#define IDC_DESCRIBEALWAYSLONG          1805
#define IDC_DESCRIBESTRATEGY            1806
#define IDC_DESCRIBEABBREVIATEDSIZE     1807
#define IDC_FORECOMMANDCOLOR            1808
#define IDC_DESCRIBEONLYFIRSTPARENT     1808
#define IDC_BACKCOMMANDCOLOR            1809
#define IDC_FOREPOSITIONCOLOR           1810
#define IDC_BACKPOSITIONCOLOR           1811
#define IDC_FOREHEADERCOLOR             1812
#define IDC_BACKHEADERCOLOR             1813
#define IDC_FORECOMMENTCOLOR            1814
#define IDC_BACKCOMMENTCOLOR            1815
#define IDC_FOREADDEDCOLOR              1816
#define IDC_BACKADDEDCOLOR              1817
#define IDC_FOREREMOVEDCOLOR            1818
#define IDC_BACKREMOVEDCOLOR            1819
#define IDC_BASEHASH                    1820
#define IDC_BASESUBJECT                 1821
#define IDC_MINECHANGETYPE              1822
#define IDC_MINEHASH                    1823
#define IDC_MINESUBJECT                 1824
#define IDC_BUTTON_UPDATE2              1825
#define IDC_BUTTON_UPDATE3              1826
#define IDC_REBASE_SPLIT_COMMIT         1827
#define IDC_BUTTON_ONTO                 1828
#define IDC_STATIC_AUTHORS              1829
#define IDC_INCLUDENESTEDREFS           1830
#define IDC_DEFAULT_NUMBER_OF           1831
#define IDC_DEFAULT_SCALE               1832
#define IDC_STOREDDECISIONS             1833
#define IDC_LABEL_FILTER                1834
#define IDC_SELREF                      1835
#define IDC_BROWSE_REFS_BRANCHFILTER    1838
#define IDC_DONTSAVE                    1839
#define IDC_FIRSTSTART_HINT             1840
#define IDC_WORKAROUNDS                 1841
#define IDC_GITHACKS1                   1842
#define IDC_GITHACKS2                   1843
#define IDC_GENERATEPUTTYKEY            1844
#define IDC_ADVANCEDCONFIGURATION       1845
#define IDC_FIRSTSTART_SSHHINT          1846
#define IDC_CHECK_LFS                   1847
#define IDC_LOCALCHECK                  1848
#define IDC_CLEARCREDENTIALS            1848
#define IDC_STORECREDENTIALS            1849
#define IDC_OPENSETTINGSELEVATED        1849
#define IDS_LOG_FILTER_BY               1850
#define IDC_STATICELEVATIONNEEDED       1850
#define IDS_LOG_FILTER_PATHS            1851
#define IDS_LOG_FILTER_AUTHORS          1852
#define IDS_LOG_FILTER_MESSAGES         1853
#define IDS_LOG_FILTER_REVS             1854
#define IDS_LOG_FILTER_REGEX            1855
#define IDS_LOG_FILTER_BUGIDS           1856
#define IDS_LOG_FILTER_CASESENSITIVE    1857
#define IDS_LOG_FILTER_REGEX_TT         1860
#define IDS_LOG_REVERTTOREV_CONFIRM     1890
#define IDS_LOG_REVERTREV_ERROR         1891
#define IDS_LOG_STOPONCOPY_HINT         1892
#define IDS_LOG_SAVEFOLDERTOHINT        1893
#define IDS_LOG_MERGETO                 1894
#define IDS_LOG_SHOW_FIRST_PARENT       1897
#define IDS_COMMIT_AMEND_TT             1899
#define IDS_PROGRESSGETFILE             1900
#define IDS_PROGRESSREVISION            1901
#define IDS_PROGRESSWAIT                1902
#define IDS_PROGRESS_UNIFIEDDIFF        1903
#define IDS_PROGRESS_INFO               1905
#define IDS_PROGRESSIMPORT              1907
#define IDS_PROGRESSREVISIONTEXT        1908
#define IDC_STATIC_PRUNE                1909
#define IDC_SHOWREVCOUNTER              1910
#define IDS_SETTINGS_SHOWREVCOUNTER_TT  1911
#define IDC_USEMAILMAP                  1911
#define IDS_INPUT_REMOVEONE             2014
#define IDS_INPUT_REMOVEMORE            2015
#define IDS_MENUREFRESH                 2150
#define IDC_RADIO_SVN_COMMIT            2152
#define IDC_RADIO_GIT_COMMIT            2153
#define IDS_LOG_COMPAREWITHBASE         2200
#define IDS_PROC_CLEANUP                2304
#define IDS_PROC_REMOVEFORCE            2305
#define IDS_PROC_YESTOALL               2306
#define IDS_PROC_IGNORESUCCESS          2307
#define IDS_PROC_RESOLVE                2308
#define IDS_PROC_RTFM                   2309
#define IDS_PROC_CASERENAME             2310
#define IDS_PROC_UnIGNORESUCCESS        2311
#define IDS_PROC_UNIGNORESUCCESS        2311
#define IDS_PROC_FORCEMOVE              2312
#define IDS_PROC_ICONCACHEREBUILT       2314
#define IDS_PROC_ICONCACHENOTREBUILT    2315
#define IDS_PROC_REMOVEFORCEFOLDER      2318
#define IDS_PROC_CLEANUP_INFO1          2332
#define IDS_PROC_CLEANUP_INFO2          2333
#define IDS_PROC_COPYRENAME             2335
#define IDS_PROC_MOVERENAME             2336
#define IDS_DIFF_WCNAME                 2400
#define IDS_COMMONFILEFILTER            2500
#define IDS_PROGRAMSFILEFILTER          2501
#define IDS_PATCHFILEFILTER             2503
#define IDS_PICTUREFILEFILTER           2504
#define IDS_STATPICFILEFILTER           2505
#define IDS_TEXTFILEFILTER              2506
#define IDS_CHECKUPDATE_SUMMARY         2600
#define IDS_COMMITDLG_STATISTICSFORMAT  2701
#define IDS_COMMITDLG_ONLYNUMBERS       2702
#define IDS_COMMITDLG_NOISSUEWARNING    2703
#define IDS_COMMITDLG_NOTHINGTOCOMMITUNVERSIONED 2704
#define IDS_COMMITDLG_HISTORY_TT        2705
#define IDS_COMMITDLG_HISTORYHINT_TT    2706
#define IDS_COMMITDLG_UNVERSIONEDFOLDERWARNING 2707
#define IDS_COMMITDLG_NOMESSAGE         2708
#define IDS_COMMITDLG_SUBMODULEDIRTY    2709
#define IDS_COMMITDLG_POPUP_PASTEFILELIST 2750
#define IDS_COMMITDLG_POPUP_PASTELASTMESSAGE 2751
#define IDC_NOCONTEXTPATHS              2752
#define IDS_SETTINGS_EXTMENULAYOUT_TT   2753
#define IDS_REVGRAPH_ERR_NOGRAPH        2754
#define IDS_SETTINGS_CHECKNEWER_TT      3100
#define IDS_SETTINGS_ONLYEXPLORER_TT    3101
#define IDS_SETTINGS_MENULAYOUT_TT      3102
#define IDS_SETTINGS_EXCLUDELIST_TT     3103
#define IDS_SETTINGS_INCLUDELIST_TT     3104
#define IDS_SETTINGS_CLEARAUTH_TT       3105
#define IDS_SETTINGS_ONLYNONELEVATED_TT 3106
#define IDS_SETTINGS_READONLYNAME       3110
#define IDS_SETTINGS_LOCKEDNAME         3111
#define IDS_SETTINGS_AUTOCOMPLETION_TT  3114
#define IDS_SETTINGS_AUTOCOMPLETIONTIMEOUT_TT 3115
#define IDS_SETTINGS_RECURSIVE_TT       3116
#define IDS_SETTINGS_UNVERSIONEDRECURSE_TT 3121
#define IDS_SETTINGS_MAXHISTORY_TT      3122
#define IDS_SETTINGS_CACHEDEFAULT_TT    3123
#define IDS_SETTINGS_CACHESHELL_TT      3124
#define IDS_SETTINGS_CACHENONE_TT       3125
#define IDS_SETTINGS_SAVEDDATA_LOGHIST_TT 3126
#define IDS_SETTINGS_SAVEDDATA_URLHIST_TT 3127
#define IDS_SETTINGS_SAVEDDATA_RESIZABLE_TT 3128
#define IDS_SETTINGS_SAVEDDATA_AUTH_TT  3129
#define IDS_SETTINGS_RESTARTSYSTEM      3131
#define IDS_SETTINGS_UNVERSIONEDASMODIFIED_TT 3133
#define IDS_SETTINGS_COMMITREOPEN_TT    3134
#define IDS_SETTINGS_SHOWEXCLUDEDASNORMAL_TT 3138
#define IDS_SETTINGS_SAVEDDATA_REPOLOGHIST_TT 3139
#define IDS_SETTINGS_SELECTFILESONCOMMIT_TT 3141
#define IDS_SETTINGS_DIFFBYDOUBLECLICK_TT 3142
#define IDS_SETTINGS_USESYSTEMLOCALEFORDATES_TT 3143
#define IDS_SETTINGS_USERECYCLEBIN_TT   3144
#define IDS_SETTINGS_EXCLUDECONTEXTLIST_TT 3145
#define IDS_SETTINGS_CACHESHELLEXT_TT   3146
#define IDS_SETTINGS_HOOKS_SELECTFOLDERPATH 3150
#define IDS_SETTINGS_HOOKS_SELECTSCRIPTFILE 3151
#define IDS_SETTINGS_HOOKS_TYPECOL      3152
#define IDS_SETTINGS_HOOKS_PATHCOL      3153
#define IDS_SETTINGS_HOOKS_COMMANDLINECOL 3154
#define IDS_SETTINGS_HOOKS_WAITCOL      3155
#define IDS_SETTINGS_HOOKS_SHOWCOL      3156
#define IDS_SETTINGS_SHOWACTIONLOG_TT   3158
#define IDS_SETTINGS_CLEARACTIONLOG_TT  3159
#define IDS_SETTINGS_MAXACTIONLOGLINES_TT 3160
#define IDS_SETTINGS_HIDEMENUS_TT       3161
#define IDS_SETTINGS_OVERLAYINFO        3162
#define IDS_SETTINGS_OVERLAYINFO2       3163
#define IDS_CHECKNEWER_YOURVERSION      3200
#define IDS_CHECKNEWER_CURRENTVERSION   3201
#define IDS_CHECKNEWER_YOURUPTODATE     3202
#define IDS_CHECKNEWER_NEWERVERSIONAVAILABLE 3203
#define IDS_CHECKNEWER_NETERROR         3204
#define IDS_STATUSLIST_COLFILE          3300
#define IDS_STATUSLIST_COLSTATUS        3301
#define IDS_STATUSLIST_COLURL           3307
#define IDS_STATUSLIST_COLEXT           3308
#define IDS_STATUSLIST_COLAUTHOR        3311
#define IDS_STATUSLIST_COLDATE          3312
#define IDS_STATUSLIST_COLREVISION      3313
#define IDS_STATUSLIST_COLMODIFICATIONDATE 3316
#define IDS_STATUSLIST_COLFILENAME      3317
#define IDS_STATUSLIST_SWITCHEDTO       3323
#define IDS_STATUSLIST_CONTEXT_ADD      3330
#define IDS_STATUSLIST_CONTEXT_EXPLORE  3331
#define IDS_STATUSLIST_CONTEXT_RESOLVED 3332
#define IDS_STATUSLIST_CONTEXT_COMMIT   3333
#define IDS_STATUSLIST_CONTEXT_COPY     3335
#define IDS_STATUSLIST_CONTEXT_COPYEXT  3336
#define IDS_STATUSLIST_CONTEXT_REMOVEFROMCS 3338
#define IDS_STATUSLIST_CONTEXT_CREATECS 3339
#define IDS_STATUSLIST_CONTEXT_MOVETOCS 3340
#define IDS_STATUSLIST_CONTEXT_ADD_RECURSIVE 3341
#define IDS_STATUSLIST_NESTED           3402
#define IDS_STATUSLIST_BUSYMSG          3403
#define IDS_STATUSLIST_EMPTYMSG         3404
#define IDS_STATUSLIST_UNASSIGNED_CHANGESET 3405
#define IDS_STATUSLIST_CHECKGROUP       3406
#define IDS_STATUSLIST_UNCHECKGROUP     3407
#define IDS_STATUSLIST_KEEPLOCAL        3409
#define IDS_STATUSLIST_NOPROPVALUE      3412
#define IDS_PROGRS_CONFLICTSOCCURRED_WARNING 3500
#define IDS_PROGRS_CONFLICTSOCCURRED    3501
#define IDS_PROGRS_DRYRUN               3502
#define IDS_PROGRS_FINISHED             3503
#define IDS_PROGRS_TITLEFAILED          3504
#define IDS_PROGRS_INFOFAILED           3505
#define IDS_PROGRS_CMDINFO              3506
#define IDS_PROGRS_INFOGETTINGINFO      3511
#define IDS_PROGRS_TITLE_RENAME         3530
#define IDS_PROGRS_TITLE_MERGEREINTEGRATE 3533
#define IDS_PROGRS_CLOSE_MANUAL         3540
#define IDS_PROGRS_CLOSE_NOERROR        3541
#define IDS_PROGRS_CLOSE_NOCONFLICTS    3542
#define IDS_PROGRS_CLOSE_NOMERGES       3543
#define IDS_PROGRS_CLOSE_NOPTIONS       3544
#define IDS_PROGRS_PATHATREV            3600
#define IDS_PROGRS_TIME                 3602
#define IDS_PROGRS_FINALINFO            3603
#define IDS_PROGRS_CMD_CHECKOUT         3650
#define IDS_PROGRS_CMD_IMPORT           3651
#define IDS_PROGRS_CMD_ADD              3657
#define IDS_PROGRS_CMD_COMMIT           3658
#define IDS_PROGRS_CMD_EXPORT           3659
#define IDS_PROGRS_CMD_RENAME           3661
#define IDS_PROGRS_CMD_RESOLVE          3662
#define IDS_PROGRS_CMD_REVERT           3663
#define IDS_REPOSTATUS_EMPTYFILELIST    3810
#define IDS_STATGRAPH_COMMITSBYAUTHOR   3900
#define IDS_STATGRAPH_COMMITSBYDATE     3901
#define IDS_STATGRAPH_COMMITSBYDATEY    3903
#define IDS_STATGRAPH_COMMITSBYAUTHORX  3904
#define IDS_STATGRAPH_COMMITSBYAUTHORY  3905
#define IDS_STATGRAPH_STATS             3906
#define IDS_STATGRAPH_OTHERGROUP        3907
#define IDS_STATGRAPH_EMPTYAUTHOR       3908
#define IDS_STATGRAPH_COMMITSBYDATEXWEEK 3909
#define IDS_STATGRAPH_COMMITSBYDATEXMONTH 3910
#define IDS_STATGRAPH_COMMITSBYDATEXQUARTER 3911
#define IDS_STATGRAPH_COMMITSBYDATEXYEAR 3912
#define IDS_STATGRAPH_PIEBUTTON_TT      3930
#define IDS_STATGRAPH_LINESTACKEDBUTTON_TT 3931
#define IDS_STATGRAPH_LINEBUTTON_TT     3932
#define IDS_STATGRAPH_BARSTACKEDBUTTON_TT 3933
#define IDS_STATGRAPH_BARBUTTON_TT      3934
#define IDS_STATGRAPH_AUTHORSLIDER_TT   3935
#define IDC_LOG_ALLBRANCH               3936
#define IDS_SVNERR_CHECKPATHORURL       4000
#define IDS_SVNERR_CLEANUPORFRESHCHECKOUT 4003
#define IDS_CLIPBOARD_PROGRESS_DEST     4100
#define IDS_SVNACTION_SKIPMISSING       4200
#define IDS_SVNACTION_ADDING            4201
#define IDS_SVNACTION_DELETING          4202
#define IDS_SVNACTION_MERGED            4203
#define IDS_SVNACTION_CONFLICTED        4204
#define IDS_SVNACTION_EXISTS            4209
#define IDS_SVNACTION_CHANGELISTSET     4210
#define IDS_SVNACTION_CHANGELISTCLEAR   4211
#define IDS_SVNACTION_CHANGELISTFAILED  4212
#define IDS_SVNACTION_CHANGELISTMOVED   4215
#define IDS_SVN_SUMMARIZENORMAL         4220
#define IDS_SVN_SUMMARIZEADDED          4221
#define IDS_SVN_SUMMARIZEMODIFIED       4222
#define IDS_SVN_SUMMARIZEDELETED        4223
#define IDS_REVGRAPH_SAVEPIC            4351
#define IDS_REVGRAPH_ERR_GDIINIT        4360
#define IDS_REVGRAPH_ERR_NOBITMAP       4361
#define IDS_REVGRAPH_ERR_NOENCODER      4362
#define IDS_MERGE_RECORDONLY            4403
#define IDS_SVNPROGRESS_MENUOPENPARENT  4502
#define IDS_SVNPROGRESS_MENUMARKASRESOLVED 4503
#define IDS_SVNPROGRESS_RESOLVED        4510
#define IDS_SVNPROGRESS_EXPORTING       4530
#define IDS_SVNPROGRESS_EXPORTINGTO     4531
#define IDS_SVNPROGRESS_EXPORTINGWAIT   4532
#define IDS_SVNPROGRESS_UNVERSION       4563
#define IDC_REBASE_COMBOXEX_UPSTREAM    4564
#define IDC_REBASE_COMBOXEX_BRANCH      4565
#define IDC_REBASE_STATIC_BRANCH        4566
#define IDC_REBASE_STATIC_UPSTREAM      4567
#define IDD_RESOLVE_CONFLICT            4568
#define IDC_MODIFY                      4569
#define IDD_SETTINGIT_CONFIG            4569
#define IDC_DEL_GROUP                   4570
#define IDD_SETTINREMOTE                4570
#define IDC_DELETE                      4571
#define IDD_SETTINGSBUGTRAQ_CONFIG      4571
#define IDC_LOCAL_STATUS                4572
#define IDD_CLEAN                       4572
#define IDC_REMOTE_STATUS               4573
#define IDD_SETTINGSEXTMENU             4573
#define IDD_BISECTSTART                 4574
#define IDD_STASH                       4575
#define IDD_DIFFSUBMODULE               4576
#define IDD_IGNORE                      4577
#define IDD_SUBMODULE_UPDATE            4578
#define IDD_DELETEREMOTETAG             4579
#define IDD_REVISIONGRAPH               4580
#define IDR_REVGRAPHBAR                 4581
#define IDR_REVGRAPHGLYPHS              4582
#define ID_REVGRAPH_ZOOMCOMBO           4583
#define IDD_REVGRAPHFILTER              4584
#define IDC_FROMREV                     4585
#define IDD_USER_PASSWD                 4585
#define IDC_TOREV                       4587
#define IDD_SETTINGSCREDENTIAL          4591
#define IDD_MERGEABORT                  4592
#define IDD_SETTINGSDIALOGS3            4593
#define IDD_CERTCHECK                   4594
#define IDD_RESOLVESUBMODULECONFLICT    4595
#define IDD_COMMITISONREFS              4596
#define IDD_FIRSTSTARTWIZARD_USER       4597
#define IDD_FIRSTSTARTWIZARD_GIT        4598
#define IDD_FIRSTSTARTWIZARD_AUTHENTICATION 4599
#define IDD_FIRSTSTARTWIZARD_LANGUAGE   4600
#define IDC_COMBOBOXEX_LOCAL_BRANCH     5000
#define IDC_COMBOBOXEX_REMOTE_BRANCH    5001
#define IDC_COMBOBOXEX_BAD              5001
#define IDC_LABEL2                      5002
#define IDS_FILEDIFF_FILE               5100
#define IDS_FILEDIFF_ACTION             5101
#define IDS_FILEDIFF_WAIT               5102
#define IDS_FILEDIFF_FILTERCUE          5120
#define IDS_FILEDIFF_POPBLAME           5150
#define IDS_FILEDIFF_POPSAVELIST        5151
#define IDS_FILEDIFF_POPEXPORT          5152
#define IDS_FILEDIFF_POPCLIPBOARD       5153
#define IDS_FILEDIFF_POPREVERTTOREV     5154
#define IDS_FILEDIFF_CHANGEDLISTINTRO   5170
#define IDS_FILEDIFF_CHANGEDLISTINTROROOT 5171
#define IDS_FILEDIFF_SWITCHLEFTRIGHT_TT 5190
#define IDS_SVN_PROGRESS_SPEED          5700
#define IDS_SVN_PROGRESS_TOTALTRANSFERRED 5701
#define IDS_SVN_PROGRESS_TOTALMBTRANSFERRED 5702
#define IDS_SVN_PROGRESS_TOTALANDSPEED  5703
#define IDS_SVN_PROGRESS_TOTALBYTESTRANSFERRED 5704
#define IDS_SETTINGS_CONF_NAMECOL       5707
#define IDS_SETTINGS_CONF_VALUECOL      5708
#define IDS_COLOURPICKER_CUSTOMTEXT     7000
#define IDS_COLOURPICKER_DEFAULTTEXT    7001
#define IDS_ERR_NOTFOUND_SUPER_PRJECT   9031
#define IDS_HOOKTYPE_STARTCOMMIT        9100
#define IDS_HOOKTYPE_PRECOMMIT          9101
#define IDS_HOOKTYPE_POSTCOMMIT         9102
#define IDS_HOOKS_APPROVE_TASK1         9110
#define IDS_HOOKS_APPROVE_TASK2         9111
#define IDS_HOOKS_APPROVE_TASK3         9112
#define IDS_HOOKS_APPROVE_TASK4         9113
#define IDS_HOOKS_APPROVE_TASK5         9114
#define IDS_ERR_HOOKNOTAPPROVED         9115
#define IDS_HOOK_ERRORMSG               9116
#define IDS_HOOK_FORCEDPROCEED          9117
#define IDS_HOOKFAILED_TASK2            9118
#define IDS_HOOKFAILED_TASK3            9119
#define IDS_HOOKFAILED_TASK4            9120
#define IDS_STATUSLIST_COLADD           9603
#define IDS_STATUSLIST_COLDEL           9604
#define IDS_B_T_NOTEMPTY                9619
#define IDS_CHOOSE_REPOSITORY           9621
#define IDS_ERR_NOT_REPOSITORY          9622
#define IDS_ERR_ADDRESS_NO_EMPTY        9623
#define IDS_SVNACTION_SENDMAIL_START    9624
#define IDS_PROGRS_TITLE_SENDMAIL       9625
#define IDS_PROGRS_CMD_SENDMAIL         9626
#define IDS_SVNACTION_SENDMAIL_RETRY    9629
#define IDS_ERR_PAGEANT                 9632
#define IDS_MENU_VIEWPATCH              9633
#define IDS_MENU_VIEWWITHMERGE          9634
#define IDS_MENU_APPLY                  9635
#define IDS_MENU_SENDMAIL               9636
#define IDS_ERROR_NOREF                 9638
#define IDS_ERROR_NOCLEAN_STASH         9641
#define IDS_ERROR_NOTHING_COMMIT        9642
#define IDS_COMMIT_FINISH               9643
#define IDS_COMMITDLG_POPUP_LOGHISTORY  9644
#define IDS_REBASE_UPTODATE_FMT         9645
#define IDS_REBASE_FORCE_TT             9646
#define IDS_REBASE_ABORT_TT             9647
#define IDS_REBASE_FASTFORWARD_FMT      9649
#define IDS_REBASE_EQUAL_FMT            9650
#define IDS_CLONE_DEPTH_TT              9651
#define IDS_HOOKTYPE_PREPUSH            9652
#define IDS_HOOKTYPE_POSTPUSH           9653
#define IDS_DCOMMIT_STASH_POP           9654
#define IDS_HASH                        9655
#define IDS_REF                         9656
#define IDS_ACTION                      9657
#define IDS_MESSAGE                     9658
#define IDS_TREE_DIFF                   9659
#define IDS_AM_3WAY_TT                  9660
#define IDS_AM_IGNORE_SPACE_TT          9661
#define IDS_STATGRAPH_NUMBEROFUNIT      9662
#define IDS_STATGRAPH_COMMITSBYUNIT     9663
#define IDS_STATGRAPH_FILECHANGESBYUNIT 9664
#define IDS_STATGRAPH_PERCENTAGE_OF_AUTHORSHIP 9665
#define IDS_STATGRAPH_PERCENTAGE_OF_AUTHORSHIPY 9666
#define IDS_STATGRAPH_COMMITSBYDATEXDAY 9667
#define IDS_SUBMODULEDIFF_UNKNOWN       9668
#define IDS_SUBMODULEDIFF_NEWSUBMODULE  9669
#define IDS_SUBMODULEDIFF_DELETESUBMODULE 9670
#define IDS_SUBMODULEDIFF_FASTFORWARD   9671
#define IDS_SUBMODULEDIFF_REWIND        9672
#define IDS_SUBMODULEDIFF_NEWERTIME     9673
#define IDS_SUBMODULEDIFF_OLDERTIME     9674
#define IDS_SUBMODULEDIFF_SAMETIME      9675
#define IDS_PROC_CREATINGPULLREUQEST    9676
#define IDS_PROCEEDBUTTON               9677
#define IDS_PROC_LOG_AUTHOREMAIL        9678
#define IDS_PROC_LOG_COMMITTEREMAIL     9679
#define IDS_PROC_LOG_MERGEPOINT         9680
#define IDS_PROC_LOG_PARENT1            9681
#define IDS_PROC_LOG_PARENT2            9682
#define IDS_PROC_WARNCLEARTEMP          9683
#define IDS_DEFAULT                     9684
#define IDS_ALL                         9685
#define IDS_NONE                        9686
#define IDS_FETCH_REACHABLE             9687
#define IDS_REVGRAPH_ERR_NOMEMORY       9688
#define IDS_PROC_RESET                  9689
#define IDS_FETCH_TAGS_ONLY             9690
#define IDS_PROG_CLONE                  9691
#define IDC_USER_NAME                   9692
#define IDC_USER_PASSWORD               9693
#define IDS_PROGRS_TITLE_CLONE          9694
#define IDS_GITACTION_UPDATE_REF        9697
#define IDS_REV_COUNTER                 9698
#define ID_VIEW_ZOOMIN                  32772
#define ID_VIEW_ZOOMOUT                 32773
#define IDM_SHOWFINDBAR                 32787
#define IDM_FINDNEXT                    32789
#define IDM_FINDPREV                    32790
#define IDM_FINDEXIT                    32791
#define ID_VIEW_ZOOM100                 32803
#define ID_VIEW_ZOOMALL                 32804
#define ID_FILE_SAVEGRAPHAS32805        32805
#define ID_FILE_SAVESTATGRAPHAS         32806
#define ID_FILTER_EXCLUDEPATHS          32807
#define ID_FILTER_EXCLUDEREVISIONS      32808
#define ID_VIEW_ZOOMHEIGHT              32809
#define ID_VIEW_ZOOMWIDTH               32810
#define ID_VIEW_GROUPBRANCHES           32811
#define ID_VIEW_TOPALIGNTREES           32812
#define ID_VIEW_SHOWOVERVIEW            32813
#define ID_VIEW_TOPDOWN                 32814
#define ID_URL_FOCUS                    32814
#define ID_VIEW_SHOWHEAD                32815
#define ID_VIEW_SHOWDIFFPATHS           32816
#define ID_VIEW_SHOWALLREVISIONS        32817
#define ID_VIEW_EXACTCOPYSOURCE         32818
#define ID_VIEW_FOLDTAGS                32819
#define ID_VIEW_REMOVEDELETEDONES       32820
#define ID_LOGDLG_REFRESH               32821
#define ID_LOGDLG_FIND                  32822
#define ID_VIEW_REMOVEUNCHANGEDBRANCHES 32823
#define ID_VIEW_REMOVETAGS              32824
#define ID_LOGDLG_FOCUSFILTER           32825
#define ID_VIEW_SHOWWCREV               32826
#define ID_FOCUS_MESSAGE                32837
#define ID_VIEW_SHOWWCMODIFICATION      32838
#define ID_VIEW_FILTER                  32839
#define ID_VIEW_SHOWTREESTRIPES         32840
#define ID_FILE_SAVEGRAPHAS             32841
#define ID_MENUEXIT                     32842
#define ID_MENUHELP                     32843
#define ID_VIEW_COMPAREREVISIONS        32844
#define ID_VIEW_COMPAREHEADREVISIONS    32845
#define ID_VIEW_UNIFIEDDIFF             32846
#define ID_VIEW_UNIFIEDDIFFOFHEADREVISIONS 32847
#define IDS_REVGRAPH_POPUP_COMPAREHEADS 32848
#define IDS_REVGRAPH_POPUP_UNIDIFFHEADS 32849
#define IDS_PROC_STATISTICS_DIFF        32851
#define IDS_PROGS_TITLE_GATHERSTATISTICS 32852
#define IDS_STATGRAPH_LINES_BYDATE_W    32853
#define IDS_STATGRAPH_LINES_BYDATE_WO   32854
#define IDS_STATGRAPH_LINES_BYDATE_W_Y  32855
#define IDS_STATGRAPH_LINES_BYDATE_WO_Y 32856
#define ID_FOCUS_FILELIST               32857
#define IDC_DETECT_MOVED_OR_COPIED_LINES 32858
#define IDS_DETECT_MOVED_OR_COPIED_LINES_DISABLED 32859
#define IDS_DETECT_MOVED_OR_COPIED_LINES_WITHIN_FILE 32860
#define IDS_DETECT_MOVED_OR_COPIED_LINES_FROM_MODIFIED_FILES 32861
#define IDS_DETECT_MOVED_OR_COPIED_LINES_FROM_EXISTING_FILES_AT_FILE_CREATION 32862
#define IDS_DETECT_MOVED_OR_COPIED_LINES_FROM_EXISTING_FILES 32863
#define IDC_SHOWCOMPLETELOG             32864
#define IDC_DETECT_MOVED_OR_COPIED_LINES_NUM_CHARACTERS_WITHIN_FILE 32865
#define IDC_DETECT_MOVED_OR_COPIED_LINES_NUM_CHARACTERS_FROM_FILES 32866
#define ID_GO_FORWARD                   32867
#define ID_GO_BACKWARD                  32868
#define ID_GO_UP                        32869
#define ID_GO_DOWN                      32870
#define ID_GO_BACKWARD_SELECT           32871
#define ID_GO_FORWARD_SELECT            32872
#define ID_SELECT_SEARCHFIELD           32873
#define ID_EXITCLEARFILTER              32874
#define IDS_ERR_CHANGELIST_LOAD         32900
#define IDS_ERR_CHANGELIST_SAVE         32901

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        363
#define _APS_NEXT_COMMAND_VALUE         32874
#define _APS_NEXT_CONTROL_VALUE         1851
#define _APS_NEXT_SYMED_VALUE           201
#endif
#endif
