//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TortoiseGitBlame.rc
//
#define IDD_ABOUTBOX				100
#define IDP_OLE_INIT_FAILED			100
#define IDR_POPUP_EDIT				119
#define ID_STATUSBAR_PANE1			120
#define ID_STATUSBAR_PANE2			121
#define IDS_STATUS_PANE1			122
#define IDS_STATUS_PANE2			123
#define IDS_TOOLBAR_STANDARD		124
#define IDS_TOOLBAR_CUSTOMIZE		125
#define ID_VIEW_CUSTOMIZE			126
#define IDR_MAINFRAME				128
#define IDR_MAINFRAME_256			129
#define IDR_TortoiseGitBlamTYPE				130
#define ID_VIEW_OUTPUTWND			149
#define ID_VIEW_PROPERTIESWND		150
#define ID_SORTPROPERTIES			151
#define ID_PROPERTIES1				152
#define ID_PROPERTIES2				153
#define ID_EXPAND_ALL				154
#define IDS_OUTPUT_WND				157
#define IDS_PROPERTIES_WND			158
#define IDI_OUTPUT_WND				165
#define IDI_OUTPUT_WND_HC			166
#define IDI_PROPERTIES_WND			167
#define IDI_PROPERTIES_WND_HC		168
#define IDR_OUTPUT_POPUP			182
#define IDR_PROPERTIES				183
#define IDB_PROPERTIES_HC			184
#define IDR_THEME_MENU				200
#define ID_SET_STYLE				201
#define ID_VIEW_APPLOOK_WIN_2000	210
#define ID_VIEW_APPLOOK_OFF_XP		211
#define ID_VIEW_APPLOOK_WIN_XP		212
#define ID_VIEW_APPLOOK_OFF_2003	213
#define ID_VIEW_APPLOOK_VS_2005		214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE	215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK	216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER	217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA	218
#define IDS_BUILD_TAB				300
#define IDS_DEBUG_TAB				301
#define IDS_FIND_TAB				302
#define IDS_EDIT_MENU				306

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	310
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		310
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
