//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\TortoiseGit\src\Resources\TortoiseMergeENG.rc
//
#define IDR_MAINFRAME                   100
#define IDP_OLE_INIT_FAILED             101
#define IDD_SETMAINPAGE                 107
#define IDR_TortoiseMergeTYPE           129
#define IDD_OPENDLG                     130
#define IDD_DIFFLOCATOR                 131
#define IDI_REMOVEDLINE                 132
#define IDI_ADDEDLINE                   133
#define IDI_CONFLICTEDLINE              134
#define IDD_FILEPATCHES                 135
#define IDD_ABOUT                       136
#define IDR_DOWNLOAD                    136
#define IDD_LINEDIFF                    137
#define IDB_BITMAP1                     137
#define IDB_TTF_BMP                     137
#define IDD_SETCOLORPAGE                138
#define IDD_FIND                        139
#define IDI_WHITESPACELINE              140
#define IDI_EQUALLINE                   141
#define IDI_LINEENDINGCR                142
#define IDI_LINEENDINGCRLF              143
#define IDI_LINEENDINGLF                144
#define IDI_CONFLICTEDIGNOREDLINE       145
#define IDI_LINEEDITED                  146
#define IDB_LOGOFLIPPED                 168
#define IDD_PATCH_FILE_OPEN_CUSTOM      180
#define IDS_SELECTFILE                  200
#define IDC_BASEFILEEDIT                1000
#define IDS_ERR_PATCH_NOINDEX           1000
#define IDC_BASEFILEBROWSE              1001
#define IDS_ERR_PATCH_NOEQUATIONCHARLINE 1001
#define IDC_THEIRFILEEDIT               1002
#define IDS_ERR_PATCH_NOREMOVEFILELINE  1002
#define IDC_THEIRFILEBROWSE             1003
#define IDS_ERR_PATCH_NOADDFILELINE     1003
#define IDS_ERR_PATCH_RENAMINGNOTSUPPORTED 1004
#define IDC_VERSIONSTRING               1005
#define IDS_ERR_PATCH_CHUNKSTARTNOTFOUND 1005
#define IDC_YOURFILEEDIT                1006
#define IDS_ERR_PATCH_UNKOWNLINETYPE    1006
#define IDC_YOURFILEBROWSE              1007
#define IDS_ERR_PATCH_CHUNKMISMATCH     1007
#define IDC_DIFFFILEEDIT                1008
#define IDC_DIFFFILEBROWSE              1009
#define IDC_DIRECTORYEDIT               1010
#define IDC_DIRECTORYBROWSE             1011
#define IDC_MERGERADIO                  1012
#define IDC_APPLYRADIO                  1013
#define IDC_FILELIST                    1014
#define IDC_BACKUP                      1015
#define IDC_FIRSTDIFFONLOAD             1016
#define IDC_TABSIZE                     1017
#define IDC_IGNORELF                    1018
#define IDC_WSCOMPARE                   1019
#define IDC_WSIGNOREALL                 1020
#define IDS_ERR_PATCH_INVALIDPATCHFILE  1020
#define IDC_WSIGNORECHANGED             1021
#define IDS_ERR_PATCH_FILENOTINPATCH    1021
#define IDS_ERR_PATCH_DOESNOTMATCH      1022
#define IDC_DIFFGROUP                   1022
#define IDS_ERR_PATCH_FILESAVE          1023
#define IDC_MISCGROUP                   1023
#define IDC_ONEPANE                     1024
#define IDC_BKUNKNOWN                   1027
#define IDC_FGUNKNOWN                   1028
#define IDC_BKNORMAL                    1029
#define IDC_FINDCOMBO                   1029
#define IDC_FGNORMAL                    1030
#define IDC_FONTNAMES                   1030
#define IDC_BKREMOVED                   1031
#define IDC_FGREMOVED                   1032
#define IDC_BKWHITESPACEREMOVED         1033
#define IDC_BKWHITESPACES               1033
#define IDC_FGWHITESPACEREMOVED         1034
#define IDC_BKWHITESPACEDIFF            1034
#define IDC_BKADDED                     1035
#define IDC_BKWHITESPACEDIFF2           1036
#define IDC_FGWHITESPACES               1036
#define IDC_FGADDED                     1037
#define IDC_BKWHITESPACEADDED           1038
#define IDC_FGWHITESPACEADDED           1039
#define IDS_ERR_MAINFRAME_FILEVERSIONNOTFOUND 1040
#define IDC_BKEMPTY                     1040
#define IDS_ERR_MAINFRAME_FILEHASCONFLICTS 1041
#define IDC_FGEMPTY                     1041
#define IDC_BKCONFLICTRESOLVED          1041
#define IDC_BKCONFLICTED                1042
#define IDC_FGCONFLICTED                1043
#define IDC_BKCONFLICTEDADDED           1044
#define IDC_FGCONFLICTEDADDED           1045
#define IDC_BKCONFLICTEDEMPTY           1046
#define IDC_FGCONFLICTEDEMPTY           1047
#define IDC_BKIDENTICAL                 1048
#define IDC_FGIDENTICAL                 1049
#define IDC_BKIDENTICALADDED            1050
#define IDC_FGIDENTICALADDED            1051
#define IDC_BKIDENTICALREMOVED          1052
#define IDC_FGIDENTICALREMOVED          1053
#define IDC_VERSIONABOUT                1054
#define IDC_BKTHEIRSADDED               1054
#define IDC_FGTHEIRSADDED               1055
#define IDC_BKTHEIRSREMOVED             1056
#define IDC_FGTHEIRSREMOVED             1057
#define IDC_BKYOURSADDED                1058
#define IDC_FGYOURSADDED                1059
#define IDC_BKYOURSREMOVED              1060
#define IDC_FGYOURSREMOVED              1061
#define IDC_LANGUAGECOMBO               1062
#define IDC_LINENUMBERS                 1063
#define IDC_CHECK1                      1064
#define IDC_MATCHCASE                   1064
#define IDC_PATCHFROMCLIPBOARD          1064
#define IDC_UTF8DEFAULT                 1064
#define IDC_CHECK2                      1065
#define IDC_LIMITTODIFFS                1065
#define IDC_STRIKEOUT                   1066
#define IDC_WHOLEWORD                   1066
#define IDC_CHECK3                      1067
#define IDC_RESOLVE                     1067
#define IDC_CASEINSENSITIVE             1067
#define ID_RESOLVE                      1067
#define IDC_CHECK4                      1068
#define IDC_USEBDIFF                    1068
#define IDC_SEARCHTEXT                  1070
#define IDC_BKMODIFIED                  1071
#define IDC_UNIDIFFGROUP                1072
#define IDC_MERGEGROUP                  1073
#define IDC_VERSIONBOX                  1075
#define IDC_PATCHSELECTEDBUTTON         1075
#define IDC_PATCHALLBUTTON              1076
#define IDS_ERR_DIFF_DIFF               1080
#define IDS_ERR_DIFF_NEWLINES           1081
#define IDC_WEBLINK                     1084
#define IDC_SUPPORTLINK                 1085
#define IDC_FONTSIZES                   1086
#define IDS_ERR_FILE_OPEN               1100
#define IDS_ERR_FILE_BINARY             1101
#define IDS_ERR_FILE_NOTAFILE           1102
#define IDS_ERR_FILE_TOOBIG             1103
#define IDC_PATCH_TO_CLIPBOARD          1132
#define IDS_ABOUTVERSION                1700
#define IDS_ABOUTVERSIONBOX             1701
#define IDS_SETTINGSTITLE               1702
#define ID_INDICATOR_LEFTVIEW           2000
#define ID_INDICATOR_RIGHTVIEW          2001
#define ID_INDICATOR_BOTTOMVIEW         2002
#define IDS_COMMONFILEFILTER            2500
#define IDS_PATCHFILEFILTER             2501
#define IDS_STATUSBAR_REMOVEDLINES      3000
#define IDS_STATUSBAR_ADDEDLINES        3001
#define IDS_STATUSBAR_CONFLICTEDLINES   3002
#define IDS_STATUSBAR_LEFTVIEW          3003
#define IDS_STATUSBAR_RIGHTVIEW         3004
#define IDS_STATUSBAR_CONFLICTS         3005
#define IDS_VIEWCONTEXTMENU_USETHISBLOCK 4000
#define IDS_VIEWCONTEXTMENU_USETHEIRBLOCK 4001
#define IDS_VIEWCONTEXTMENU_USEYOURBLOCK 4002
#define IDS_VIEWCONTEXTMENU_USETHEIRANDYOURBLOCK 4003
#define IDS_VIEWCONTEXTMENU_USEYOURANDTHEIRBLOCK 4004
#define IDS_VIEWCONTEXTMENU_USETHISFILE 4005
#define IDS_VIEWCONTEXTMENU_USEOTHERBLOCK 4006
#define IDS_VIEWCONTEXTMENU_USEOTHERFILE 4007
#define IDS_VIEWCONTEXTMENU_USEBOTHTHISFIRST 4008
#define IDS_VIEWCONTEXTMENU_USEBOTHTHISLAST 4009
#define IDS_VIEWTITLE_THEIRS            4200
#define IDS_VIEWTITLE_MERGED            4201
#define IDS_VIEWTITLE_MINE              4202
#define IDS_VIEWSCROLLTIPTEXT           4300
#define IDS_SAVEASTITLE                 5000
#define IDS_COMMANDLINEHELP             5001
#define IDS_OPENDIFFFILETITLE           5002
#define IDS_GETVERSIONOFFILETITLE       5003
#define IDS_GETVERSIONOFFILE            5004
#define IDS_WARNMODIFIEDLOOSECHANGES    5005
#define IDS_ASKFORSAVE                  5006
#define IDS_WARNMODIFIEDLOOSECHANGES_   5007
#define IDS_WARNMODIFIEDLOOSECHANGESOPTIONS 5007
#define IDS_WARNBETTERPATCHPATHFOUND    5008
#define IDS_NOTFOUNDVIEWTITLEINDICATOR  5009
#define IDS_WARNABSOLUTEPATHFOUND       5010
#define IDS_WARNABSOLUTEPATHNOTFOUND    5011
#define IDS_DELETEWHENEMPTY             5012
#define IDS_EMPTYLINETT                 5013
#define IDS_PATCH_ALL                   6000
#define IDS_PATCH_TITLE                 6001
#define IDS_DIFF_TITLE                  6002
#define IDS_PATCH_SELECTED              6003
#define IDS_PATCH_PREVIEW               6004
#define IDS_PATCH_REVIEW                6005
#define IDS_COLOURPICKER_CUSTOMTEXT     7000
#define IDS_COLOURPICKER_DEFAULTTEXT    7001
#define IDS_EDIT_COPY                   8000
#define IDS_EDIT_CUT                    8001
#define IDS_EDIT_PASTE                  8002
#define ID_VIEW_WHITESPACES             32774
#define ID_VIEW_ONEWAYDIFF              32775
#define ID_NAVIGATE_NEXTDIFFERENCE      32779
#define ID_NAVIGATE_PREVIOUSDIFFERENCE  32780
#define ID_VIEW_                        32781
#define ID_VIEW_OPTIONS                 32782
#define ID_BUTTON32783                  32783
#define ID_EDIT_FINDNEXT                32790
#define ID_FILE_RELOAD                  32794
#define ID_BUTTON32797                  32797
#define ID_VIEW_LINEDOWN                32799
#define ID_NAVIGATE_PREVIOUSCONFLICT    32802
#define ID_NAVIGATE_NEXTCONFLICT        32804
#define ID_BUTTON32807                  32807
#define ID_EDIT_MARKASRESOLVED          32808
#define ID_VIEW_SWITCHLEFT              32811
#define ID_BUTTON32812                  32812
#define ID_VIEW_LINELEFT                32813
#define ID_VIEW_LINERIGHT               32814
#define ID_BUTTON32816                  32816
#define ID_VIEW_SHOWFILELIST            32817
#define ID_EDIT_FINDPREV                32818
#define ID_EDIT_USETHEIRBLOCK           32819
#define ID_EDIT_USEMYBLOCK              32820
#define ID_EDIT_USETHEIRTHENMYBLOCK     32821
#define ID_EDIT_USEMINETHENTHEIRBLOCK   32822
#define ID_VIEW_INLINEDIFFWORD          32825
#define ID_EDIT_                        32827
#define ID_EDIT_CREATEUNIFIEDDIFFFILE   32828
#define ID_CARET_LEFT                   32829
#define ID_CARET_RIGHT                  32830
#define ID_CARET_DOWN                   32831
#define ID_CARET_UP                     32832
#define ID_CARET_WORDLEFT               32833
#define ID_CARET_WORDRIGHT              32834
#define ID_VIEW_APPLOOK_WIN_2000        32844
#define ID_VIEW_APPLOOK_OFF_XP          32845
#define ID_VIEW_APPLOOK_WIN_XP          32846
#define ID_VIEW_APPLOOK_OFF_2003        32847
#define ID_VIEW_APPLOOK_VS_2005         32848
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32849
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32850
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32851
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32852
#define ID_VIEW_LINEDIFFBAR             32853
#define ID_VIEW_LOCATORBAR              32854
#define ID_EDIT_USELEFTBLOCK            32855
#define ID_EDIT_USELEFTFILE             32856
#define ID_EDIT_USEBLOCKFROMLEFTBEFORERIGHT 32857
#define ID_EDIT_USEBLOCKFROMRI          32858
#define ID_EDIT_USEBLOCKFROMRIGHTBEFORELEFT 32859
#define ID_EDIT_TEST                    32862
#define ID_EDIT_SELECTALL               32883

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32884
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
