//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\TortoiseGit\src\Resources\TortoiseMergeENG.rc
//
#define IDR_MAINFRAME                   100
#define IDP_OLE_INIT_FAILED             101
#define IDS_TITLE_REJECTEDHUNKS         101
#define IDS_CONFIGUREREGEXES            102
#define IDS_ASKFORSAVE_MARKEDBLOCKS     103
#define IDS_WARNMARKEDBLOCKS            104
#define IDS_MARKEDBLOCKSSAVEINCLUDE     105
#define IDS_MARKEDBLOCKSSAVEEXCLUDE     106
#define IDS_MARKEDBLCOKSSAVEIGNORE      107
#define IDD_SETMAINPAGE                 107
#define IDS_MSGBOX_YES                  108
#define IDS_MSGBOX_NO                   109
#define IDS_MSGBOX_CANCEL               110
#define IDD_OPENDLG                     130
#define IDD_DIFFLOCATOR                 131
#define IDI_REMOVEDLINE                 132
#define IDI_ADDEDLINE                   133
#define IDI_CONFLICTEDLINE              134
#define IDD_FILEPATCHES                 135
#define IDD_ABOUT                       136
#define IDD_LINEDIFF                    137
#define IDD_SETCOLORPAGE                138
#define IDD_FIND                        139
#define IDI_WHITESPACELINE              140
#define IDI_EQUALLINE                   141
#define IDI_LINEENDINGCR                142
#define IDI_LINEENDINGCRLF              143
#define IDI_LINEENDINGLF                144
#define IDI_CONFLICTEDIGNOREDLINE       145
#define IDI_LINEEDITED                  146
#define IDI_MOVEDLINE                   152
#define IDC_MARGINCURSOR                153
#define IDD_GOTO                        155
#define IDB_LOGO                        159
#define IDD_REGEXFILTERS                164
#define IDD_REGEXFILTER                 165
#define IDR_REGEXFILTERINI              166
#define IDB_LOGOFLIPPED                 168
#define IDR_IGNORECOMMENTSTXT           169
#define IDI_LINEMARKED                  170
#define IDB_REGEX_FILTER                171
#define IDS_SELECTFILE                  200
#define IDD_ENCODING                    300
#define IDC_STATIC_ENCODING             301
#define IDC_COMBO_ENCODING              302
#define IDC_STATIC_EOL                  303
#define IDC_COMBO_EOL                   304
#define ID_REGEXFILTER                  500
#define IDC_BASEFILEEDIT                1000
#define IDC_BASEFILEBROWSE              1001
#define IDC_THEIRFILEEDIT               1002
#define IDC_THEIRFILEBROWSE             1003
#define IDS_ERR_PATCH_NOADDFILELINE     1003
#define IDC_VERSIONSTRING               1005
#define IDC_YOURFILEEDIT                1006
#define IDS_ERR_PATCH_UNKNOWNLINETYPE    1006
#define IDC_YOURFILEBROWSE              1007
#define IDS_ERR_PATCH_CHUNKMISMATCH     1007
#define IDC_DIFFFILEEDIT                1008
#define IDC_DIFFFILEBROWSE              1009
#define IDC_DIRECTORYEDIT               1010
#define IDC_DIRECTORYBROWSE             1011
#define IDC_MERGERADIO                  1012
#define IDC_APPLYRADIO                  1013
#define IDC_FILELIST                    1014
#define IDC_BACKUP                      1015
#define IDC_FIRSTDIFFONLOAD             1016
#define IDC_TABSIZE                     1017
#define IDC_IGNORELF                    1018
#define IDS_ERR_PATCH_INVALIDPATCHFILE  1020
#define IDS_ERR_PATCH_FILENOTINPATCH    1021
#define IDS_ERR_PATCH_DOESNOTMATCH      1022
#define IDC_DIFFGROUP                   1022
#define IDC_MISCGROUP                   1023
#define IDC_ONEPANE                     1024
#define IDC_BKNORMAL                    1029
#define IDC_FINDCOMBO                   1029
#define IDC_FGNORMAL                    1030
#define IDC_FONTNAMES                   1030
#define IDC_REPLACECOMBO                1030
#define IDC_BKREMOVED                   1031
#define IDC_FGREMOVED                   1032
#define IDC_BKWHITESPACES               1033
#define IDC_BKWHITESPACEDIFF            1034
#define IDC_BKADDED                     1035
#define IDC_FGWHITESPACES               1036
#define IDC_FGADDED                     1037
#define IDS_ERR_MAINFRAME_FILEVERSIONNOTFOUND 1040
#define IDC_BKEMPTY                     1040
#define IDS_ERR_MAINFRAME_FILEHASCONFLICTS 1041
#define IDC_BKCONFLICTRESOLVED          1041
#define IDC_BKCONFLICTED                1042
#define IDC_FGCONFLICTED                1043
#define IDC_FGCONFLICTRESOLVED          1044
#define IDC_FGEMPTY                     1045
#define IDC_BKFILTERED                  1046
#define IDC_VERSIONABOUT                1054
#define IDC_LINENUMBERS                 1063
#define IDC_MATCHCASE                   1064
#define IDC_PATCHFROMCLIPBOARD          1064
#define IDC_UTF8DEFAULT                 1064
#define IDC_LIMITTODIFFS                1065
#define IDC_AUTOADD                     1065
#define IDC_WHOLEWORD                   1066
#define IDC_USERIBBONS                  1066
#define IDC_CASEINSENSITIVE             1067
#define IDC_BKMODIFIED                  1071
#define IDC_UNIDIFFGROUP                1072
#define IDC_MERGEGROUP                  1073
#define IDC_SEARCHUP                    1074
#define IDC_FIRSTCONFLICTONLOAD         1074
#define IDC_VERSIONBOX                  1075
#define IDC_PATCHSELECTEDBUTTON         1075
#define IDC_PATCHALLBUTTON              1076
#define IDC_NUMBER                      1077
#define IDC_LINELABEL                   1078
#define IDC_MAXINLINE                   1079
#define IDS_ERR_DIFF_DIFF               1080
#define IDC_VIEW                        1080
#define IDS_ERR_DIFF_NEWLINES           1081
#define IDC_WEBLINK                     1084
#define IDC_SUPPORTLINK                 1085
#define IDC_FONTSIZES                   1086
#define IDC_USESPACES                   1091
#define IDC_RESTORE                     1097
#define IDC_SMARTTABCHAR                1098
#define IDS_ERR_FILE_OPEN               1100
#define IDS_ERR_FILE_BINARY             1101
#define IDS_ERR_FILE_NOTAFILE           1102
#define IDS_ERR_FILE_TOOBIG             1103
#define IDS_ERR_PATCHPATHS              1111
#define IDS_ERR_ERROR                   1112
#define IDS_ERR_INVALIDREGEX            1113
#define IDS_APPNAME                     1271
#define IDS_GOTOLINE                    1400
#define IDS_GOTO_OUTOFRANGE             1401
#define IDC_COUNT                       1501
#define IDS_FIND_COUNT                  1502
#define IDC_FINDSTATUS                  1503
#define IDS_FIND_NOTFOUND               1504
#define IDC_REGEXLIST                   1504
#define IDS_FIND_BOTTOMREACHED          1505
#define IDC_ADD                         1505
#define IDS_FIND_TOPREACHED             1506
#define IDC_EDIT                        1506
#define IDC_REMOVE                      1507
#define IDS_FIND_REPLACED               1507
#define IDC_NAME                        1508
#define IDC_REGEX                       1509
#define IDC_CONTEXTLINES                1509
#define IDC_ENABLEEDITORCONFIG          1510
#define IDC_REPLACE                     1511
#define IDC_REPLACEALL                  1512
#define IDS_TEXTIDENTICAL_MAIN          1600
#define IDS_TEXTIDENTICAL_WHITESPACE    1601
#define IDS_TEXTIDENTICAL_ENCODING      1602
#define IDS_TEXTIDENTICAL_EOL           1603
#define IDS_ABOUTVERSION                1700
#define IDS_ABOUTVERSIONBOX             1701
#define IDS_SETTINGSTITLE               1702
#define ID_INDICATOR_LEFTVIEW           2000
#define ID_INDICATOR_RIGHTVIEW          2001
#define ID_INDICATOR_BOTTOMVIEW         2002
#define ID_INDICATOR_LEFTVIEWCOMBOENCODING 2010
#define ID_INDICATOR_RIGHTVIEWCOMBOENCODING 2011
#define ID_INDICATOR_BOTTOMVIEWCOMBOENCODING 2012
#define ID_INDICATOR_LEFTVIEWCOMBOEOL   2020
#define ID_INDICATOR_RIGHTVIEWCOMBOEOL  2021
#define ID_INDICATOR_BOTTOMVIEWCOMBOEOL 2022
#define ID_INDICATOR_LEFTVIEWCOMBOTABMODE 2030
#define ID_INDICATOR_RIGHTVIEWCOMBOTABMODE 2031
#define ID_INDICATOR_BOTTOMVIEWCOMBOTABMODE 2032
#define ID_INDICATOR_LEFTENCODINGSTART  2100
#define ID_INDICATOR_RIGHTENCODINGSTART 2120
#define ID_INDICATOR_BOTTOMENCODINGSTART 2140
#define ID_INDICATOR_LEFTEOLSTART       2200
#define ID_INDICATOR_RIGHTEOLSTART      2220
#define ID_INDICATOR_BOTTOMEOLSTART     2240
#define ID_INDICATOR_LEFTTABMODESTART   2300
#define ID_INDICATOR_RIGHTTABMODESTART  2320
#define ID_INDICATOR_BOTTOMTABMODESTART 2340
#define IDS_COMMONFILEFILTER            2500
#define IDS_PATCHFILEFILTER             2501
#define IDS_PATCH_SEARCHPATHTITLE       2700
#define IDS_PATCH_SEARCHPATHLINE1       2701
#define IDS_PATCH_PROGTITLE             2702
#define IDS_PATCH_PATHINGFILE           2703
#define IDS_PATH                        2704
#define IDS_STATE                       2705
#define IDS_STATE_ERROR                 2706
#define IDS_STATE_PATCHED               2707
#define IDS_STATE_CONFLICTS             2708
#define IDS_ERR_PATCH_FILENAMENOTUNIQUE 2800
#define IDS_ERR_MAINFRAME_FILECONFLICTNOVERSION 2801
#define IDS_MOVED_FROM_TT               2810
#define IDS_MOVED_TO_TT                 2811
#define IDS_STATUSBAR_REMOVEDLINES      3000
#define IDS_STATUSBAR_ADDEDLINES        3001
#define IDS_STATUSBAR_CONFLICTEDLINES   3002
#define IDS_STATUSBAR_LEFTVIEW          3003
#define IDS_STATUSBAR_RIGHTVIEW         3004
#define IDS_STATUSBAR_CONFLICTS         3005
#define IDS_STATUSBAR_BOTTOMVIEW        3006
#define IDS_ENCODING_COMBO_TOOLTIP      3010
#define IDS_VIEWCONTEXTMENU_USETHISBLOCK 4000
#define IDS_VIEWCONTEXTMENU_USETHEIRBLOCK 4001
#define IDS_VIEWCONTEXTMENU_USEYOURBLOCK 4002
#define IDS_VIEWCONTEXTMENU_USETHEIRANDYOURBLOCK 4003
#define IDS_VIEWCONTEXTMENU_USEYOURANDTHEIRBLOCK 4004
#define IDS_VIEWCONTEXTMENU_USETHISFILE 4005
#define IDS_VIEWCONTEXTMENU_USEOTHERBLOCK 4006
#define IDS_VIEWCONTEXTMENU_USEOTHERFILE 4007
#define IDS_VIEWCONTEXTMENU_USEBOTHTHISFIRST 4008
#define IDS_VIEWCONTEXTMENU_USEBOTHTHISLAST 4009
#define IDS_VIEWCONTEXTMENU_PREPENDTHIS 4010
#define IDS_VIEWCONTEXTMENU_USETHIS     4011
#define IDS_VIEWCONTEXTMENU_APPENDTHIS  4012
#define IDS_VIEWCONTEXTMENU_PREPENDRIGHT 4013
#define IDS_VIEWCONTEXTMENU_USERIGHT    4014
#define IDS_VIEWCONTEXTMENU_APPENDRIGHT 4015
#define IDS_VIEWCONTEXTMENU_EOL         4016
#define IDS_VIEWCONTEXTMENU_ENCODING    4017
#define IDS_VIEWCONTEXTMENU_MARKBLOCK   4018
#define IDS_VIEWCONTEXTMENU_UNMARKBLOCK 4019
#define IDS_VIEWCONTEXTMENU_LEAVEONLYMARKEDBLOCKS 4020
#define IDS_VIEWTITLE_THEIRS            4200
#define IDS_VIEWTITLE_MERGED            4201
#define IDS_VIEWTITLE_MINE              4202
#define IDS_VIEWSCROLLTIPTEXT           4300
#define IDS_SAVEASTITLE                 5000
#define IDS_COMMANDLINEHELP             5001
#define IDS_OPENDIFFFILETITLE           5002
#define IDS_GETVERSIONOFFILETITLE       5003
#define IDS_GETVERSIONOFFILE            5004
#define IDS_WARNMODIFIEDLOOSECHANGES    5005
#define IDS_WARNMODIFIEDLOOSECHANGESOPTIONS 5007
#define IDS_WARNBETTERPATCHPATHFOUND    5008
#define IDS_NOTFOUNDVIEWTITLEINDICATOR  5009
#define IDS_DELETEWHENEMPTY             5012
#define IDS_EMPTYLINETT                 5013
#define IDS_WARNMODIFIEDOUTSIDELOOSECHANGES 5014
#define IDS_WARNMODIFIEDOUTSIDE         5015
#define IDS_WARNBETTERPATCHPATHFOUND_TASK2 5016
#define IDS_WARNBETTERPATCHPATHFOUND_TASK3 5017
#define IDS_WARNBETTERPATCHPATHFOUND_TASK4 5018
#define IDS_DELETEWHENEMPTY_TASK2       5019
#define IDS_DELETEWHENEMPTY_TASK3       5020
#define IDS_DELETEWHENEMPTY_TASK4       5021
#define IDS_ASKFORSAVE_TASK2            5022
#define IDS_ASKFORSAVE_TASK3            5023
#define IDS_ASKFORSAVE_TASK4            5024
#define IDS_ASKFORSAVE_TASK5            5025
#define IDS_ASKFORSAVE_TASK6            5026
#define IDS_ASKFORSAVE_TASK7            5027
#define IDS_ASKFORSAVE_TASK8            5028
#define IDS_WARNMODIFIEDOUTSIDE_TASK2   5029
#define IDS_WARNMODIFIEDOUTSIDE_TASK3   5030
#define IDS_WARNMODIFIEDOUTSIDE_TASK4   5031
#define IDS_WARNMODIFIEDOUTSIDE_TASK5   5032
#define IDS_ERR_MAINFRAME_FILEHASCONFLICTS_TASK2 5033
#define IDS_ERR_MAINFRAME_FILEHASCONFLICTS_TASK3 5034
#define IDS_ERR_MAINFRAME_FILEHASCONFLICTS_TASK4 5035
#define IDS_ASKFORSAVE_NOSAVE_OPEN      5036
#define IDS_ASKFORSAVE_CANCEL_OPEN      5037
#define IDS_ASKFORSAVE_CANCEL_OPTIONS   5039
#define IDS_ASKFORSAVE_SAVELEFT         5041
#define IDS_ASKFORSAVE_SAVELEFTAS       5042
#define IDS_ASKFORSAVE_SAVERIGHT        5043
#define IDS_ASKFORSAVE_SAVERIGHTAS      5044
#define IDS_ASKFORSAVE_SAVEALL2         5045
#define IDS_SAVE                        5046
#define IDS_SAVE_MORE                   5047
#define IDS_ASKFORSAVE_SAVEBOTTOMAS     5048
#define IDS_ASKFORSAVE_NEEDRESOLVE      5049
#define IDS_ASKFORSAVEAS                5050
#define IDS_ASKFORSAVEAS_MORE           5051
#define IDS_ASKFORSAVEAS_MORECONFLICT   5052
#define IDS_MARKASRESOLVED              5100
#define IDS_MARKASRESOLVED_TASK2        5101
#define IDS_MARKASRESOLVED_TASK3        5102
#define IDS_MARKASRESOLVED_TASK4        5103
#define IDS_PATCH_ALL                   6000
#define IDS_PATCH_TITLE                 6001
#define IDS_DIFF_TITLE                  6002
#define IDS_PATCH_SELECTED              6003
#define IDS_PATCH_PREVIEW               6004
#define IDS_PATCH_ITEMTT                6005
#define IDS_PATCH_COPYFROMCLIPBOARD     6006
#define IDS_HEADER_DIFFLEFTTOBASE       6100
#define IDS_HEADER_DIFFRIGHTTOBASE      6101
#define IDS_COLOURPICKER_CUSTOMTEXT     7000
#define IDS_COLOURPICKER_DEFAULTTEXT    7001
#define IDS_EDIT_COPY                   8000
#define IDS_EDIT_CUT                    8001
#define IDS_EDIT_PASTE                  8002
#define IDS_EDIT_TAB2SPACE              8003
#define IDS_EDIT_SPACE2TAB              8004
#define IDS_EDIT_TRIM                   8005
#define ID_VIEW_WHITESPACES             32774
#define ID_VIEW_ONEWAYDIFF              32775
#define ID_NAVIGATE_NEXTDIFFERENCE      32779
#define ID_NAVIGATE_PREVIOUSDIFFERENCE  32780
#define ID_VIEW_OPTIONS                 32782
#define ID_EDIT_FINDNEXT                32790
#define ID_FILE_RELOAD                  32794
#define ID_VIEW_LINEDOWN                32799
#define ID_NAVIGATE_PREVIOUSCONFLICT    32802
#define ID_NAVIGATE_NEXTCONFLICT        32804
#define ID_EDIT_MARKASRESOLVED          32808
#define ID_VIEW_SWITCHLEFT              32811
#define ID_VIEW_LINELEFT                32813
#define ID_VIEW_LINERIGHT               32814
#define ID_VIEW_SHOWFILELIST            32817
#define ID_EDIT_FINDPREV                32818
#define ID_EDIT_USETHEIRBLOCK           32819
#define ID_EDIT_USEMYBLOCK              32820
#define ID_EDIT_USETHEIRTHENMYBLOCK     32821
#define ID_EDIT_USEMINETHENTHEIRBLOCK   32822
#define ID_VIEW_INLINEDIFFWORD          32825
#define ID_EDIT_CREATEUNIFIEDDIFFFILE   32828
#define ID_CARET_LEFT                   32829
#define ID_CARET_RIGHT                  32830
#define ID_CARET_DOWN                   32831
#define ID_CARET_UP                     32832
#define ID_CARET_WORDLEFT               32833
#define ID_CARET_WORDRIGHT              32834
#define ID_VIEW_LINEDIFFBAR             32853
#define ID_VIEW_LOCATORBAR              32854
#define ID_EDIT_USELEFTBLOCK            32855
#define ID_EDIT_USELEFTFILE             32856
#define ID_EDIT_USEBLOCKFROMLEFTBEFORERIGHT 32857
#define ID_EDIT_USEBLOCKFROMRIGHTBEFORELEFT 32859
#define ID_VIEW_COLLAPSED               32870
#define ID_VIEW_COMPAREWHITESPACES      32871
#define ID_VIEW_IGNOREWHITESPACECHANGES 32872
#define ID_VIEW_IGNOREALLWHITESPACECHANGES 32873
#define ID_NAVIGATE_NEXTINLINEDIFF      32875
#define ID_NAVIGATE_PREVINLINEDIFF      32876
#define ID_NAVIGATE_NEXTINLINEDIFFERENCE 32878
#define ID_NAVIGATE_PREVIOUSINLINEDIFFERENCE 32879
#define ID_VIEW_MOVEDBLOCKS             32880
#define ID_VIEW_WRAPLONGLINES           32881
#define ID_EDIT_SELECTALL               32883
#define ID_VIEW_INLINEDIFF              32889
#define ID_EDIT_FINDNEXTSTART           32891
#define ID_EDIT_FINDPREVSTART           32892
#define ID_EDIT_GOTOLINE                32893
#define ID_VIEW_IGNORECOMMENTS          32896
#define ID_LOGOBUTTON                   32897
#define ID_VIEW_BARS                    32898
#define ID_USEBLOCKS                    32914
#define ID_EDIT_ENABLE                  32976
#define ID_FILE_ENABLEEDIT              32978
#define ID_EDIT_REGEXFILTER             32992
#define ID_REGEXFILTER_REGEXFILTER      32993
#define ID_EDIT_THREEWAY_ACTIONS        33001
#define ID_REGEX_NO_FILTER              33002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         33003
#define _APS_NEXT_CONTROL_VALUE         1513
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
