#pragma once

#define TGIT_DEFMAJOR 1
#define TGIT_DEFMINOR 7
#define TGIT_DEFMICRO 15
#define TGIT_DEFBUILD 0

#define TGIT_QUOTE2(str) #str
#define TGIT_QUOTE(str) TGIT_QUOTE2(str)
#define TGIT_LQUOTE(str) L#str
#define TGIT_DEFSTRMAJOR TGIT_QUOTE(TGIT_DEFMAJOR)
#define TGIT_DEFSTRMINOR TGIT_QUOTE(TGIT_DEFMINOR)
#define TGIT_DEFSTRMICRO TGIT_QUOTE(TGIT_DEFMICRO)
#define TGIT_DEFSTRBUILD TGIT_QUOTE(TGIT_DEFBUILD)

const char *STRFILEVER = TGIT_QUOTE(TGIT_DEFMAJOR) "." TGIT_QUOTE(TGIT_DEFMINOR) "." TGIT_QUOTE(TGIT_DEFMICRO) "." TGIT_QUOTE(TGIT_DEFBUILD);
const char *STRPRODUCTVER = TGIT_QUOTE(TGIT_DEFMAJOR) "." TGIT_QUOTE(TGIT_DEFMINOR) "." TGIT_QUOTE(TGIT_DEFMICRO) "." TGIT_QUOTE(TGIT_DEFBUILD);
const TCHAR *WCSFILEVER = TGIT_LQUOTE(TGIT_DEFMAJOR) L"." TGIT_LQUOTE(TGIT_DEFMINOR) L"." TGIT_LQUOTE(TGIT_DEFMICRO) L"." TGIT_LQUOTE(TGIT_DEFBUILD);
const TCHAR *WCSPRODUCTVER = TGIT_LQUOTE(TGIT_DEFMAJOR) L"." TGIT_LQUOTE(TGIT_DEFMINOR) L"." TGIT_LQUOTE(TGIT_DEFMICRO) L"." TGIT_LQUOTE(TGIT_DEFBUILD);

#define FILEVER        TGIT_DEFMAJOR,TGIT_DEFMINOR,TGIT_DEFMICRO,TGIT_DEFBUILD
#define PRODUCTVER     TGIT_DEFMAJOR,TGIT_DEFMINOR,TGIT_DEFMICRO,TGIT_DEFBUILD
#define STRFILEVER     TGIT_DEFSTRMAJOR "." TGIT_DEFSTRMINOR "." TGIT_DEFSTRMICRO "." TGIT_DEFSTRBUILD
#define STRPRODUCTVER  TGIT_DEFSTRMAJOR "." TGIT_DEFSTRMINOR "." TGIT_DEFSTRMICRO "." TGIT_DEFSTRBUILD

int TGIT_VERMAJOR = TGIT_DEFMAJOR;
int TGIT_VERMINOR = TGIT_DEFMINOR;
int TGIT_VERMICRO = TGIT_DEFMICRO;
int TGIT_VERBUILD = TGIT_DEFBUILD;
const char *TGIT_VERDATE = __DATE__;

#ifdef _WIN64
#define TGIT_PLATFORM		"64 Bit"
#else
#define TGIT_PLATFORM		"32 Bit"
#endif

#define PREVIEW		0
