<?php
//
// TortoiseSVN variables for the Drupal status pages
//
// Copyright (C) 2004-2008 the TortoiseSVN team
// This file is distributed under the same license as TortoiseSVN
//
// $Author: steveking $
// $Date: 2008-10-27 18:55:00 +0800 (Mon, 27 Oct 2008) $
// $Rev: 14406 $
//
// Author: Lübbe Onken 2004-2008
//         Stefan Küng 2004-2008
//

// 'Constants' that do not change upon a release
$tsvn_var['sf_project']="138498";
$tsvn_var['url1']="http://downloads.sourceforge.net/tortoisesvn/";
$tsvn_var['url2']="?download";
$tsvn_var['repos_base']="http://tortoisesvn.tigris.org/svn/tortoisesvn/";
$tsvn_var['flagpath']="/flags/world.small/";

// Variables that change upon each release
$tsvn_var['release']="1.5.5";
$tsvn_var['build']="14361";
$tsvn_var['build_x64']="14361";
$tsvn_var['svnver']="1.5.4";
$tsvn_var['sf_release_id']="635612";

$tsvn_var['repos_trunk']=$tsvn_var['repos_base'].'trunk/';
$tsvn_var['repos_branch']=$tsvn_var['repos_base'].'branches/1.5.x/';
?>
